### ISSUE TITLE
Error when upload pdf file and No error with txt file

### ISSUE THREAD

**Issue by mahmodDAHOL** [h2oai/h2ogpt#1018]
Traceback (most recent call last):
  File "C:\Users\FPCC\miniconda3\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\FPCC\miniconda3\lib\site-packages\urllib3\connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\FPCC\miniconda3\lib\site-packages\urllib3\connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "C:\Users\FPCC\miniconda3\lib\http\client.py", line 1253, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\FPCC\miniconda3\lib\http\client.py", line 1299, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\FPCC\miniconda3\lib\http\client.py", line 1248, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\FPCC\miniconda3\lib\http\client.py", line 1047, in _send_output
    self.send(chunk)
  File "C:\Users\FPCC\miniconda3\lib\http\client.py", line 969, in send
    self.sock.sendall(data)
  File "C:\Users\FPCC\miniconda3\lib\ssl.py", line 1204, in sendall
    v = self.send(byte_view[count:])
  File "C:\Users\FPCC\miniconda3\lib\ssl.py", line 1173, in send
    return self._sslobj.write(data)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\FPCC\miniconda3\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\FPCC\miniconda3\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "C:\Users\FPCC\miniconda3\lib\site-packages\urllib3\util\retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\FPCC\miniconda3\lib\site-packages\urllib3\packages\six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\FPCC\miniconda3\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\FPCC\miniconda3\lib\site-packages\urllib3\connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\FPCC\miniconda3\lib\site-packages\urllib3\connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "C:\Users\FPCC\miniconda3\lib\http\client.py", line 1253, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\FPCC\miniconda3\lib\http\client.py", line 1299, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\FPCC\miniconda3\lib\http\client.py", line 1248, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\FPCC\miniconda3\lib\http\client.py", line 1047, in _send_output
    self.send(chunk)
  File "C:\Users\FPCC\miniconda3\lib\http\client.py", line 969, in send
    self.sock.sendall(data)
  File "C:\Users\FPCC\miniconda3\lib\ssl.py", line 1204, in sendall
    v = self.send(byte_view[count:])
  File "C:\Users\FPCC\miniconda3\lib\ssl.py", line 1173, in send
    return self._sslobj.write(data)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\FPCC\miniconda3\lib\site-packages\gradio_client\client.py", line 292, in predict
    return self.submit(*args, api_name=api_name, fn_index=fn_index).result()
  File "C:\Users\FPCC\miniconda3\lib\site-packages\gradio_client\client.py", line 1131, in result
    return super().result(timeout=timeout)
  File "C:\Users\FPCC\miniconda3\lib\concurrent\futures\_base.py", line 445, in result
    return self.__get_result()
  File "C:\Users\FPCC\miniconda3\lib\concurrent\futures\_base.py", line 390, in __get_result
    raise self._exception
  File "C:\Users\FPCC\miniconda3\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\FPCC\miniconda3\lib\site-packages\gradio_client\client.py", line 797, in _inner
    data = self.serialize(*data)
  File "C:\Users\FPCC\miniconda3\lib\site-packages\gradio_client\client.py", line 965, in serialize
    uploaded_files = self._upload(files)
  File "C:\Users\FPCC\miniconda3\lib\site-packages\gradio_client\client.py", line 881, in _upload
    r = requests.post(
  File "C:\Users\FPCC\miniconda3\lib\site-packages\requests\api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\FPCC\miniconda3\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\FPCC\miniconda3\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\FPCC\miniconda3\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\FPCC\miniconda3\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

**Comment by pseudotensor** [comment]
Not seen, looks like a connection error on client side.  Do you have the server errors?
