### ISSUE TITLE
bitsandbytes: RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x2 and 1x5120)

### ISSUE THREAD

**Issue by pseudotensor** [h2oai/h2ogpt#104]
e82b642860f67b5a416e9f737563cf9a35213194

repeatedly do:
1) "Write the longest story possible about birds." and submit
2) Close tab
3) re-open tab
4) Repeat 1-4 many times.  Memory stays at 76%, but hit the below eventually after about 5 trials

Once happens, everything is dead, can't use chatbot.

Seems bitsandbytes is not thread safe.

But seems to only happen on https://github.com/h2oai/h2ogpt/pull/98

But if I try on main branch, then no such issues.  So perhaps transformers/HF way is flawed in some way.

```
Exception in thread Thread-27 (generate):
Traceback (most recent call last):
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/transformers/generation/utils.py", line 1485, in generate
    return self.sample(
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/transformers/generation/utils.py", line 2524, in sample
    outputs = self(
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/transformers/models/gpt_neox/modeling_gpt_neox.py", line 662, in forward
    outputs = self.gpt_neox(
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/transformers/models/gpt_neox/modeling_gpt_neox.py", line 553, in forward
    outputs = layer(
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/transformers/models/gpt_neox/modeling_gpt_neox.py", line 320, in forward
    attention_layer_outputs = self.attention(
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/transformers/models/gpt_neox/modeling_gpt_neox.py", line 156, in forward
    attn_output = self.dense(attn_output)
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/bitsandbytes/nn/modules.py", line 320, in forward
    out = bnb.matmul(x, self.weight, bias=self.bias, state=self.state)
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py", line 500, in matmul
    return MatMul8bitLt.apply(A, B, out, bias, state)
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py", line 417, in forward
    output += torch.matmul(subA, state.subB)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x2 and 1x5120)
Exception in thread Thread-25 (generate):
```

**Comment by pseudotensor** [comment]
High concurrency (10) runs fine (just slower), no more memory.

![image](https://user-images.githubusercontent.com/2249614/235573732-53ea4a8a-7c62-441e-8e6d-cb0c0a449e47.png)

**Comment by pseudotensor** [comment]
```
    attn_output = self.dense(attn_output)
  File "/home/user/.pyenv/versions/3.8.9/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/.pyenv/versions/3.8.9/lib/python3.8/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/user/.pyenv/versions/3.8.9/lib/python3.8/site-packages/bitsandbytes/nn/modules.py", line 320, in forward
    out = bnb.matmul(x, self.weight, bias=self.bias, state=self.state)
  File "/home/user/.pyenv/versions/3.8.9/lib/python3.8/site-packages/bitsandbytes/autograd/_functions.py", line 500, in matmul
    return MatMul8bitLt.apply(A, B, out, bias, state)
  File "/home/user/.pyenv/versions/3.8.9/lib/python3.8/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/user/.pyenv/versions/3.8.9/lib/python3.8/site-packages/bitsandbytes/autograd/_functions.py", line 417, in forward
    output += torch.matmul(subA, state.subB)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x3 and 1x5120)
```

**Comment by pseudotensor** [comment]
chatbot2:
```
File "/home/user/app/utils.py", line 312, in run
    self._return = self._target(*self._args, **self._kwargs)
  File "/home/user/app/generate.py", line 1221, in generate_with_exceptions
    func(*args, **kwargs)
  File "/home/user/.pyenv/versions/3.10.11/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/user/.pyenv/versions/3.10.11/lib/python3.10/site-packages/transformers/generation/utils.py", line 1485, in generate
    return self.sample(
  File "/home/user/.pyenv/versions/3.10.11/lib/python3.10/site-packages/transformers/generation/utils.py", line 2524, in sample
    outputs = self(
  File "/home/user/.pyenv/versions/3.10.11/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/.pyenv/versions/3.10.11/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/user/.pyenv/versions/3.10.11/lib/python3.10/site-packages/transformers/models/gpt_neox/modeling_gpt_neox.py", line 662, in forward
    outputs = self.gpt_neox(
  File "/home/user/.pyenv/versions/3.10.11/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/.pyenv/versions/3.10.11/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/user/.pyenv/versions/3.10.11/lib/python3.10/site-packages/transformers/models/gpt_neox/modeling_gpt_neox.py", line 553, in forward
    outputs = layer(
  File "/home/user/.pyenv/versions/3.10.11/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/.pyenv/versions/3.10.11/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/user/.pyenv/versions/3.10.11/lib/python3.10/site-packages/transformers/models/gpt_neox/modeling_gpt_neox.py", line 320, in forward
    attention_layer_outputs = self.attention(
  File "/home/user/.pyenv/versions/3.10.11/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/.pyenv/versions/3.10.11/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/user/.pyenv/versions/3.10.11/lib/python3.10/site-packages/transformers/models/gpt_neox/modeling_gpt_neox.py", line 116, in forward
    qkv = self.query_key_value(hidden_states)
  File "/home/user/.pyenv/versions/3.10.11/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/.pyenv/versions/3.10.11/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/user/.pyenv/versions/3.10.11/lib/python3.10/site-packages/bitsandbytes/nn/modules.py", line 388, in forward
    out = bnb.matmul(x, self.weight, bias=self.bias, state=self.state)
  File "/home/user/.pyenv/versions/3.10.11/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py", line 559, in matmul
    return MatMul8bitLt.apply(A, B, out, bias, state)
  File "/home/user/.pyenv/versions/3.10.11/lib/python3.10/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/user/.pyenv/versions/3.10.11/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py", line 417, in forward
    output += torch.matmul(subA, state.subB)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x5 and 6x15360)

Logs
[App](https://huggingface.co/spaces/h2oai/h2ogpt-chatbot)
[Files](https://huggingface.co/spaces/h2oai/h2ogpt-chatbot/tree/main)
Community
2
[Settings](https://huggingface.co/spaces/h2oai/h2ogpt-chatbot/settings)
```

**Comment by pseudotensor** [comment]
```
ing: 2023-06-13 11:18:00.307193
Task exception was never retrieved
future: <Task finished name='rrsegm1gcdd_42' coro=<Queue.process_events() done, defined at /home/user/.pyenv/versions/3.10.11/lib/python3.10/site-packages/gradio/queueing.py:343> exception=WebSocketDisconnect(1001)>
Traceback (most recent call last):
  File "/home/user/.pyenv/versions/3.10.11/lib/python3.10/site-packages/gradio/queueing.py", line 347, in process_events
    client_awake = await self.gather_event_data(event)
  File "/home/user/.pyenv/versions/3.10.11/lib/python3.10/site-packages/gradio/queueing.py", line 220, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
  File "/home/user/.pyenv/versions/3.10.11/lib/python3.10/site-packages/gradio/queueing.py", line 453, in get_message
    data = await asyncio.wait_for(
  File "/home/user/.pyenv/versions/3.10.11/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/home/user/.pyenv/versions/3.10.11/lib/python3.10/site-packages/starlette/websockets.py", line 133, in receive_json
    self._raise_on_disconnect(message)
  File "/home/user/.pyenv/versions/3.10.11/lib/python3.10/site-packages/starlette/websockets.py", line 105, in _raise_on_disconnect
    raise WebSocketDisconnect(message["code"])
starlette.websockets.WebSocketDisconnect: 1001
Ping: 2023-06-13 11:19:00.319226
Ping: 2023-06-13 11:20:00.306471
Ping: 2023-06-13 11:21:00.310302
Ping: 2023-06-13 11:22:00.106455
Ping: 2023-06-13 11:23:00.305702
Ping: 2023-06-13 11:24:00.303837
Ping: 2023-06-13 11:25:00.293153
Ping: 2023-06-13 11:26:00.306246
Ping: 2023-06-13 11:27:00.295840
Add chats exception: 'utf-8' codec can't decode byte 0xe2 in position 10: invalid continuation byte
Ping: 2023-06-13 11:28:00.308972
GPU Error: prompt: <human>: hello
<bot>: Hello! How can I help you today?
<human>: What are the eligibility criteria for recognising UFCP?
<bot>: inputs_decoded: <human>: hello
<bot>: Hello! How can I help you today?
<human>: What are the eligibility criteria for recognising UFCP?
<bot>: exception: mat1 and mat2 shapes cannot be multiplied (1x7 and 6x15360)
Traceback (most recent call last):
  File "/home/user/app/generate.py", line 1221, in generate_with_exceptions
    func(*args, **kwargs)
  File "/home/user/.pyenv/versions/3.10.11/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/user/.pyenv/versions/3.10.11/lib/python3.10/site-packages/transformers/generation/utils.py", line 1485, in generate
    return self.sample(
  File "/home/user/.pyenv/versions/3.10.11/lib/python3.10/site-packages/transformers/generation/utils.py", line 2524, in sample
    outputs = self(
  File "/home/user/.pyenv/versions/3.10.11/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/.pyenv/versions/3.10.11/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/user/.pyenv/versions/3.10.11/lib/python3.10/site-packages/transformers/models/gpt_neox/modeling_gpt_neox.py", line 662, in forward
    outputs = self.gpt_neox(
  File "/home/user/.pyenv/versions/3.10.11/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/.pyenv/versions/3.10.11/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/user/.pyenv/versions/3.10.11/lib/python3.10/site-packages/transformers/models/gpt_neox/modeling_gpt_neox.py", line 553, in forward
    outputs = layer(
  File "/home/user/.pyenv/versions/3.10.11/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/.pyenv/versions/3.10.11/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/user/.pyenv/versions/3.10.11/lib/python3.10/site-packages/transformers/models/gpt_neox/modeling_gpt_neox.py", line 320, in forward
    attention_layer_outputs = self.attention(
  File "/home/user/.pyenv/versions/3.10.11/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/.pyenv/versions/3.10.11/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/user/.pyenv/versions/3.10.11/lib/python3.10/site-packages/transformers/models/gpt_neox/modeling_gpt_neox.py", line 116, in forward
    qkv = self.query_key_value(hidden_states)
  File "/home/user/.pyenv/versions/3.10.11/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/.pyenv/versions/3.10.11/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/user/.pyenv/versions/3.10.11/lib/python3.10/site-packages/bitsandbytes/nn/modules.py", line 388, in forward
    out = bnb.matmul(x, self.weight, bias=self.bias, state=self.state)
  File "/home/user/.pyenv/versions/3.10.11/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py", line 559, in matmul
    return MatMul8bitLt.apply(A, B, out, bias, state)
  File "/home/user/.pyenv/versions/3.10.11/lib/python3.10/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/user/.pyenv/versions/3.10.11/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py", line 417, in forward
    output += torch.matmul(subA, state.subB)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x7 and 6x15360)
thread exception: (<class 'RuntimeError'>, RuntimeError('mat1 and mat2 shapes cannot be multiplied (1x7 and 6x15360)'), <traceback object at 0x7faff7b03840>)
make stop: (<class 'RuntimeError'>, RuntimeError('mat1 and mat2 shapes cannot be multiplied (1x7 and 6x15360)'), <traceback object at 0x7faff7b03840>)
```

**Comment by llmwesee** [comment]
when i hit the stop button the generation stops but when asking something new it throws the same error? why it happens and how to resolve it.
can we Use the torch.mm() function instead of torch.matmul() in functions.py file, which can handle matrices of different shapes.

**Comment by pseudotensor** [comment]
I'd guess it's a bug in bitsandbytes.  We'll have to wait for fixes there.  You can try latest bitsandbytes instead of our default.

**Comment by kartikWorld** [comment]
Has this issue resolved ? Is this only issue with bitsandbytes or Even with Tesla GPU machines ?

**Comment by pseudotensor** [comment]
I've not seen the issue in long time, and h2oGPT recently updated to latest bitsandbytes, so hopefully improved.  I'm going to close for now until see again.
