### ISSUE TITLE
Pydantic validation error 

### ISSUE THREAD

**Issue by tstanek390** [h2oai/h2ogpt#1052]
Hi there,
everytime I run the initial command : python generate.py --base_model='llama' --prompt_type=llama2 --score_model=None --langchain_mode='UserData' --user_path=user_path --model_path_llama=https://huggingface.co/TheBloke/Llama-2-7b-Chat-GGUF/resolve/main/llama-2-7b-chat.Q6_K.gguf --max_seq_len=4096

I'm getting this error :

Using Model llama
0it [00:00, ?it/s]
0it [00:00, ?it/s]
Loaded 0 sources for potentially adding to UserData
Starting get_model: llama 
Starting get_model: llama 
Starting get_model: llama 
Starting get_model: llama 
Traceback (most recent call last):
  File "/Users/admin/AI/h2ogpt/h2ogpt/generate.py", line 16, in <module>
    entrypoint_main()
  File "/Users/admin/AI/h2ogpt/h2ogpt/generate.py", line 12, in entrypoint_main
    H2O_Fire(main)
  File "/Users/admin/AI/h2ogpt/h2ogpt/src/utils.py", line 64, in H2O_Fire
    fire.Fire(component=component, command=args)
  File "/Users/admin/miniforge3/envs/h2ogpt/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/Users/admin/miniforge3/envs/h2ogpt/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/Users/admin/miniforge3/envs/h2ogpt/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/Users/admin/AI/h2ogpt/h2ogpt/src/gen.py", line 1417, in main
    model0, tokenizer0, device = get_model_retry(reward_type=False,
  File "/Users/admin/AI/h2ogpt/h2ogpt/src/gen.py", line 1765, in get_model_retry
    model1, tokenizer1, device1 = get_model(**kwargs)
  File "/Users/admin/AI/h2ogpt/h2ogpt/src/gen.py", line 1996, in get_model
    model, tokenizer, device = get_model_tokenizer_gpt4all(base_model,
  File "/Users/admin/AI/h2ogpt/h2ogpt/src/gpt4all_llm.py", line 27, in get_model_tokenizer_gpt4all
    model, tokenizer, redo, max_seq_len = get_llm_gpt4all(**llama_kwargs)
  File "/Users/admin/AI/h2ogpt/h2ogpt/src/gpt4all_llm.py", line 175, in get_llm_gpt4all
    llm = cls(**model_kwargs)
  File "/Users/admin/miniforge3/envs/h2ogpt/lib/python3.10/site-packages/langchain/load/serializable.py", line 97, in __init__
    super().__init__(**kwargs)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for H2OLlamaCpp
__root__
  Could not load Llama model from path: https://huggingface.co/TheBloke/Llama-2-7b-Chat-GGUF/resolve/main/llama-2-7b-chat.Q6_K.gguf. Received error Model path does not exist: https://huggingface.co/TheBloke/Llama-2-7b-Chat-GGUF/resolve/main/llama-2-7b-chat.Q6_K.gguf (type=value_error)

The client could be started with python generate.py , but when I want to load model in the interface I get the same error as when initializing. I've tried to completely uninstall a reinstall Homebrew, Conda with envs, the h2opt, pydantic etc., but still getting this error. Any idea what could case the issue? 
P.S. The same error occurs with different --model_path_llama values, either HF links, and local paths.

Thanks a lot and have a nice sunday!
T.

**Comment by pseudotensor** [comment]
Thanks.  I can run your command without error.

If you only had issues with the URL, I'd suspect this block is causing you issues: 

https://github.com/h2oai/h2ogpt/blob/f51ffa7079ecfb86ed9ba0fbc47be69b11bfb8b0/src/gpt4all_llm.py#L152-L162

maybe `url_alive` is not detecting the link as valid, even though it is..

For local paths, I don't have a good idea of what could be wrong.

@Mathanraj-Sharma any chance you can try on your mac?

**Comment by tstanek390** [comment]
Thanks a lot for your reply and the whole awesome project. After another complete reinstall of the repo and clean conda environment, it has started to work properly! I suppose there was some collision of the installed packages and / or envs. Sorry for bothering you with my mistake. Take care!
