### ISSUE TITLE
AssertionError: Missing ['from_ui'] on Previously Working Script

### ISSUE THREAD

**Issue by NickThompson42** [h2oai/h2ogpt#1062]
I have encountered a sudden issue with the `generate.py` script in the `h2ogpt` project. The script executed successfully on 2023-11-06, but started throwing an error on 2023-11-07 without any changes to the codebase.

Command Executed:
```bash
python $HOME/h2ogpt/generate.py \
  --base_model=h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3 \
  --prompt_type=human_bot \
  --max_seq_len=4096 \
  --score_model=None \
  --langchain_mode=UserData \
  --langchain_modes="['LLM', 'UserData', 'MyData']" \
  --user_path=user_path \
  --share=False \
  --hf_embedding_model=sentence \
  --transformers/all-MiniLM-L6-v2 \
  --cli=True \
  --use_gpu_id=False
```

Console Output/Error:
```
Using Model h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3
load INSTRUCTOR_Transformer
max_seq_length  512
0it [00:00, ?it/s]
0it [00:00, ?it/s]
Loaded 0 sources for potentially adding to UserData
Traceback (most recent call last):
  File "/home/user/h2ogpt/generate.py", line 16, in <module>
    entrypoint_main()
  File "/home/user/h2ogpt/generate.py", line 12, in entrypoint_main
    H2O_Fire(main)
  File "/home/user/h2ogpt/src/utils.py", line 64, in H2O_Fire
    fire.Fire(component=component, command=args)
  File "/home/user/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/user/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/user/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, kwargs)
  File "/home/user/h2ogpt/src/gen.py", line 1325, in main
    return run_cli(get_kwargs(run_cli, exclude_names=['model_state0'], locals()))
  File "/home/user/h2ogpt/src/utils.py", line 976, in get_kwargs
    assert not missing_kwargs, "Missing %s" % missing_kwargs
AssertionError: Missing ['from_ui']
```

Attempts to Resolve:
- Tried adding `--from_ui=False` to the command line, but the issue persists.
- Checked for any recent changes in the environment or codebase.

Request for Help:
I am looking for insights or suggestions on how to resolve this error. Any help or guidance would be greatly appreciated.

**Comment by anno143** [comment]
i am facing same issue, any update why it happened

**Comment by ccollab23** [comment]
Same here after update

**Comment by NickThompson42** [comment]
no information yet on why it happened

**Comment by pseudotensor** [comment]
Hi, sorry about that, just extra argument was added to cli by accident.

**Comment by NickThompson42** [comment]
great, thank you for the prompt fix. I'll test it out and see if there are any other issues.
