### ISSUE TITLE
Loading model trained in H2O studio giving us error

### ISSUE THREAD

**Issue by Cansiano** [h2oai/h2ogpt#1065]
We got this error when trying to load our finetuned model form h2o Studio, can you help please? :
python3 generate.py --base_model=/home/kocka/Data/model/model_unnatural-rat --langchain_mode=UserData --score_model=None --use_gpu_id=False --max_seq_len=4096 --share=False --gradio_offline_level=1 --h2ocolors=False --hf_embedding_model=BAAI/bge-large-en-v1.5 --enable-heap-analytics=False --cut_distance=1000000 --prompt_type=llama2 --top_k_docs=-1 --enable_pdf_ocr='on' --langchain_modes="['LLM','UserData','UserData2']" --do_sample=True --max_max_new_tokens=4096 --max_new_tokens=4096 --auth=auth.json    Using Model /home/kocka/data/model/model_unnatural-rat
Starting get_model: /home/kocka/Data/model/model_unnatural-rat
/home/kocka/.local/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py:1006: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers.
  warnings.warn(
Overriding max_seq_len -> 4096
/home/kocka/.local/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:1727: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers.
  warnings.warn(
Traceback (most recent call last):
  File "/home/kocka/h2ogpt/generate.py", line 16, in <module>
    entrypoint_main()
  File "/home/kocka/h2ogpt/generate.py", line 12, in entrypoint_main
    H2O_Fire(main)
  File "/home/kocka/h2ogpt/src/utils.py", line 64, in H2O_Fire
    fire.Fire(component=component, command=args)
  File "/home/kocka/.local/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/kocka/.local/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/kocka/.local/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/kocka/h2ogpt/src/gen.py", line 1203, in main
    model0, tokenizer0, device = get_model(reward_type=False,
  File "/home/kocka/h2ogpt/src/gen.py", line 1633, in get_model
    tokenizer = tokenizer_loader.from_pretrained(tokenizer_base_model, **tokenizer_kwargs)
  File "/home/kocka/.local/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 1854, in from_pretrained
    return cls._from_pretrained(
  File "/home/kocka/.local/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2017, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/home/kocka/.local/lib/python3.10/site-packages/transformers/models/llama/tokenization_llama.py", line 156, in __init__
    self.sp_model = self.get_spm_processor()
  File "/home/kocka/.local/lib/python3.10/site-packages/transformers/models/llama/tokenization_llama.py", line 169, in get_spm_processor
    with open(self.vocab_file, "rb") as f:
TypeError: expected str, bytes or os.PathLike object, not NoneType

Thanks!

**Comment by pseudotensor** [comment]
@psinger @pascal-pfeiffer Do you have any idea why a model from LLM Studio would have some issue like this?  Seems to be missing the vocab.json file.  Thanks!

**Comment by pseudotensor** [comment]
Please show full contents of the path in question.

**Comment by maxjeblick** [comment]
Thanks for reporting @Cansiano.

It seems that we missed to include `tokenizer.model` in the download zip. You can directly grab it from the LLM Studio experiment output folder and place it in the corresponding folder.

The issue should be fixed with [this](https://github.com/h2oai/h2o-llmstudio/pull/490) PR.
