### ISSUE TITLE
AttributeError: 'Client' object has no attribute '_producer'

### ISSUE THREAD

**Issue by slavag** [h2oai/h2ogpt#1066]
Hi, I'm trying to upload document to MyData
But I'm getting that error :
<img width="993" alt="image" src="https://github.com/h2oai/h2ogpt/assets/511540/41dacf33-71f7-4608-a9ff-8d754c8da3d5">

Log :
```
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 144.91it/s]
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/Users/slava/Documents/Development/private/AI/h2ogpt/src/gpt_langchain.py", line 5905, in update_user_db
    return _update_user_db(file, db1s=db1s,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/Documents/Development/private/AI/h2ogpt/src/gpt_langchain.py", line 6144, in _update_user_db
    db = get_db(sources, use_openai_embedding=use_openai_embedding,
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/Documents/Development/private/AI/h2ogpt/src/gpt_langchain.py", line 177, in get_db
    if hasattr(api._producer, 'max_batch_size'):
               ^^^^^^^^^^^^^
AttributeError: 'Client' object has no attribute '_producer'

Traceback (most recent call last):
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/gradio/queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/gradio/route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/gradio/blocks.py", line 1550, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/gradio/blocks.py", line 1185, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/gradio/utils.py", line 661, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "/Users/slava/Documents/Development/private/AI/h2ogpt/src/gradio_runner.py", line 4856, in get_sources_gr
    get_sources(db1s, selection_docs_state1, requests_state1, langchain_mode,
  File "/Users/slava/Documents/Development/private/AI/h2ogpt/src/gpt_langchain.py", line 5842, in get_sources
    db = get_any_db(db1s, langchain_mode, langchain_mode_paths, langchain_mode_types,
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/Documents/Development/private/AI/h2ogpt/src/gpt_langchain.py", line 5806, in get_any_db
    get_existing_db(db, persist_directory, load_db_if_exists, db_type,
  File "/Users/slava/Documents/Development/private/AI/h2ogpt/src/gpt_langchain.py", line 3239, in get_existing_db
    db = chroma_class(persist_directory=persist_directory, embedding_function=embedding,
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/langchain/vectorstores/chroma.py", line 119, in __init__
    self._client = chromadb.Client(_client_settings)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/chromadb/__init__.py", line 190, in Client
    return ClientCreator(tenant=tenant, database=database, settings=settings)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/chromadb/api/client.py", line 133, in __init__
    super().__init__(settings=settings)
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/chromadb/api/client.py", line 36, in __init__
    SharedSystemClient._create_system_if_not_exists(self._identifier, settings)
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/chromadb/api/client.py", line 55, in _create_system_if_not_exists
    raise ValueError(
ValueError: An instance of Chroma already exists for users/fbf7d99b-d2a6-48b2-b246-0c6ac06c4911/db_dir_MyData with different settings
Traceback (most recent call last):
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/gradio/queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/gradio/route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/gradio/blocks.py", line 1550, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/gradio/blocks.py", line 1185, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/gradio/utils.py", line 661, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "/Users/slava/Documents/Development/private/AI/h2ogpt/src/gradio_runner.py", line 4890, in get_source_files_given_langchain_mode_gr
    return get_source_files_given_langchain_mode(db1s, selection_docs_state1, requests_state1, None,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/Documents/Development/private/AI/h2ogpt/src/gpt_langchain.py", line 6212, in get_source_files_given_langchain_mode
    db = get_any_db(db1s, langchain_mode, langchain_mode_paths, langchain_mode_types,
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/Documents/Development/private/AI/h2ogpt/src/gpt_langchain.py", line 5806, in get_any_db
    get_existing_db(db, persist_directory, load_db_if_exists, db_type,
  File "/Users/slava/Documents/Development/private/AI/h2ogpt/src/gpt_langchain.py", line 3239, in get_existing_db
    db = chroma_class(persist_directory=persist_directory, embedding_function=embedding,
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/langchain/vectorstores/chroma.py", line 119, in __init__
    self._client = chromadb.Client(_client_settings)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/chromadb/__init__.py", line 190, in Client
    return ClientCreator(tenant=tenant, database=database, settings=settings)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/chromadb/api/client.py", line 133, in __init__
    super().__init__(settings=settings)
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/chromadb/api/client.py", line 36, in __init__
    SharedSystemClient._create_system_if_not_exists(self._identifier, settings)
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/chromadb/api/client.py", line 55, in _create_system_if_not_exists
    raise ValueError(
ValueError: An instance of Chroma already exists for users/fbf7d99b-d2a6-48b2-b246-0c6ac06c4911/db_dir_MyData with different settings
Traceback (most recent call last):
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/gradio/queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/gradio/route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/gradio/blocks.py", line 1550, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/gradio/blocks.py", line 1185, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/gradio/utils.py", line 661, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "/Users/slava/Documents/Development/private/AI/h2ogpt/src/gradio_runner.py", line 4856, in get_sources_gr
    get_sources(db1s, selection_docs_state1, requests_state1, langchain_mode,
  File "/Users/slava/Documents/Development/private/AI/h2ogpt/src/gpt_langchain.py", line 5842, in get_sources
    db = get_any_db(db1s, langchain_mode, langchain_mode_paths, langchain_mode_types,
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/Documents/Development/private/AI/h2ogpt/src/gpt_langchain.py", line 5806, in get_any_db
    get_existing_db(db, persist_directory, load_db_if_exists, db_type,
  File "/Users/slava/Documents/Development/private/AI/h2ogpt/src/gpt_langchain.py", line 3239, in get_existing_db
    db = chroma_class(persist_directory=persist_directory, embedding_function=embedding,
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/langchain/vectorstores/chroma.py", line 119, in __init__
    self._client = chromadb.Client(_client_settings)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/chromadb/__init__.py", line 190, in Client
    return ClientCreator(tenant=tenant, database=database, settings=settings)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/chromadb/api/client.py", line 133, in __init__
    super().__init__(settings=settings)
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/chromadb/api/client.py", line 36, in __init__
    SharedSystemClient._create_system_if_not_exists(self._identifier, settings)
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/chromadb/api/client.py", line 55, in _create_system_if_not_exists
    raise ValueError(
ValueError: An instance of Chroma already exists for users/fbf7d99b-d2a6-48b2-b246-0c6ac06c4911/db_dir_MyData with different settings
```
I removed the content os the users folder, and yet getting that errors.
Please advise.
Thanks

**Comment by pseudotensor** [comment]
The original error that cascades into the other errors is:
```
Traceback (most recent call last):
  File "/Users/slava/Documents/Development/private/AI/h2ogpt/src/gpt_langchain.py", line 5905, in update_user_db
    return _update_user_db(file, db1s=db1s,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/Documents/Development/private/AI/h2ogpt/src/gpt_langchain.py", line 6144, in _update_user_db
    db = get_db(sources, use_openai_embedding=use_openai_embedding,
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/Documents/Development/private/AI/h2ogpt/src/gpt_langchain.py", line 177, in get_db
    if hasattr(api._producer, 'max_batch_size'):
               ^^^^^^^^^^^^^
AttributeError: 'Client' object has no attribute '_producer'
```

My guess is that you have a newer version of chroma that isn't the one we support.  Can you double check your chroma version via `pip freeze | grep chroma` matches the version in `requirements_optional_langchain.txt` ?

**Comment by slavag** [comment]
@pseudotensor Indeed, I had 0.4.15. The work around (https://github.com/h2oai/h2ogpt/commit/ab3b6ed28a3896f5aca22a80bc997e14f304f892) didn't fixed the issue, so I downgraded chromadb tp 0.4.13.
Thanks

**Comment by pseudotensor** [comment]
@slavag Ok thanks.  I'm curious what you hit when you used that work-around.  It couldn't fail the same way.

**Comment by slavag** [comment]
@pseudotensor 
```
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 117.52it/s]
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/Users/slava/Documents/Development/private/AI/h2ogpt/src/gpt_langchain.py", line 5945, in update_user_db
    return _update_user_db(file, db1s=db1s,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/Documents/Development/private/AI/h2ogpt/src/gpt_langchain.py", line 6184, in _update_user_db
    db = get_db(sources, use_openai_embedding=use_openai_embedding,
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/Documents/Development/private/AI/h2ogpt/src/gpt_langchain.py", line 185, in get_db
    db = Chroma.from_documents(documents=sources_batch, **from_kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/langchain/vectorstores/chroma.py", line 684, in from_documents
    return cls.from_texts(
           ^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/langchain/vectorstores/chroma.py", line 620, in from_texts
    chroma_collection = cls(
                        ^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/langchain/vectorstores/chroma.py", line 119, in __init__
    self._client = chromadb.Client(_client_settings)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/chromadb/__init__.py", line 190, in Client
    return ClientCreator(tenant=tenant, database=database, settings=settings)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/chromadb/api/client.py", line 133, in __init__
    super().__init__(settings=settings)
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/chromadb/api/client.py", line 36, in __init__
    SharedSystemClient._create_system_if_not_exists(self._identifier, settings)
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/chromadb/api/client.py", line 55, in _create_system_if_not_exists
    raise ValueError(
ValueError: An instance of Chroma already exists for users/147c1efd-ae63-457d-bde3-e5174bb759e6/db_dir_MyData with different settings

Traceback (most recent call last):
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/gradio/queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/gradio/route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/gradio/blocks.py", line 1550, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/gradio/blocks.py", line 1185, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/gradio/utils.py", line 661, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "/Users/slava/Documents/Development/private/AI/h2ogpt/src/gradio_runner.py", line 4856, in get_sources_gr
    get_sources(db1s, selection_docs_state1, requests_state1, langchain_mode,
  File "/Users/slava/Documents/Development/private/AI/h2ogpt/src/gpt_langchain.py", line 5882, in get_sources
    db = get_any_db(db1s, langchain_mode, langchain_mode_paths, langchain_mode_types,
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/Documents/Development/private/AI/h2ogpt/src/gpt_langchain.py", line 5846, in get_any_db
    get_existing_db(db, persist_directory, load_db_if_exists, db_type,
  File "/Users/slava/Documents/Development/private/AI/h2ogpt/src/gpt_langchain.py", line 3256, in get_existing_db
    db = chroma_class(persist_directory=persist_directory, embedding_function=embedding,
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/langchain/vectorstores/chroma.py", line 119, in __init__
    self._client = chromadb.Client(_client_settings)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/chromadb/__init__.py", line 190, in Client
    return ClientCreator(tenant=tenant, database=database, settings=settings)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/chromadb/api/client.py", line 133, in __init__
    super().__init__(settings=settings)
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/chromadb/api/client.py", line 36, in __init__
    SharedSystemClient._create_system_if_not_exists(self._identifier, settings)
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/chromadb/api/client.py", line 55, in _create_system_if_not_exists
    raise ValueError(
ValueError: An instance of Chroma already exists for users/147c1efd-ae63-457d-bde3-e5174bb759e6/db_dir_MyData with different settings
Traceback (most recent call last):
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/gradio/queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/gradio/route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/gradio/blocks.py", line 1550, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/gradio/blocks.py", line 1185, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/gradio/utils.py", line 661, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "/Users/slava/Documents/Development/private/AI/h2ogpt/src/gradio_runner.py", line 4890, in get_source_files_given_langchain_mode_gr
    return get_source_files_given_langchain_mode(db1s, selection_docs_state1, requests_state1, None,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/Documents/Development/private/AI/h2ogpt/src/gpt_langchain.py", line 6252, in get_source_files_given_langchain_mode
    db = get_any_db(db1s, langchain_mode, langchain_mode_paths, langchain_mode_types,
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/Documents/Development/private/AI/h2ogpt/src/gpt_langchain.py", line 5846, in get_any_db
    get_existing_db(db, persist_directory, load_db_if_exists, db_type,
  File "/Users/slava/Documents/Development/private/AI/h2ogpt/src/gpt_langchain.py", line 3256, in get_existing_db
    db = chroma_class(persist_directory=persist_directory, embedding_function=embedding,
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/langchain/vectorstores/chroma.py", line 119, in __init__
    self._client = chromadb.Client(_client_settings)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/chromadb/__init__.py", line 190, in Client
    return ClientCreator(tenant=tenant, database=database, settings=settings)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/chromadb/api/client.py", line 133, in __init__
    super().__init__(settings=settings)
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/chromadb/api/client.py", line 36, in __init__
    SharedSystemClient._create_system_if_not_exists(self._identifier, settings)
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/chromadb/api/client.py", line 55, in _create_system_if_not_exists
    raise ValueError(
ValueError: An instance of Chroma already exists for users/147c1efd-ae63-457d-bde3-e5174bb759e6/db_dir_MyData with different settings
Traceback (most recent call last):
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/gradio/queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/gradio/route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/gradio/blocks.py", line 1550, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/gradio/blocks.py", line 1185, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/gradio/utils.py", line 661, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "/Users/slava/Documents/Development/private/AI/h2ogpt/src/gradio_runner.py", line 4856, in get_sources_gr
    get_sources(db1s, selection_docs_state1, requests_state1, langchain_mode,
  File "/Users/slava/Documents/Development/private/AI/h2ogpt/src/gpt_langchain.py", line 5882, in get_sources
    db = get_any_db(db1s, langchain_mode, langchain_mode_paths, langchain_mode_types,
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/Documents/Development/private/AI/h2ogpt/src/gpt_langchain.py", line 5846, in get_any_db
    get_existing_db(db, persist_directory, load_db_if_exists, db_type,
  File "/Users/slava/Documents/Development/private/AI/h2ogpt/src/gpt_langchain.py", line 3256, in get_existing_db
    db = chroma_class(persist_directory=persist_directory, embedding_function=embedding,
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/langchain/vectorstores/chroma.py", line 119, in __init__
    self._client = chromadb.Client(_client_settings)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/chromadb/__init__.py", line 190, in Client
    return ClientCreator(tenant=tenant, database=database, settings=settings)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/chromadb/api/client.py", line 133, in __init__
    super().__init__(settings=settings)
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/chromadb/api/client.py", line 36, in __init__
    SharedSystemClient._create_system_if_not_exists(self._identifier, settings)
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/chromadb/api/client.py", line 55, in _create_system_if_not_exists
    raise ValueError(
ValueError: An instance of Chroma already exists for users/147c1efd-ae63-457d-bde3-e5174bb759e6/db_dir_MyData with different settings
```

**Comment by pseudotensor** [comment]
Ok, at least it didn't fail same way in cascade, but I guess they changed something in chroma that breaks things.
