### ISSUE TITLE
Error when opening gradio UI on latest docker image

### ISSUE THREAD

**Issue by Blacksuan19** [h2oai/h2ogpt#1108]
running the docker image using `latest` image tag produces the below error when visiting gradio UI, the UI was working as intended on the previous docker image version.

```python
Traceback (most recent call last):
  File "/h2ogpt_conda/lib/python3.10/site-packages/gradio/queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
  File "/h2ogpt_conda/lib/python3.10/site-packages/gradio/route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
  File "/h2ogpt_conda/lib/python3.10/site-packages/gradio/blocks.py", line 1550, in process_api
    result = await self.call_function(
  File "/h2ogpt_conda/lib/python3.10/site-packages/gradio/blocks.py", line 1185, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/h2ogpt_conda/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/h2ogpt_conda/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/h2ogpt_conda/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/h2ogpt_conda/lib/python3.10/site-packages/gradio/utils.py", line 661, in wrapper
    response = f(*args, **kwargs)
  File "/workspace/src/gradio_runner.py", line 2410, in login
    gr.update(choices=list(roles_state1.keys())), \
AttributeError: 'list' object has no attribute 'keys'
```

![image](https://github.com/h2oai/h2ogpt/assets/10248473/99b23743-ba71-4004-9f92-ec99c0891bca)

here's the command used

```sh

export DATA_HOME=~/h2ogpt_mistral

mkdir -p ${DATA_HOME}/.cache
mkdir -p ${DATA_HOME}/save
mkdir -p ${DATA_HOME}/user_path
mkdir -p ${DATA_HOME}/db_dir_UserData
mkdir -p ${DATA_HOME}/users
mkdir -p ${DATA_HOME}/db_nonusers
docker run \
       --gpus all \
       --runtime=nvidia \
       --shm-size=2g \
       -p 7860:7860 \
       --rm --init \
       -v /etc/passwd:/etc/passwd:ro \
       -v /etc/group:/etc/group:ro \
       -u `id -u`:`id -g` \
       -v "${HOME}"/h2ogpt_mistral/.cache:/workspace/.cache \
       -v "${HOME}"/h2ogpt_mistral/save:/workspace/save \
       -v "${HOME}"/h2ogpt_mistral/user_path:/workspace/user_path \
       -v "${HOME}"/h2ogpt_mistral/db_dir_UserData:/workspace/db_dir_UserData \
       -v "${HOME}"/h2ogpt_mistral/users:/workspace/users \
       -v "${HOME}"/h2ogpt_mistral/db_nonusers:/workspace/db_nonusers \
       gcr.io/vorvan/h2oai/h2ogpt-runtime:latest /workspace/generate.py \
          --base_model=llama \
          --model_path_llama=https://huggingface.co/TheBloke/Mistral-7B-Instruct-v0.1-GGUF/resolve/main/mistral-7b-instruct-v0.1.Q4_K_M.gguf \
          --prompt_type=mistral \
          --save_dir='/workspace/save/' \
          --use_gpu_id=False \
          --score_model=None \
          --max_max_new_tokens=2048 \
          --max_new_tokens=1024 \
          --max_seq_len=4096 \
          --enable_ocr=True \
          --visible_h2ogpt_links=False \
          --visible_h2ogpt_logo=False \
          --visible_h2ogpt_qrcode=False \
          --visible_system_tab=False \
          --visible_models_tab=False \
          --visible_expert_tab=False \
          --visible_login_tab=False \
          --visible_chatbot_label=False \
          --actions_in_sidebar=True \
          --height=700 \
          --auth_access='closed' \
          --auth="[('test','test')]" \


```

**Comment by pseudotensor** [comment]
Fixed thanks.  Building new docker image...
