### ISSUE TITLE
download models from specific hugging face model branch

### ISSUE THREAD

**Issue by fahadshery** [h2oai/h2ogpt#1114]
Hi,

TheBloke publishes quite a few GPTQ models. Each model sits in a different branch. 
If you pass the model name like this: `TheBloke/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3-GPTQ`, it downloads the `main` model from the `main` branch. 

When I try and download a specific model such as: `gptq-4bit-32g-actorder_True` it fails:
```
OSError: Can't load the configuration of 'TheBloke/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3-GPTQ:gptq-4bit-32g-actorder_True'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'TheBloke/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3-GPTQ:gptq-4bit-32g-actorder_True' is the correct path to a directory containing a config.json file
```

Yes, all branches have a valid `config.json` file present in them....Any ideas how to select a specific model from a specific branch in hugging face?

Cheers,

**Comment by pseudotensor** [comment]
If you give the full resolved url we will use that.  It's among the examples in the FAQ:

https://github.com/h2oai/h2ogpt/blob/main/docs/FAQ.md#thebloke

i.e.

```
python generate.py --base_model=https://huggingface.co/TheBloke/Llama-2-7b-Chat-GGUF/resolve/main/llama-2-7b-chat.Q6_K.gguf
```

Just need to be the resolved path.

**Comment by fahadshery** [comment]
> ```
> python generate.py --base_model=https://huggingface.co/TheBloke/Llama-2-7b-Chat-GGUF/resolve/main/llama-2-7b-chat.Q6_K.gguf
> ```
> 
> Just need to be the resolved path.

The Problem is that not all available models have the complete resolved URL...For example here is the GPTQ model for h2ogpt...look [here](https://huggingface.co/TheBloke/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3-GPTQ)

This is the model I wish to tryout: https://huggingface.co/TheBloke/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3-GPTQ/tree/gptq-8bit--1g-actorder_True

I pass it as:
```
export CUDA_VISIBLE_DEVICES=0
docker run \
       --gpus all \
       --restart always \
       --runtime=nvidia \
       --shm-size=4g \
       -p 7860:7860 \
       --network host \
       -e CUDA_VISIBLE_DEVICES=$CUDA_VISIBLE_DEVICES \
       -v /etc/passwd:/etc/passwd:ro \
       -v /etc/group:/etc/group:ro \
       -u `id -u`:`id -g` \
       -v "${HOME}"/.cache:/workspace/.cache \
       -v "${HOME}"/save:/workspace/save \
       -v "${HOME}"/user_path:/workspace/user_path \
       -v "${HOME}"/db_dir_UserData:/workspace/db_dir_UserData \
       -v "${HOME}"/users:/workspace/users \
       -v "${HOME}"/db_nonusers:/workspace/db_nonusers \
       gcr.io/vorvan/h2oai/h2ogpt-runtime:0.1.0 /workspace/generate.py \
          --base_model=https://huggingface.co/TheBloke/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3-GPTQ/tree/gptq-8bit--1g-actorder_True \
          --prompt_type=prompt_answer \
          --use_safetensors=True \
          --save_dir='/workspace/save/' \
          --use_gpu_id=False \
          --score_model=None \
          --max_max_new_tokens=2048 \
          --max_new_tokens=1024
```

It produces the following error:
```
Downloading (…)it--1g-actorder_True: 100%|██████████| 111k/111k [00:00<00:00, 2.02MB/s]
Starting get_model: https://huggingface.co/TheBloke/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3-GPTQ/tree/gptq-8bit--1g-actorder_True
Downloading (…)it--1g-actorder_True: 100%|██████████| 111k/111k [00:00<00:00, 3.49MB/s]
Starting get_model: https://huggingface.co/TheBloke/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3-GPTQ/tree/gptq-8bit--1g-actorder_True
Downloading (…)it--1g-actorder_True: 100%|██████████| 111k/111k [00:00<00:00, 7.80MB/s]
Starting get_model: https://huggingface.co/TheBloke/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3-GPTQ/tree/gptq-8bit--1g-actorder_True
Downloading (…)it--1g-actorder_True: 100%|██████████| 111k/111k [00:00<00:00, 8.03MB/s]
Traceback (most recent call last):
  File "/h2ogpt_conda/lib/python3.10/site-packages/transformers/configuration_utils.py", line 705, in _get_config_dict
    config_dict = cls._dict_from_json_file(resolved_config_file)
  File "/h2ogpt_conda/lib/python3.10/site-packages/transformers/configuration_utils.py", line 801, in _dict_from_json_file
    return json.loads(text)
  File "/h2ogpt_conda/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/h2ogpt_conda/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/h2ogpt_conda/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/generate.py", line 16, in <module>
    entrypoint_main()
  File "/workspace/generate.py", line 12, in entrypoint_main
    H2O_Fire(main)
  File "/workspace/src/utils.py", line 65, in H2O_Fire
    fire.Fire(component=component, command=args)
  File "/h2ogpt_conda/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/h2ogpt_conda/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/h2ogpt_conda/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/workspace/src/gen.py", line 1487, in main
    model0, tokenizer0, device = get_model_retry(reward_type=False,
  File "/workspace/src/gen.py", line 1809, in get_model_retry
    model1, tokenizer1, device1 = get_model(**kwargs)
  File "/workspace/src/gen.py", line 1925, in get_model
    config, _, max_seq_len = get_config(base_model, **config_kwargs, raise_exception=False)
  File "/workspace/src/gen.py", line 1572, in get_config
    config = AutoConfig.from_pretrained(base_model, token=use_auth_token,
  File "/h2ogpt_conda/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 1034, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/h2ogpt_conda/lib/python3.10/site-packages/transformers/configuration_utils.py", line 620, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/h2ogpt_conda/lib/python3.10/site-packages/transformers/configuration_utils.py", line 708, in _get_config_dict
    raise EnvironmentError(
OSError: It looks like the config file at '/tmp/tmpjanzofef' is not a valid JSON file.
```

**Comment by Zirgite** [comment]
I did use the the path. The download has started. Then I load it.  However when I go to chat mode it is still the previous default model.
The example I used was:
 https://huggingface.co/TheBloke/digital-socrates-13B-GGUF/resolve/main/digital-socrates-13b.Q6_K.gguf 
Here I tried to download not the recommended model but a custom model. The model was downloaded but at the end it did not work. Just using the model name and the Bloke as address results in the system choosing the recommended model but it still does not work after being downloaded.

**Comment by Zirgite** [comment]
I solved the issue. In fact when downloading the model it is not enough to switch the model from the central drop down menu and press the load button.

It is necessary to make one more step.
There is a menu that is on the right that may be hidden but you need to open.'
Choose LLaMa.cpp Model Path/URL (for Base Model: llama)
Here on the path it is the old model. So actually you wont#t switch the model but you will load the old model.

In my case I have downloaded a custom model from the bloke:
https://huggingface.co/TheBloke/digital-socrates-13B-GGUF/resolve/main/digital-socrates-13b.Q6_K.gguf

Then I had not just to use this path in the central menu but also to put the same path to the menu on the right.

https://huggingface.co/TheBloke/digital-socrates-13B-GGUF/resolve/main/digital-socrates-13b.Q6_K.gguf

**Comment by Zirgite** [comment]
Apparently what I was reporting was a visual glitch that was fixed right now.

**Comment by pseudotensor** [comment]
--revision is used to get from a specific branch
