### ISSUE TITLE
I am unable to fully implement Langchain's experimental AUTOGPT agent

### ISSUE THREAD

**Issue by Antho331364** [h2oai/h2ogpt#1116]
Hello there!

I'm trying to implement the Langchain's experimental AUTOGPT agent with GPT4 model from OPENAI but I'm facing an issue when the agent has finished to proceed the query and have to return his result.

Below is the error stack trace I have:

`thread exception: (<class 'TypeError'>, TypeError("'str' object is not callable"), <traceback object at 0x7fcc2be0d5c0>)
make stop: (<class 'TypeError'>, TypeError("'str' object is not callable"), <traceback object at 0x7fcc2be0d5c0>)
hit stop
Traceback (most recent call last):
  File "/home/anthox/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/gradio/queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
  File "/home/anthox/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/gradio/route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/anthox/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/gradio/blocks.py", line 1550, in process_api
    result = await self.call_function(
  File "/home/anthox/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/gradio/blocks.py", line 1199, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/home/anthox/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/gradio/utils.py", line 519, in async_iteration
    return await iterator.__anext__()
  File "/home/anthox/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/gradio/utils.py", line 512, in __anext__
    return await anyio.to_thread.run_sync(
  File "/home/anthox/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/anthox/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/anthox/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/anthox/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/gradio/utils.py", line 495, in run_sync_iterator_async
    return next(iterator)
  File "/home/anthox/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/gradio/utils.py", line 649, in gen_wrapper
    yield from f(*args, **kwargs)
  File "/home/anthox/development/h2ogpt/src/gradio_runner.py", line 3701, in bot
    for res in get_response(fun1, history, chatbot_role1, speaker1, tts_language1, roles_state1,
  File "/home/anthox/development/h2ogpt/src/gradio_runner.py", line 3615, in get_response
    for output_fun in fun1():
  File "/home/anthox/development/h2ogpt/src/gen.py", line 3099, in evaluate
    for r in run_qa_db(
  File "/home/anthox/development/h2ogpt/src/gpt_langchain.py", line 4421, in _run_qa_db
    answer = yield from run_target_func(query=query,
  File "/home/anthox/development/h2ogpt/src/gpt_langchain.py", line 4561, in run_target
    raise thread.exc
  File "/home/anthox/development/h2ogpt/src/utils.py", line 448, in run
    self._return = self._target(*self._args, **self._kwargs)
TypeError: 'str' object is not callable
`
To implement the AUTOGPT agent I followed this Langchain : [cookbook](https://github.com/langchain-ai/langchain/blob/master/cookbook/autogpt/autogpt.ipynb)

I edited the gpt_langchain.py file and added the following code to the get_chain() func just before "if LangChainAgent.SMART.value in langchain_agents:" condition instruction:

`
if LangChainAgent.AUTOGPT.value in langchain_agents:
        from langchain_experimental.autonomous_agents.autogpt.agent import AutoGPT
        from langchain.agents import load_tools

        tools = load_tools(["ddg-search"], llm=llm)

        from langchain.docstore import InMemoryDocstore
        from langchain.embeddings import OpenAIEmbeddings
        from langchain.vectorstores import FAISS

        # Define your embedding model
        embeddings_model = OpenAIEmbeddings()
        # Initialize the vectorstore as empty
        import faiss

        embedding_size = 1536
        index = faiss.IndexFlatL2(embedding_size)
        vectorstore = FAISS(embeddings_model.embed_query, index, InMemoryDocstore({}), {})

        agent = AutoGPT.from_llm_and_tools(
            ai_name="AI Assist",
            ai_role="Assistant",
            tools=tools,
            llm=llm,
            memory=vectorstore.as_retriever(),
        )
        # Set verbose to be true
        agent.chain.verbose = True
        target = agent.run([query])

        docs = []
        scores = []
        num_docs_before_cut = 0
        use_llm_if_no_docs = True
        return docs, target, scores, num_docs_before_cut, use_llm_if_no_docs, top_k_docs_max_show, \
            llm, model_name, streamer, prompt_type_out, async_output, only_new_text`

When the program hit the "return" statement I can see that the "target" variable contains the complete llm answer by debugging the program execution step by step.

Then the run_target function is called with the following parameters and the error is raised is this function execution:
<a href="https://ibb.co/HtKFmKM"><img src="https://i.ibb.co/8rmKFmR/Capture-d-cran-du-2023-11-21-16-35-52.png" alt="Capture-d-cran-du-2023-11-21-16-35-52" border="0"></a>

I know that this agent is experimental and even not yet implemented in the H2OGPT framework but could be useful for me and the community of this project to use it. 

Any help would be greatly appreciated to help me to fix the issue I'm facing. 

If I forgot to mention some useful information to help the debug, please ask me relevant information needed.

**Edit:**

I finally succeed to have the answer from AUTOGPT Agent in the gradio UI by understanding how the SmartLLMAgent works.

I updated how the Agent is called with:

` 
chain_kwargs = [query]
chain_func = agent.run
target = wrapped_partial(chain_func, chain_kwargs)
`
        
So now it works fine, except that the reasoning and action steps aren't fully streamed to the UI. I had some when running the agent (actually only the first one) but they were removed from the UI once the final response was generated. It would be nice to keep the intermediate steps or at least show them with the final answers like for example with the possibility of showing the "sources" of the Q/A functionality but I don't know how to implement this behavior.

**Comment by abugaberd** [comment]
Thanks so much for sharing this as I've been facing similar issues. Any chance you could share the final code? Where does the   "chain_kwargs = [query] chain_func = agent.run target = wrapped_partial(chain_func, chain_kwargs)" line go?

**Comment by Antho331364** [comment]
> Thanks so much for sharing this as I've been facing similar issues. Any chance you could share the final code? Where does the "chain_kwargs = [query] chain_func = agent.run target = wrapped_partial(chain_func, chain_kwargs)" line go?

@abugaberd sure, you can find the final code on my fork [here](https://github.com/Antho331364/h2ogpt/blob/main/src/gpt_langchain.py#L5066)
