### ISSUE TITLE
Can't run TheBloke/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3-GPTQ model using Docker

### ISSUE THREAD

**Issue by fahadshery** [h2oai/h2ogpt#1118]
Here is the Docker run command:
```
fahadshery@chatgpt:~$ ./run_h2oai-h2ogpt-gm-oasst1-en-2048-falcon-7b-v3.sh
export CUDA_VISIBLE_DEVICES=0
docker run \
       --gpus all \
       --runtime=nvidia \
       --shm-size=4g \
       -p 7860:7860 \
       --rm --init \
       --network host \
       -e CUDA_VISIBLE_DEVICES=$CUDA_VISIBLE_DEVICES \
       -v /etc/passwd:/etc/passwd:ro \
       -v /etc/group:/etc/group:ro \
       -u `id -u`:`id -g` \
       -v "${HOME}"/.cache:/workspace/.cache \
       -v "${HOME}"/save:/workspace/save \
       -v "${HOME}"/user_path:/workspace/user_path \
       -v "${HOME}"/db_dir_UserData:/workspace/db_dir_UserData \
       -v "${HOME}"/users:/workspace/users \
       -v "${HOME}"/db_nonusers:/workspace/db_nonusers \
       gcr.io/vorvan/h2oai/h2ogpt-runtime:0.1.0 /workspace/generate.py \
          --base_model=TheBloke/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3-GPTQ \
          --prompt_type=prompt_answer \
          --save_dir='/workspace/save/' \
          --use_autogptq=True \
          --load_gptq=True \
          --load_8bit=True \
          --use_gpu_id=False \
          --score_model=None \
          --max_new_tokens=512
```

Getting the following error:
```
Could not determine --max_seq_len, setting to 2048.  Pass if not correct
Traceback (most recent call last):
  File "/workspace/generate.py", line 16, in <module>
    entrypoint_main()
  File "/workspace/generate.py", line 12, in entrypoint_main
    H2O_Fire(main)
  File "/workspace/src/utils.py", line 65, in H2O_Fire
    fire.Fire(component=component, command=args)
  File "/h2ogpt_conda/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/h2ogpt_conda/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/h2ogpt_conda/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/workspace/src/gen.py", line 1487, in main
    model0, tokenizer0, device = get_model_retry(reward_type=False,
  File "/workspace/src/gen.py", line 1809, in get_model_retry
    model1, tokenizer1, device1 = get_model(**kwargs)
  File "/workspace/src/gen.py", line 2054, in get_model
    return get_hf_model(load_8bit=load_8bit,
  File "/workspace/src/gen.py", line 2266, in get_hf_model
    model = model_loader(
  File "/h2ogpt_conda/lib/python3.10/site-packages/auto_gptq/modeling/auto.py", line 108, in from_quantized
    return quant_func(
  File "/h2ogpt_conda/lib/python3.10/site-packages/auto_gptq/modeling/_base.py", line 786, in from_quantized
    resolved_archive_file = cached_file(model_name_or_path, model_basename + ext, **cached_file_kwargs)
TypeError: unsupported operand type(s) for +: 'bool' and 'str'
```

**Comment by fahadshery** [comment]
Not sure but I am able to run it in a painfully slow manner using the following docker run command:
```
max_seq_length  512
export CUDA_VISIBLE_DEVICES=0
docker run \
       --gpus all \
       --runtime=nvidia \
       --shm-size=4g \
       -p 7860:7860 \
       --rm --init \
       --network host \
       -e CUDA_VISIBLE_DEVICES=$CUDA_VISIBLE_DEVICES \
       -v /etc/passwd:/etc/passwd:ro \
       -v /etc/group:/etc/group:ro \
       -u `id -u`:`id -g` \
       -v "${HOME}"/.cache:/workspace/.cache \
       -v "${HOME}"/save:/workspace/save \
       -v "${HOME}"/user_path:/workspace/user_path \
       -v "${HOME}"/db_dir_UserData:/workspace/db_dir_UserData \
       -v "${HOME}"/users:/workspace/users \
       -v "${HOME}"/db_nonusers:/workspace/db_nonusers \
       gcr.io/vorvan/h2oai/h2ogpt-runtime:0.1.0 /workspace/generate.py \
          --base_model=h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3 \
          --prompt_type=prompt_answer \
          --save_dir='/workspace/save/' \
          --load_4bit=True \
          --use_gpu_id=False \
          --score_model=None \
          --temperature=0.3 \
          --max_new_tokens=1024
```
