### ISSUE TITLE
Missing libcudart.so.12 library on docker image when using AWQ based model

### ISSUE THREAD

**Issue by Blacksuan19** [h2oai/h2ogpt#1137]
when running the docker image with an AWQ based model I get the below error.

```python
Traceback (most recent call last):
  File "/workspace/generate.py", line 16, in <module>
    entrypoint_main()
  File "/workspace/generate.py", line 12, in entrypoint_main
    H2O_Fire(main)
  File "/workspace/src/utils.py", line 65, in H2O_Fire
    fire.Fire(component=component, command=args)
  File "/h2ogpt_conda/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/h2ogpt_conda/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/h2ogpt_conda/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/workspace/src/gen.py", line 1684, in main
    model0, tokenizer0, device = get_model_retry(reward_type=False,
  File "/workspace/src/gen.py", line 2007, in get_model_retry
    model1, tokenizer1, device1 = get_model(**kwargs)
  File "/workspace/src/gen.py", line 2144, in get_model
    get_loaders(model_name=base_model, reward_type=reward_type, llama_type=llama_type,
  File "/workspace/src/loaders.py", line 102, in get_loaders
    from awq import AutoAWQForCausalLM
  File "/h2ogpt_conda/lib/python3.10/site-packages/awq/__init__.py", line 2, in <module>
    from awq.models.auto import AutoAWQForCausalLM
  File "/h2ogpt_conda/lib/python3.10/site-packages/awq/models/__init__.py", line 1, in <module>
    from .mpt import MptAWQForCausalLM
  File "/h2ogpt_conda/lib/python3.10/site-packages/awq/models/mpt.py", line 1, in <module>
    from .base import BaseAWQForCausalLM
  File "/h2ogpt_conda/lib/python3.10/site-packages/awq/models/base.py", line 12, in <module>
    from awq.quantize.quantizer import AwqQuantizer
  File "/h2ogpt_conda/lib/python3.10/site-packages/awq/quantize/quantizer.py", line 11, in <module>
    from awq.modules.linear import WQLinear_GEMM, WQLinear_GEMV
  File "/h2ogpt_conda/lib/python3.10/site-packages/awq/modules/linear.py", line 4, in <module>
    import awq_inference_engine  # with CUDA kernels
ImportError: libcudart.so.12: cannot open shared object file: No such file or directory
```

here's a snippet of the command used to run the image

```bash
docker run \
       --pull=always \
       --gpus all \
       --runtime=nvidia \
       --shm-size=2g \
       -p 7860:7860 \
       --rm --init \
       -v /etc/passwd:/etc/passwd:ro \
       -v /etc/group:/etc/group:ro \
       -u `id -u`:`id -g` \
       gcr.io/vorvan/h2oai/h2ogpt-runtime:latest /workspace/generate.py \
          --use_gpu_id=False \
          --score_model=None \
          --base_model=TheBloke/Mistral-7B-Instruct-v0.1-AWQ \
          --prompt_type=mistral \
          --use_safetensors=True \
          --max_seq_len=4096 \
          --max_new_tokens=1024 \
          --max_max_new_tokens=2048 \

```

**Comment by jberries** [comment]
Yes - I get the same error too in docker when loading AWQ model

**Comment by pseudotensor** [comment]
Wow, sorry for delay,  lost first message.  Should be fixed, rebuilding image.
