### ISSUE TITLE
TypeError: 'type' object does not support the context manager protocol

### ISSUE THREAD

**Issue by slavag** [h2oai/h2ogpt#1158]
Hi, 
Latest commit 727152b2aa58c33e6e28a39c307cc76a39bd8e51
When specifying --langchain_modes, without --langchain_modes works ok.
```
soundfile, librosa, and wavio not installed, disabling STT
soundfile, librosa, and wavio not installed, disabling TTS
Using Model llama
Must install DocTR and LangChain installed if enabled DocTR, disabling
Traceback (most recent call last):
  File "/Users/slava/Documents/Development/private/AI/h2ogpt/generate.py", line 16, in <module>
    entrypoint_main()
  File "/Users/slava/Documents/Development/private/AI/h2ogpt/generate.py", line 12, in entrypoint_main
    H2O_Fire(main)
  File "/Users/slava/Documents/Development/private/AI/h2ogpt/src/utils.py", line 65, in H2O_Fire
    fire.Fire(component=component, command=args)
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/Documents/Development/private/AI/h2ogpt/src/gen.py", line 1565, in main
    db = prep_langchain(persist_directory1,
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/Documents/Development/private/AI/h2ogpt/src/gpt_langchain.py", line 3436, in prep_langchain
    get_existing_db(None, persist_directory, load_db_if_exists,
  File "/Users/slava/Documents/Development/private/AI/h2ogpt/src/gpt_langchain.py", line 3653, in get_existing_db
    with get_context_cast():
TypeError: 'type' object does not support the context manager protocol
```

Please advise.

Thanks

**Comment by pseudotensor** [comment]
8dc0664b16eed252aee946380fdaad0e98a3f53f probably fixes
