### ISSUE TITLE
ModuleNotFoundError: No module named 'doctr.utils'

### ISSUE THREAD

**Issue by DocMAX** [h2oai/h2ogpt#1167]
Probably not an h2ogpt issue but maybe someone can help.
i allready installed doctr and dr-utils pip packages.
```
(.venv) root@gpt:~/github/h2ogpt# pip freeze | grep doctr
doctr==1.9.0

Dec 04 10:39:46 gpt h2ogpt[4518]: Failed to ingest user_path/0002385.pdf due to Traceback (most recent call last):
Dec 04 10:39:46 gpt h2ogpt[4518]:   File "/root/github/h2ogpt/src/gpt_langchain.py", line 3093, in path_to_doc1
Dec 04 10:39:46 gpt h2ogpt[4518]:     res = file_to_doc(file,
Dec 04 10:39:46 gpt h2ogpt[4518]:           ^^^^^^^^^^^^^^^^^
Dec 04 10:39:46 gpt h2ogpt[4518]:   File "/root/github/h2ogpt/src/gpt_langchain.py", line 2863, in file_to_doc
Dec 04 10:39:46 gpt h2ogpt[4518]:     from image_doctr import H2OOCRLoader
Dec 04 10:39:46 gpt h2ogpt[4518]:   File "/root/github/h2ogpt/src/image_doctr.py", line 16, in <module>
Dec 04 10:39:46 gpt h2ogpt[4518]:     from doctr.utils.common_types import AbstractFile
Dec 04 10:39:46 gpt h2ogpt[4518]: ModuleNotFoundError: No module named 'doctr.utils'
Dec 04 10:39:46 gpt h2ogpt[4519]: Failed to ingest user_path/0001267.pdf due to Traceback (most recent call last):
Dec 04 10:39:46 gpt h2ogpt[4519]:   File "/root/github/h2ogpt/src/gpt_langchain.py", line 3093, in path_to_doc1
Dec 04 10:39:46 gpt h2ogpt[4519]:     res = file_to_doc(file,
Dec 04 10:39:46 gpt h2ogpt[4519]:           ^^^^^^^^^^^^^^^^^
Dec 04 10:39:46 gpt h2ogpt[4519]:   File "/root/github/h2ogpt/src/gpt_langchain.py", line 2863, in file_to_doc
Dec 04 10:39:46 gpt h2ogpt[4519]:     from image_doctr import H2OOCRLoader
Dec 04 10:39:46 gpt h2ogpt[4519]:   File "/root/github/h2ogpt/src/image_doctr.py", line 16, in <module>
Dec 04 10:39:46 gpt h2ogpt[4519]:     from doctr.utils.common_types import AbstractFile
Dec 04 10:39:46 gpt h2ogpt[4519]: ModuleNotFoundError: No module named 'doctr.utils'

```

**Comment by DocMAX** [comment]
Crazy, DocTR docs clearly say doctr.utils.common_types is valid...
