### ISSUE TITLE
'Llama' object has no attribute 'ctx'

### ISSUE THREAD

**Issue by gpnath82** [h2oai/h2ogpt#1180]
I am receiving this error on latest pull.

Can somebody please help.

I have  llama_cpp_python Version: 0.2.20

Could not load Llama model from path: llamacpp_path/llama-2-7b-chat.Q6_K.gguf. Received error  (type=value_error)
Exception ignored in: <function Llama.__del__ at 0x7fd4ec709ab0>
Traceback (most recent call last):
  File "/home/jupyter/h2ogpt/h2o/lib/python3.10/site-packages/llama_cpp_cuda/llama.py", line 1502, in __del__
AttributeError: 'Llama' object has no attribute 'ctx'

**Comment by pseudotensor** [comment]
That's a cascade error, meaning it's just because something else failed earlier.

What failed is it couldn't find `llamacpp_path/llama-2-7b-chat.Q6_K.gguf` .

I presume you have this file?  If you don't, you need to either download it or choose/enter TheBloke HF link in the UI or CLI instead so we download it for you.

**Comment by gpnath82** [comment]
I do have this file in current folder

 ls -l llamacpp_path/llama-2-7b-chat.Q6_K.gguf
-rw-r--r-- 1 g30097220 g30097220 5529194176 Dec  5 16:48 llamacpp_path/llama-2-7b-chat.Q6_K.gguf

**Comment by pseudotensor** [comment]
Can you share rest of stack trace -- anything earlier than what you shared?

**Comment by gpnath82** [comment]
I still get the same error

llama_load_model_from_file: failed to load model
Exception ignored in: <function Llama.__del__ at 0x7f800c34b370>
Traceback (most recent call last):
  File "/home/jupyter/h2ogpt/h2o/lib/python3.10/site-packages/llama_cpp_cuda/llama.py", line 1502, in __del__
    if self.ctx is not None:
AttributeError: 'Llama' object has no attribute 'ctx'
Traceback (most recent call last):
  File "/home/jupyter/h2ogpt/h2o/lib/python3.10/site-packages/gradio/queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
  File "/home/jupyter/h2ogpt/h2o/lib/python3.10/site-packages/gradio/route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/jupyter/h2ogpt/h2o/lib/python3.10/site-packages/gradio/blocks.py", line 1550, in process_api
    result = await self.call_function(
  File "/home/jupyter/h2ogpt/h2o/lib/python3.10/site-packages/gradio/blocks.py", line 1185, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/jupyter/h2ogpt/h2o/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/jupyter/h2ogpt/h2o/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/jupyter/h2ogpt/h2o/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/jupyter/h2ogpt/h2o/lib/python3.10/site-packages/gradio/utils.py", line 661, in wrapper
    response = f(*args, **kwargs)
  File "/home/jupyter/h2ogpt/src/gradio_runner.py", line 4973, in load_model
    model1, tokenizer1, device1 = get_model_retry(**gradio_model_kwargs)
  File "/home/jupyter/h2ogpt/src/gen.py", line 2104, in get_model_retry
    model1, tokenizer1, device1 = get_model(**kwargs)
  File "/home/jupyter/h2ogpt/src/gen.py", line 2364, in get_model
    model, tokenizer, device = get_model_tokenizer_gpt4all(base_model,
  File "/home/jupyter/h2ogpt/src/gpt4all_llm.py", line 30, in get_model_tokenizer_gpt4all
    model, tokenizer, redo, max_seq_len = get_llm_gpt4all(**llama_kwargs)
  File "/home/jupyter/h2ogpt/src/gpt4all_llm.py", line 179, in get_llm_gpt4all
    llm = cls(**model_kwargs)
  File "/home/jupyter/h2ogpt/h2o/lib/python3.10/site-packages/langchain_core/load/serializable.py", line 97, in __init__
    super().__init__(**kwargs)
  File "/home/jupyter/h2ogpt/h2o/lib/python3.10/site-packages/pydantic/v1/main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 1 validation error for H2OLlamaCpp
__root__
  Could not load Llama model from path: llamacpp_path/llama-2-7b-chat.Q6_K.gguf. Received error  (type=value_error)
Exception ignored in: <function Llama.__del__ at 0x7f800c34b370>
Traceback (most recent call last):
  File "/home/jupyter/h2ogpt/h2o/lib/python3.10/site-packages/llama_cpp_cuda/llama.py", line 1502, in __del__
    if self.ctx is not None:
AttributeError: 'Llama' object has no attribute 'ctx'

**Comment by gpnath82** [comment]
@pseudotensor  Please see full error

Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
Started Gradio Server and/or GUI: server_name: localhost port: None
Use local URL: http://localhost:7860/
Starting get_model: llama
ggml_init_cublas: found 2 CUDA devices:
  Device 0: NVIDIA L4, compute capability 8.9
  Device 1: NVIDIA L4, compute capability 8.9
llama.cpp: loading model from llamacpp_path/zephyr-7b-beta.Q5_K_M.gguf
error loading model: unknown (magic, version) combination: 46554747, 00000003; is this really a GGML file?
llama_load_model_from_file: failed to load model
Starting get_model: llama
Already have llamacpp_path/zephyr-7b-beta.Q5_K_M.gguf from url https://huggingface.co/TheBloke/zephyr-7B-beta-GGUF/resolve/main/zephyr-7b-beta.Q5_K_M.gguf, delete file if invalid
llama.cpp: loading model from llamacpp_path/zephyr-7b-beta.Q5_K_M.gguf
error loading model: unknown (magic, version) combination: 46554747, 00000003; is this really a GGML file?
llama_load_model_from_file: failed to load model
Exception ignored in: <function Llama.__del__ at 0x7f800c34b370>
Traceback (most recent call last):
  File "/home/jupyter/h2ogpt/h2o/lib/python3.10/site-packages/llama_cpp_cuda/llama.py", line 1502, in __del__
    if self.ctx is not None:
AttributeError: 'Llama' object has no attribute 'ctx'
Starting get_model: llama
Already have llamacpp_path/zephyr-7b-beta.Q5_K_M.gguf from url https://huggingface.co/TheBloke/zephyr-7B-beta-GGUF/resolve/main/zephyr-7b-beta.Q5_K_M.gguf, delete file if invalid
llama.cpp: loading model from llamacpp_path/zephyr-7b-beta.Q5_K_M.gguf
error loading model: unknown (magic, version) combination: 46554747, 00000003; is this really a GGML file?
llama_load_model_from_file: failed to load model
Exception ignored in: <function Llama.__del__ at 0x7f800c34b370>
Traceback (most recent call last):
  File "/home/jupyter/h2ogpt/h2o/lib/python3.10/site-packages/llama_cpp_cuda/llama.py", line 1502, in __del__
    if self.ctx is not None:
AttributeError: 'Llama' object has no attribute 'ctx'
