### ISSUE TITLE
Error on Macbook M1

### ISSUE THREAD

**Issue by a-ml** [h2oai/h2ogpt#1258]
Hello,

**Enviroment:**
System: Macbook Pro M1 Max 64G
Base OS: Sonoma
Conda: 23.9.0

I've cloned the repo, create the virtual env using conda, installed all the requirements without error, but when trying to run the generate script I receive the error bellow:

```
❯ python generate.py --base_model=TheBloke/zephyr-7B-beta-GGUF --prompt_type=zephyr --max_seq_len=4096
soundfile, librosa, and wavio not installed, disabling STT
soundfile, librosa, and wavio not installed, disabling TTS
Using Model llama
Traceback (most recent call last):
  File "/Users/kapenge/Laboratories/coding/_ai/frameworks/h2ogpt/generate.py", line 16, in <module>
    entrypoint_main()
  File "/Users/kapenge/Laboratories/coding/_ai/frameworks/h2ogpt/generate.py", line 12, in entrypoint_main
    H2O_Fire(main)
  File "/Users/kapenge/Laboratories/coding/_ai/frameworks/h2ogpt/src/utils.py", line 65, in H2O_Fire
    fire.Fire(component=component, command=args)
  File "/Users/kapenge/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/Users/kapenge/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/Users/kapenge/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/Users/kapenge/Laboratories/coding/_ai/frameworks/h2ogpt/src/gen.py", line 1620, in main
    from src.gpt_langchain import get_embedding
  File "/Users/kapenge/Laboratories/coding/_ai/frameworks/h2ogpt/src/gpt_langchain.py", line 34, in <module>
    from langchain.callbacks import streaming_stdout
  File "/Users/kapenge/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/langchain/callbacks/__init__.py", line 10, in <module>
    from langchain_community.callbacks.aim_callback import AimCallbackHandler
  File "/Users/kapenge/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/langchain_community/callbacks/__init__.py", line 24, in <module>
    from langchain_community.callbacks.manager import (
  File "/Users/kapenge/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/langchain_community/callbacks/manager.py", line 14, in <module>
    from langchain_community.callbacks.tracers.wandb import WandbTracer
  File "/Users/kapenge/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/langchain_community/callbacks/tracers/__init__.py", line 4, in <module>
    from langchain_core.tracers.langchain_v1 import LangChainTracerV1
ModuleNotFoundError: No module named 'langchain_core.tracers.langchain_v1'
```

Please, need some hint.

**Comment by BillJones-SectorFlow** [comment]
Same error on Win 10.

**Comment by EmmaWebGH** [comment]
Same error on Win11, just made a post about it.
Is there something in the current version (I did a git clone just today) that is doing this? Should we pull an older version?

Apologies for the duplicate post, I didn't think the MAC in the headline applied to me, but reading this now, I see it's common.
https://github.com/h2oai/h2ogpt/issues/1260

Thanks

**Comment by pseudotensor** [comment]
5674a758c6c529bc0c6bdb0f9ca4a47c9c6b74af

But from langchain, had to pin to work around their mistake.  Fixed in above commit.

**Comment by pseudotensor** [comment]
If you already have env, this should fix:
```
pip install langchain==0.0.354 langchain_experimental==0.0.47 langchain-community==0.0.8 langsmith==0.0.77 langchain-core==0.1.6
```
