### ISSUE TITLE
Mixtral8x7 on A6000 48GB with RAG

### ISSUE THREAD

**Issue by davide445** [h2oai/h2ogpt#1274]
Was able to load mistralai/Mixtral-8x7B-Instruct-v0.1 using the --load_4bit=True quantization, using about 30GB VRAM. 
Loading an xlsx file containing the data I want (are just 220 cells with some text) the GPU go out of VRAM, testing on an A100 goes up to 78GB usage before settling down to 33GB again.

I tried loading --base_model=TheBloke/Mixtral-8x7B-Instruct-v0.1-GPTQ but got this error

`Traceback (most recent call last):
  File "/workspace/./generate.py", line 16, in <module>
    entrypoint_main()
  File "/workspace/./generate.py", line 12, in entrypoint_main
    H2O_Fire(main)
  File "/workspace/src/utils.py", line 65, in H2O_Fire
    fire.Fire(component=component, command=args)
  File "/h2ogpt_conda/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/h2ogpt_conda/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/h2ogpt_conda/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/workspace/src/gen.py", line 1971, in main
    model0, tokenizer0, device = get_model_retry(reward_type=False,
  File "/workspace/src/gen.py", line 2299, in get_model_retry
    model1, tokenizer1, device1 = get_model(**kwargs)
  File "/workspace/src/gen.py", line 2674, in get_model
    return get_hf_model(load_8bit=load_8bit,
  File "/workspace/src/gen.py", line 2878, in get_hf_model
    model = model_loader(
  File "/h2ogpt_conda/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 566, in from_pretrained
    return model_class.from_pretrained(
  File "/h2ogpt_conda/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3523, in from_pretrained
    model = quantizer.convert_model(model)
  File "/h2ogpt_conda/lib/python3.10/site-packages/optimum/gptq/quantizer.py", line 229, in convert_model
    self._replace_by_quant_layers(model, layers_to_be_replaced)
  File "/h2ogpt_conda/lib/python3.10/site-packages/optimum/gptq/quantizer.py", line 298, in _replace_by_quant_layers
    self._replace_by_quant_layers(child, names, name + "." + name1 if name != "" else name1)
  File "/h2ogpt_conda/lib/python3.10/site-packages/optimum/gptq/quantizer.py", line 298, in _replace_by_quant_layers
    self._replace_by_quant_layers(child, names, name + "." + name1 if name != "" else name1)
  File "/h2ogpt_conda/lib/python3.10/site-packages/optimum/gptq/quantizer.py", line 298, in _replace_by_quant_layers
    self._replace_by_quant_layers(child, names, name + "." + name1 if name != "" else name1)
  [Previous line repeated 1 more time]
  File "/h2ogpt_conda/lib/python3.10/site-packages/optimum/gptq/quantizer.py", line 282, in _replace_by_quant_layers
    new_layer = QuantLinear(
  File "/h2ogpt_conda/lib/python3.10/site-packages/auto_gptq/nn_modules/qlinear/qlinear_exllama.py", line 68, in __init__
    assert outfeatures % 32 == 0
AssertionError`

Tried loading --base_model=TheBloke/Mixtral-8x7B-Instruct-v0.1-AWQ and the UI started, but every prompt generate this error
`Traceback (most recent call last):
  File "/h2ogpt_conda/lib/python3.10/site-packages/gradio/queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
  File "/h2ogpt_conda/lib/python3.10/site-packages/gradio/route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
  File "/h2ogpt_conda/lib/python3.10/site-packages/gradio/blocks.py", line 1550, in process_api
    result = await self.call_function(
  File "/h2ogpt_conda/lib/python3.10/site-packages/gradio/blocks.py", line 1199, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/h2ogpt_conda/lib/python3.10/site-packages/gradio/utils.py", line 519, in async_iteration
    return await iterator.__anext__()
  File "/h2ogpt_conda/lib/python3.10/site-packages/gradio/utils.py", line 512, in __anext__
    return await anyio.to_thread.run_sync(
  File "/h2ogpt_conda/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/h2ogpt_conda/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/h2ogpt_conda/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/h2ogpt_conda/lib/python3.10/site-packages/gradio/utils.py", line 495, in run_sync_iterator_async
    return next(iterator)
  File "/h2ogpt_conda/lib/python3.10/site-packages/gradio/utils.py", line 649, in gen_wrapper
    yield from f(*args, **kwargs)
  File "/workspace/src/gradio_runner.py", line 4279, in bot
    for res in get_response(fun1, history, chatbot_role1, speaker1, tts_language1, roles_state1,
  File "/workspace/src/gradio_runner.py", line 4175, in get_response
    for output_fun in fun1():
  File "/workspace/src/gen.py", line 3640, in evaluate
    for r in run_qa_db(
  File "/workspace/src/gpt_langchain.py", line 5054, in _run_qa_db
    answer = yield from run_target_func(query=query,
  File "/workspace/src/gpt_langchain.py", line 5211, in run_target
    raise thread.exc
  File "/workspace/src/utils.py", line 460, in run
    self._return = self._target(*self._args, **self._kwargs)
  File "/h2ogpt_conda/lib/python3.10/site-packages/langchain/chains/base.py", line 316, in __call__
    raise e
  File "/h2ogpt_conda/lib/python3.10/site-packages/langchain/chains/base.py", line 310, in __call__
    self._call(inputs, run_manager=run_manager)
  File "/h2ogpt_conda/lib/python3.10/site-packages/langchain/chains/combine_documents/base.py", line 136, in _call
    output, extra_return_dict = self.combine_docs(
  File "/h2ogpt_conda/lib/python3.10/site-packages/langchain/chains/combine_documents/stuff.py", line 244, in combine_docs
    return self.llm_chain.predict(callbacks=callbacks, **inputs), {}
  File "/h2ogpt_conda/lib/python3.10/site-packages/langchain/chains/llm.py", line 293, in predict
    return self(kwargs, callbacks=callbacks)[self.output_key]
  File "/h2ogpt_conda/lib/python3.10/site-packages/langchain/chains/base.py", line 316, in __call__
    raise e
  File "/h2ogpt_conda/lib/python3.10/site-packages/langchain/chains/base.py", line 310, in __call__
    self._call(inputs, run_manager=run_manager)
  File "/h2ogpt_conda/lib/python3.10/site-packages/langchain/chains/llm.py", line 103, in _call
    response = self.generate([inputs], run_manager=run_manager)
  File "/h2ogpt_conda/lib/python3.10/site-packages/langchain/chains/llm.py", line 115, in generate
    return self.llm.generate_prompt(
  File "/h2ogpt_conda/lib/python3.10/site-packages/langchain_core/language_models/llms.py", line 521, in generate_prompt
    return self.generate(prompt_strings, stop=stop, callbacks=callbacks, **kwargs)
  File "/h2ogpt_conda/lib/python3.10/site-packages/langchain_core/language_models/llms.py", line 671, in generate
    output = self._generate_helper(
  File "/h2ogpt_conda/lib/python3.10/site-packages/langchain_core/language_models/llms.py", line 558, in _generate_helper
    raise e
  File "/h2ogpt_conda/lib/python3.10/site-packages/langchain_core/language_models/llms.py", line 545, in _generate_helper
    self._generate(
  File "/workspace/src/gpt_langchain.py", line 1417, in _generate
    rets = super()._generate(prompts, stop=stop, run_manager=run_manager, **kwargs)
  File "/h2ogpt_conda/lib/python3.10/site-packages/langchain_community/llms/huggingface_pipeline.py", line 203, in _generate
    responses = self.pipeline(batch_prompts)
  File "/h2ogpt_conda/lib/python3.10/site-packages/transformers/pipelines/text_generation.py", line 208, in __call__
    return super().__call__(text_inputs, **kwargs)
  File "/h2ogpt_conda/lib/python3.10/site-packages/transformers/pipelines/base.py", line 1121, in __call__
    outputs = list(final_iterator)
  File "/h2ogpt_conda/lib/python3.10/site-packages/transformers/pipelines/pt_utils.py", line 124, in __next__
    item = next(self.iterator)
  File "/h2ogpt_conda/lib/python3.10/site-packages/transformers/pipelines/pt_utils.py", line 125, in __next__
    processed = self.infer(item, **self.params)
  File "/h2ogpt_conda/lib/python3.10/site-packages/transformers/pipelines/base.py", line 1046, in forward
    model_outputs = self._forward(model_inputs, **forward_params)
  File "/workspace/src/h2oai_pipeline.py", line 257, in _forward
    return self.__forward(model_inputs, **generate_kwargs)
  File "/workspace/src/h2oai_pipeline.py", line 293, in __forward
    generated_sequence = self.model.generate(input_ids=input_ids, attention_mask=attention_mask, **generate_kwargs)
  File "/h2ogpt_conda/lib/python3.10/site-packages/awq/models/base.py", line 81, in generate
    return self.model.generate(*args, **kwargs)
  File "/h2ogpt_conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/h2ogpt_conda/lib/python3.10/site-packages/transformers/generation/utils.py", line 1718, in generate
    return self.greedy_search(
  File "/h2ogpt_conda/lib/python3.10/site-packages/transformers/generation/utils.py", line 2579, in greedy_search
    outputs = self(
  File "/h2ogpt_conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/h2ogpt_conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/h2ogpt_conda/lib/python3.10/site-packages/transformers/models/mixtral/modeling_mixtral.py", line 1213, in forward
    outputs = self.model(
  File "/h2ogpt_conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/h2ogpt_conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/h2ogpt_conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/h2ogpt_conda/lib/python3.10/site-packages/awq/modules/fused/model.py", line 35, in forward
    h = self.embedding(input_ids)
  File "/h2ogpt_conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/h2ogpt_conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/h2ogpt_conda/lib/python3.10/site-packages/torch/nn/modules/sparse.py", line 162, in forward
    return F.embedding(
  File "/h2ogpt_conda/lib/python3.10/site-packages/torch/nn/functional.py", line 2233, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument index in method wrapper_CUDA__index_select)`

So want to know apart GGUF if there are other strategies to lower the VRAM usage during RAG, or to make work AWQ/GPTQ if these can offer further optimization respect using the internal library for quantization.

**Comment by pseudotensor** [comment]
I think the quantizations GGUF, GPTQ, AWQ aren't fully good for mixtral.  GGUF gets too slow for context >4096, AWQ totally doesn't work in vLLM, etc.

**Comment by davide445** [comment]
Looking at some tests seems AWQ can be faster than GPTQ but is using more VRAM, and the used VRAM is my problem.
Any suggestion where the second error is coming out.

**Comment by davide445** [comment]
GPTQ can be loaded without errors using your solution in this issue

https://github.com/h2oai/h2ogpt/issues/1216

Still got the out of memory error trying using the RAG

**Comment by davide445** [comment]
With GGUF I was able to make it work. Is loading Q5 K - Medium and offloading all the layers on the GPU using 37GB, but at inference didn't use more VRAM so I'm able to use also the RAG on my documents.

**Comment by pseudotensor** [comment]
@davide445 Ok, just I saw >4096 fail before.  I updated llama cpp python recently that has newer llama.cpp and it may not be buggy anymore, need to check.

**Comment by pseudotensor** [comment]
Ya, GGUF even with latest stuff is still very slow even for 4k context even with latest 0.2.26.

**Comment by davide445** [comment]
I never wrote GGUF is slow, on my setup is a bit slower than GPTQ but anyway like 2-3 words in a second, enough to didn't stay waiting too much.
