### ISSUE TITLE
using my local codellama 34 intruct get Open API Key Errror

### ISSUE THREAD

**Issue by Rotoslider** [h2oai/h2ogpt#1282]
fresh install of h2oGPT. Using local LLM. Loaded 7 pdfs in MyDocs Collection 4608 chunks. Tried several prompt types. Same error. 
`error
1 validation error for OpenAI __root__ Did not find openai_api_key, please add an environment variable `OPENAI_API_KEY` which contains it, or pass `openai_api_key` as a named parameter. (type=value_error)`

I m not using openai. this is a local LLM. I ran the Nov version of the installer with no issues.

**Comment by pseudotensor** [comment]
Hi, do you have a more complete stack trace, so I can see the origin?

If you are using latest windows installer, I'm not sure what would cause this.  When testing it I had no issues.

**Comment by pseudotensor** [comment]
I tried various things to repro, like unset the key myself or add `os.environ.pop('OPENAI_API_KEY', None)` early in the python code, but nothing fails for me with GGUF model.

**Comment by pseudotensor** [comment]
I also tried inference_server as vLLM with that env popped out, and still no issue for document QA or direct LLM.

**Comment by Rotoslider** [comment]
Not sure why but it is no longer producing the error. I clicked on a model in the list and once finally downloaded it ran without issue. then I used one of my local models i downloaded again after the folder mishap and it loaded without error. I then downloaded another one and tried that after a reboot and it worked also without error.
I assume that the api key error may only happen at first install if one has not used a model on the list first or maybe it only happens on a clean install. 
There are a few warnings and issues listed in the terminal but they do not prevent it from running.
[issues.txt](https://github.com/h2oai/h2ogpt/files/13928284/issues.txt)

**Comment by pseudotensor** [comment]
Ok if you see again, please run the full debug mode to get stack trace to see where it was coming from.  I'll close for now.

**Comment by micsthepick** [comment]
@pseudotensor I think I've replicated it acciedentally: [https://logpaste.com/rbrxhMtH](full stack).

**Comment by pseudotensor** [comment]
```
evaluate_nochat exception: 1 validation error for OpenAI
__root__
  Did not find openai_api_key, please add an environment variable `OPENAI_API_KEY` which contains it, or pass `openai_api_key` as a named parameter. (type=value_error): ('', '', '', True, 'p
lain', "{   'PreInput': None,\n    'PreInstruct': None,\n    'PreResponse': None,\n    'botstr': None,\n    'can_handle_system_prompt': False,\n    'chat_sep': '',\n    'chat_turn_sep': '',\
n    'generates_leading_space': False,\n    'humanstr': None,\n    'promptA': None,\n    'promptB': None,\n    'system_prompt': '',\n    'terminate_response': []}", 0.1, 0.75, 40, 0, 1, 1024
, 0, False, 600, 1.07, 1, False, True, '', '', 'UserData', True, 'Query', ['Collection'], 10, True, 512, 'Relevant', ['All'], [], [], [], [], 'Pay attention and remember the information belo
w, which will help to answer the question or imperative after the context ends.', 'According to only the information in the document sources provided within the context above, write an insig
htful and well-structured response to: ', 'In order to write a concise single-paragraph or bulleted list summary, pay attention to the following text.', 'Using only the information in the do
cument sources above, write a condensed and concise summary of key results (preferably as bullet points).', 'Answer this question with vibrant details in order for some NLP embedding model t
o use that answer as better query than original question: ', 'You are an expert document question-answer language model named GPT-4 Turbo created by OpenAI.  You will get a tip of $200 when 
you answer correctly the questions and only use the document context given.  I may lose my job if your answers are inaccurate or do a poor job of using the documents in the context.', ['DocT
R', 'Caption', 'ASR'], ['PyPDF'], ['Unstructured'], '.[]', 10, 'auto', [], '', False, '[]', '[]', 'reverse_ucurve_sort', 512, -1.0, -1.0, 'split_or_merge', '\n\n', 0, 'auto', False, False, '
None', 'None', [], 1.0, {'model': 'model', 'tokenizer': 'tokenizer', 'device': 'cuda', 'base_model': '/media/mike/Elements/LLModels/models/models--TheBloke--Nous-Hermes-13B-GPTQ', 'tokenizer
_base_model': '', 'lora_weights': '[None/Remove]', 'inference_server': '[None/Remove]', 'prompt_type': 'plain', 'prompt_dict': {'promptA': None, 'promptB': None, 'PreInstruct': None, 'PreInp
ut': None, 'PreResponse': None, 'terminate_response': [], 'chat_sep': '', 'chat_turn_sep': '', 'humanstr': None, 'botstr': None, 'generates_leading_space': False, 'system_prompt': '', 'can_h
andle_system_prompt': False}, 'visible_models': 0, 'h2ogpt_key': None}, {'MyData': [None, 'd2a76a4d-57c3-4c82-a057-8b267c091f22', 'mike']}, {'langchain_modes': ['UserData', 'MyData', 'LLM', 
'Disabled'], 'langchain_mode_paths': {'UserData': None}, 'langchain_mode_types': {'UserData': 'shared', 'github h2oGPT': 'shared', 'DriverlessAI docs': 'shared', 'wiki': 'shared', 'wiki_full
': '', 'MyData': 'personal', 'LLM': 'either', 'Disabled': 'either'}}, {'headers': '', 'host': 'localhost:7860', 'username': 'mike', 'connection': 'Upgrade', 'pragma': 'no-cache', 'cache-cont
rol': 'no-cache', 'upgrade': 'websocket', 'origin': 'http://localhost:7860', 'sec-websocket-version': '13', 'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gec
ko) Chrome/120.0.0.0 Safari/537.36', 'accept-encoding': 'gzip, deflate, br', 'accept-language': 'en-AU,en-GB;q=0.9,en-US;q=0.8,en;q=0.7', 'cookie': 'username-localhost-8888=REDACTED:username-localhost-8888|188:REDACTED; _xsrf=REDACTED', 'sec-gpc': '1', 'sec-websock
et-key': 'REDACTED', 'sec-websocket-extensions': 'permessage-deflate; client_max_window_bits', 'host2': '127.0.0.1'}, {}, [['hello', ''], ['hi', '']])
Traceback (most recent call last):
  File "/home/mike/miniconda3/envs/h2oGPT/lib/python3.10/site-packages/gradio/queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
  File "/home/mike/miniconda3/envs/h2oGPT/lib/python3.10/site-packages/gradio/route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/mike/miniconda3/envs/h2oGPT/lib/python3.10/site-packages/gradio/blocks.py", line 1550, in process_api
    result = await self.call_function(
  File "/home/mike/miniconda3/envs/h2oGPT/lib/python3.10/site-packages/gradio/blocks.py", line 1199, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/home/mike/miniconda3/envs/h2oGPT/lib/python3.10/site-packages/gradio/utils.py", line 519, in async_iteration
    return await iterator.__anext__()
  File "/home/mike/miniconda3/envs/h2oGPT/lib/python3.10/site-packages/gradio/utils.py", line 512, in __anext__
    return await anyio.to_thread.run_sync(
  File "/home/mike/miniconda3/envs/h2oGPT/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/mike/miniconda3/envs/h2oGPT/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/mike/miniconda3/envs/h2oGPT/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/mike/miniconda3/envs/h2oGPT/lib/python3.10/site-packages/gradio/utils.py", line 495, in run_sync_iterator_async
    return next(iterator)
  File "/home/mike/miniconda3/envs/h2oGPT/lib/python3.10/site-packages/gradio/utils.py", line 649, in gen_wrapper
    yield from f(*args, **kwargs)
  File "/home/mike/source/repos/h2ogpt/src/gradio_runner.py", line 4397, in bot
    for res in get_response(fun1, history, chatbot_role1, speaker1, tts_language1, roles_state1,
  File "/home/mike/source/repos/h2ogpt/src/gradio_runner.py", line 4293, in get_response
    for output_fun in fun1():
  File "/home/mike/source/repos/h2ogpt/src/gen.py", line 3702, in evaluate
    for r in run_qa_db(
  File "/home/mike/source/repos/h2ogpt/src/gpt_langchain.py", line 5104, in _run_qa_db
    get_chain(**sim_kwargs)
  File "/home/mike/source/repos/h2ogpt/src/gpt_langchain.py", line 6040, in get_chain
    toolkit = VectorStoreToolkit(vectorstore_info=vectorstore_info)
  File "/home/mike/miniconda3/envs/h2oGPT/lib/python3.10/site-packages/pydantic/v1/main.py", line 339, in __init__
    values, fields_set, validation_error = validate_model(__pydantic_self__.__class__, data)
  File "/home/mike/miniconda3/envs/h2oGPT/lib/python3.10/site-packages/pydantic/v1/main.py", line 1066, in validate_model
    value = field.get_default()
  File "/home/mike/miniconda3/envs/h2oGPT/lib/python3.10/site-packages/pydantic/v1/fields.py", line 439, in get_default
    return smart_deepcopy(self.default) if self.default_factory is None else self.default_factory()
  File "/home/mike/miniconda3/envs/h2oGPT/lib/python3.10/site-packages/langchain/agents/agent_toolkits/vectorstore/toolkit.py", line 34, in <lambda>
    llm: BaseLanguageModel = Field(default_factory=lambda: OpenAI(temperature=0))
  File "/home/mike/miniconda3/envs/h2oGPT/lib/python3.10/site-packages/langchain_core/load/serializable.py", line 107, in __init__
    super().__init__(**kwargs)
  File "/home/mike/miniconda3/envs/h2oGPT/lib/python3.10/site-packages/pydantic/v1/main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 1 validation error for OpenAI
__root__
  Did not find openai_api_key, please add an environment variable `OPENAI_API_KEY` which contains it, or pass `openai_api_key` as a named parameter. (type=value_error)
```

This implies you chose the "collection" agent.  This is a bug in langchain.  I'll file issue for them, thanks.
