### ISSUE TITLE
Trying to convert BFloat16 to the MPS backend but it does not have support for that dtype

### ISSUE THREAD

**Issue by kamrancr7** [h2oai/h2ogpt#1362]
while running following command i'm getting the error:

```
kamranali@Kamrans-MacBook-Pro h2o % sudo python3 generate.py --base_model=openchat/openchat-3.5-1210 --hf_embedding_model=sentence-transformers/all-MiniLM-L6-v2 --score_model=None --load_4bit=True --langchain_mode='UserData' --enable_tts=False --enable_stt=False --enable_transcriptions=False --max_seq_len=2048
Password:
Using Model openchat/openchat-3.5-1210
Must install DocTR and LangChain installed if enabled DocTR, disabling
Starting get_model: openchat/openchat-3.5-1210 
Overriding max_seq_len -> 2048
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Overriding max_seq_len -> 2048
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Overriding max_seq_len -> 2048
Starting get_model: openchat/openchat-3.5-1210 
Overriding max_seq_len -> 2048
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Overriding max_seq_len -> 2048
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Overriding max_seq_len -> 2048
Loading checkpoint shards:   0%|                                                                                             | 0/3 [00:18<?, ?it/s]
Starting get_model: openchat/openchat-3.5-1210 
Overriding max_seq_len -> 2048
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Overriding max_seq_len -> 2048
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Overriding max_seq_len -> 2048
Loading checkpoint shards:   0%|                                                                                             | 0/3 [01:38<?, ?it/s]
Starting get_model: openchat/openchat-3.5-1210 
Overriding max_seq_len -> 2048
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Overriding max_seq_len -> 2048
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Overriding max_seq_len -> 2048
Loading checkpoint shards:   0%|                                                                                             | 0/3 [01:56<?, ?it/s]
Traceback (most recent call last):
  File "/Users/kamranali/Development/ML_Project/h2o/generate.py", line 16, in <module>
    entrypoint_main()
  File "/Users/kamranali/Development/ML_Project/h2o/generate.py", line 12, in entrypoint_main
    H2O_Fire(main)
  File "/Users/kamranali/Development/ML_Project/h2o/src/utils.py", line 65, in H2O_Fire
    fire.Fire(component=component, command=args)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kamranali/Development/ML_Project/h2o/src/gen.py", line 2023, in main
    model0, tokenizer0, device = get_model_retry(reward_type=False,
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kamranali/Development/ML_Project/h2o/src/gen.py", line 2351, in get_model_retry
    model1, tokenizer1, device1 = get_model(**kwargs)
                                  ^^^^^^^^^^^^^^^^^^^
  File "/Users/kamranali/Development/ML_Project/h2o/src/gen.py", line 2775, in get_model
    return get_hf_model(load_8bit=load_8bit,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kamranali/Development/ML_Project/h2o/src/gen.py", line 3011, in get_hf_model
    model = model_loader(
            ^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 566, in from_pretrained
    return model_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/transformers/modeling_utils.py", line 3850, in from_pretrained
    ) = cls._load_pretrained_model(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/transformers/modeling_utils.py", line 4284, in _load_pretrained_model
    new_error_msgs, offload_index, state_dict_index = _load_state_dict_into_meta_model(
                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/transformers/modeling_utils.py", line 765, in _load_state_dict_into_meta_model
    param = param.to(dtype)
            ^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/utils/_device.py", line 78, in __torch_function__
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
TypeError: Trying to convert BFloat16 to the MPS backend but it does not have support for that dtype.
```

**Comment by pseudotensor** [comment]
I think it's because that model requires bfloat16 unless one specifies `--load_half=True` but I'm not sure as I don't have an M1/M2 to test.

@Mathanraj-Sharma

**Comment by Mathanraj-Sharma** [comment]
@pseudotensor specifying `--load_half=True` didn't help. 

@kamrancr7 please refer to #1442 for workaround
