### ISSUE TITLE
gpt4all: Request failed: HTTP 404 Not Found (type=value_error)

### ISSUE THREAD

**Issue by alllexx88** [h2oai/h2ogpt#1379]
Hi, whenever I try to load a gpt4all model, I get an error, e.g., with an example from https://github.com/h2oai/h2ogpt/blob/main/docs/README_CPU.md

```
$ python generate.py --base_model=gpt4all_llama --model_name_gpt4all_llama=ggml-wizardLM-7B.q4_2.bin --score_model=None --langchain_mode='UserData' --user_path=user_path
soundfile, librosa, and wavio not installed, disabling STT
soundfile, librosa, and wavio not installed, disabling TTS
Using Model gpt4all_llama
load INSTRUCTOR_Transformer
max_seq_length  512
Must install DocTR and LangChain installed if enabled DocTR, disabling
0it [00:00, ?it/s]huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 18/18 [00:02<00:00,  7.11it/s]
Loaded 18 new files as sources to add to UserData
Existing db, potentially adding 2878 sources from user_path=user_path
Found 0 new sources (0 have no hash in original source, so have to reprocess for migration to sources with hash)
Removing 0 duplicate files from db because ingesting those as new documents
Existing db, added 0 new sources from user_path=user_path
Starting get_model: gpt4all_llama 
Starting get_model: gpt4all_llama 
Starting get_model: gpt4all_llama 
Starting get_model: gpt4all_llama 
Traceback (most recent call last):
  File "/home/alex/Documents/doc_search_kb/h2ogpt/generate.py", line 16, in <module>
    entrypoint_main()
  File "/home/alex/Documents/doc_search_kb/h2ogpt/generate.py", line 12, in entrypoint_main
    H2O_Fire(main)
  File "/home/alex/Documents/doc_search_kb/h2ogpt/src/utils.py", line 65, in H2O_Fire
    fire.Fire(component=component, command=args)
  File "/home/alex/Documents/doc_search_kb/venv/lib/python3.11/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/Documents/doc_search_kb/venv/lib/python3.11/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/Documents/doc_search_kb/venv/lib/python3.11/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/Documents/doc_search_kb/h2ogpt/src/gen.py", line 1977, in main
    model0, tokenizer0, device = get_model_retry(reward_type=False,
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/Documents/doc_search_kb/h2ogpt/src/gen.py", line 2305, in get_model_retry
    model1, tokenizer1, device1 = get_model(**kwargs)
                                  ^^^^^^^^^^^^^^^^^^^
  File "/home/alex/Documents/doc_search_kb/h2ogpt/src/gen.py", line 2717, in get_model
    model, tokenizer, device = get_model_tokenizer_gpt4all(base_model,
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/Documents/doc_search_kb/h2ogpt/src/gpt4all_llm.py", line 30, in get_model_tokenizer_gpt4all
    model, tokenizer, redo, max_seq_len = get_llm_gpt4all(**llama_kwargs)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/Documents/doc_search_kb/h2ogpt/src/gpt4all_llm.py", line 217, in get_llm_gpt4all
    llm = cls(**model_kwargs)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/alex/Documents/doc_search_kb/venv/lib/python3.11/site-packages/langchain_core/load/serializable.py", line 107, in __init__
    super().__init__(**kwargs)
  File "/home/alex/Documents/doc_search_kb/venv/lib/python3.11/site-packages/pydantic/v1/main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 1 validation error for H2OGPT4All
__root__
  Request failed: HTTP 404 Not Found (type=value_error)
```

Even if I download the model manually from https://gpt4all.io/models/ggml-wizardLM-7B.q4_2.bin
```bash
$ ls -lh llamacpp_path/ggml-wizardLM-7B.q4_2.bin
-rw-r--r-- 1 alex alex 4.0G Feb  7 16:16 llamacpp_path/ggml-wizardLM-7B.q4_2.bin
```

Thanks

**Comment by pseudotensor** [comment]
I don't recommend gpt4all models, I haven't tried to maintain them and I think they typically don't work on GPU and are CPU only.  In any case I recommend llama.cpp models, i.e. GGUF.

I didn't design h2oGPT to accept urls for gpt4all models.  The version I use automatically downloads models by name as described in the h2oGPT docs. https://github.com/h2oai/h2ogpt/blob/main/docs/FAQ.md#gpt4all

However, I can run your exactly command fine.  Just takes a while since runs on CPU.

```
python generate.py --base_model=gpt4all_llama --model_name_gpt4all_llama=ggml-wizardLM-7B.q4_2.bin --score_model=None --langchain_mode='UserData' --user_path=user_path
```

Basic case:

![image](https://github.com/h2oai/h2ogpt/assets/2249614/ffc55603-472c-4c05-b980-9bf1a5c2763c)


Uploaded doc and then asked question, but it takes WAY too long to be useful.

![image](https://github.com/h2oai/h2ogpt/assets/2249614/9d30a23b-a599-4c78-aa9f-09e56fcb500a)


Note that gpt4all models do not go to llamacpp_path, that's only for llama.cpp models.  gpt4all models to to their own ~
/.cache location automatically.

However, I think you can provide the full absolute path and it'll work.

**Comment by pseudotensor** [comment]
It's also possible they changed what models are available.  In any case, I don't plan to maintain the gpt4all models, but happy if someone helps you or provides any solutions.

**Comment by alllexx88** [comment]
@pseudotensor Thank you for your reply! I don't know why the command doesn't work for me, but I'll stick to GGUF then :smiley:
