### ISSUE TITLE
Cannot launch after windows installer running: requests.exceptions.ConnectionError

### ISSUE THREAD

**Issue by dustinjoe** [h2oai/h2ogpt#1393]
Hello. Thanks for your time and work!
I am running into issue using the Windows installer.
May plan to switch to gpu mode later but want to have a try on cpu first. But running into errors below:

Traceback (most recent call last):
  File "D:\LLMs\h2ogpt\h2ogpt\pkgs\urllib3\connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "D:\LLMs\h2ogpt\h2ogpt\pkgs\urllib3\connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "D:\LLMs\h2ogpt\h2ogpt\pkgs\urllib3\connectionpool.py", line 1058, in _validate_conn
    conn.connect()
  File "D:\LLMs\h2ogpt\h2ogpt\pkgs\urllib3\connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "D:\LLMs\h2ogpt\h2ogpt\pkgs\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "D:\LLMs\h2ogpt\h2ogpt\pkgs\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "ssl.py", line 512, in wrap_socket
  File "ssl.py", line 1070, in _create
  File "ssl.py", line 1341, in do_handshake
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\LLMs\h2ogpt\h2ogpt\pkgs\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "D:\LLMs\h2ogpt\h2ogpt\pkgs\urllib3\connectionpool.py", line 799, in urlopen
    retries = retries.increment(
  File "D:\LLMs\h2ogpt\h2ogpt\pkgs\urllib3\util\retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "D:\LLMs\h2ogpt\h2ogpt\pkgs\urllib3\packages\six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "D:\LLMs\h2ogpt\h2ogpt\pkgs\urllib3\connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "D:\LLMs\h2ogpt\h2ogpt\pkgs\urllib3\connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "D:\LLMs\h2ogpt\h2ogpt\pkgs\urllib3\connectionpool.py", line 1058, in _validate_conn
    conn.connect()
  File "D:\LLMs\h2ogpt\h2ogpt\pkgs\urllib3\connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "D:\LLMs\h2ogpt\h2ogpt\pkgs\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "D:\LLMs\h2ogpt\h2ogpt\pkgs\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "ssl.py", line 512, in wrap_socket
  File "ssl.py", line 1070, in _create
  File "ssl.py", line 1341, in do_handshake
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\LLMs\h2ogpt\h2ogpt\pkgs\win_run_app.py", line 150, in main
    _main()
  File "D:\LLMs\h2ogpt\h2ogpt\pkgs\win_run_app.py", line 136, in _main
    main_h2ogpt()
  File "D:\LLMs\h2ogpt\h2ogpt\generate.py", line 12, in entrypoint_main
    H2O_Fire(main)
  File "D:\LLMs\h2ogpt\h2ogpt\src\utils.py", line 65, in H2O_Fire
    fire.Fire(component=component, command=args)
  File "D:\LLMs\h2ogpt\h2ogpt\pkgs\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "D:\LLMs\h2ogpt\h2ogpt\pkgs\fire\core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "D:\LLMs\h2ogpt\h2ogpt\pkgs\fire\core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "D:\LLMs\h2ogpt\h2ogpt\src\gen.py", line 1664, in main
    model=get_embedding(use_openai_embedding, hf_embedding_model=hf_embedding_model,
  File "D:\LLMs\h2ogpt\h2ogpt\src\gpt_langchain.py", line 461, in get_embedding
    embedding = HuggingFaceEmbeddings(model_name=hf_embedding_model, model_kwargs=model_kwargs)
  File "D:\LLMs\h2ogpt\h2ogpt\pkgs\langchain_community\embeddings\huggingface.py", line 65, in __init__
    self.client = sentence_transformers.SentenceTransformer(
  File "D:\LLMs\h2ogpt\h2ogpt\pkgs\sentence_transformers\SentenceTransformer.py", line 87, in __init__
    snapshot_download(model_name_or_path,
  File "D:\LLMs\h2ogpt\h2ogpt\pkgs\sentence_transformers\util.py", line 442, in snapshot_download
    model_info = _api.model_info(repo_id=repo_id, revision=revision, token=token)
  File "D:\LLMs\h2ogpt\h2ogpt\pkgs\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "D:\LLMs\h2ogpt\h2ogpt\pkgs\huggingface_hub\hf_api.py", line 1921, in model_info
    r = get_session().get(path, headers=headers, timeout=timeout, params=params)
  File "D:\LLMs\h2ogpt\h2ogpt\pkgs\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "D:\LLMs\h2ogpt\h2ogpt\pkgs\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\LLMs\h2ogpt\h2ogpt\pkgs\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "D:\LLMs\h2ogpt\h2ogpt\pkgs\huggingface_hub\utils\_http.py", line 63, in send
    return super().send(request, *args, **kwargs)
  File "D:\LLMs\h2ogpt\h2ogpt\pkgs\requests\adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: (ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)), '(Request ID: 292a9858-baea-4407-879b-b8d560168fb7)')

Seems to be some connection and ssl related issue but do not know the solution on this. Any suggestions on this? thanks

**Comment by pseudotensor** [comment]
Looks like some kind of firewall issue or SSL issue.  It's trying to reach huggingface and cannot.

If you are trying to run offline, need to follow one of the offline methods: https://github.com/h2oai/h2ogpt/blob/main/docs/README_offline.md
