### ISSUE TITLE
Default install fails starting webserver

### ISSUE THREAD

**Issue by markg85** [h2oai/h2ogpt#1426]
Hi,

I'm running it with `python generate.py --base_model=microsoft/phi-2 --prompt_type=zephyr --max_seq_len=4096`

But this fails with the following error:
```
Running on local URL:  http://0.0.0.0:7860
Traceback (most recent call last):
  File "/home/mark/.conda/envs/h2ogpt/lib/python3.10/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/home/mark/.conda/envs/h2ogpt/lib/python3.10/site-packages/httpcore/_backends/sync.py", line 100, in connect_tcp
    sock = socket.create_connection(
  File "/home/mark/.conda/envs/h2ogpt/lib/python3.10/socket.py", line 824, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/home/mark/.conda/envs/h2ogpt/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mark/.conda/envs/h2ogpt/lib/python3.10/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/home/mark/.conda/envs/h2ogpt/lib/python3.10/site-packages/httpx/_transports/default.py", line 218, in handle_request
    resp = self._pool.handle_request(req)
  File "/home/mark/.conda/envs/h2ogpt/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 262, in handle_request
    raise exc
  File "/home/mark/.conda/envs/h2ogpt/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 245, in handle_request
    response = connection.handle_request(request)
  File "/home/mark/.conda/envs/h2ogpt/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 92, in handle_request
    raise exc
  File "/home/mark/.conda/envs/h2ogpt/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 69, in handle_request
    stream = self._connect(request)
  File "/home/mark/.conda/envs/h2ogpt/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 117, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
  File "/home/mark/.conda/envs/h2ogpt/lib/python3.10/site-packages/httpcore/_backends/sync.py", line 99, in connect_tcp
    with map_exceptions(exc_map):
  File "/home/mark/.conda/envs/h2ogpt/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/mark/.conda/envs/h2ogpt/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno -2] Name or service not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mark/GitProjects/h2ogpt/generate.py", line 20, in <module>
    entrypoint_main()
  File "/home/mark/GitProjects/h2ogpt/generate.py", line 16, in entrypoint_main
    H2O_Fire(main)
  File "/home/mark/GitProjects/h2ogpt/src/utils.py", line 69, in H2O_Fire
    fire.Fire(component=component, command=args)
  File "/home/mark/.conda/envs/h2ogpt/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/mark/.conda/envs/h2ogpt/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/mark/.conda/envs/h2ogpt/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/mark/GitProjects/h2ogpt/src/gen.py", line 2182, in main
    go_gradio(**locals())
  File "/home/mark/GitProjects/h2ogpt/src/gradio_runner.py", line 6114, in go_gradio
    demo.launch(share=kwargs['share'],
  File "/home/mark/.conda/envs/h2ogpt/lib/python3.10/site-packages/gradio/blocks.py", line 2020, in launch
    httpx.get(f"{self.local_url}startup-events", verify=ssl_verify)
  File "/home/mark/.conda/envs/h2ogpt/lib/python3.10/site-packages/httpx/_api.py", line 189, in get
    return request(
  File "/home/mark/.conda/envs/h2ogpt/lib/python3.10/site-packages/httpx/_api.py", line 100, in request
    return client.request(
  File "/home/mark/.conda/envs/h2ogpt/lib/python3.10/site-packages/httpx/_client.py", line 814, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/home/mark/.conda/envs/h2ogpt/lib/python3.10/site-packages/httpx/_client.py", line 901, in send
    response = self._send_handling_auth(
  File "/home/mark/.conda/envs/h2ogpt/lib/python3.10/site-packages/httpx/_client.py", line 929, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/home/mark/.conda/envs/h2ogpt/lib/python3.10/site-packages/httpx/_client.py", line 966, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/home/mark/.conda/envs/h2ogpt/lib/python3.10/site-packages/httpx/_client.py", line 1002, in _send_single_request
    response = transport.handle_request(request)
  File "/home/mark/.conda/envs/h2ogpt/lib/python3.10/site-packages/httpx/_transports/default.py", line 217, in handle_request
    with map_httpcore_exceptions():
  File "/home/mark/.conda/envs/h2ogpt/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/mark/.conda/envs/h2ogpt/lib/python3.10/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno -2] Name or service not known
```

I verified it, nothing uses port 7860.

What i'm guessing is that "0.0.0.0" is being pulled through name resolving which fails because it's already an ip. But that's just a hunch.

**Comment by pseudotensor** [comment]
I haven't seen that before for linux.  Can you try instead:

```
python generate.py --base_model=microsoft/phi-2 --prompt_type=zephyr --max_seq_len=4096 --server_name=127.0.0.1
```

or some other variant like localhost?

**Comment by markg85** [comment]
That works.

I already made it work before your suggestion by removing this line: `server_name=kwargs['server_name']` from gradio_runner.py. That's obviously wrong to remove ;) But it's hinting at whatever the default value is for `server_name` isn't correct.

**Comment by markg85** [comment]
So this is completely on me. My hosts file was empty and was missing the localhost to 127.0.0.1 mapping. Not sure how that happened. Fixing that also fixed my issue. Sorry for the noise!
