### ISSUE TITLE
AsserionError on HYDE 2

### ISSUE THREAD

**Issue by slavag** [h2oai/h2ogpt#1435]
Hi,
Trying to question and getting that error during "Computing HYDE 1/2 response" :
```
Traceback (most recent call last):
  File "/mnt/AI/miniconda3/envs/python311/lib/python3.11/site-packages/gradio/queueing.py", line 495, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/AI/miniconda3/envs/python311/lib/python3.11/site-packages/gradio/route_utils.py", line 233, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/AI/miniconda3/envs/python311/lib/python3.11/site-packages/gradio/blocks.py", line 1608, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/AI/miniconda3/envs/python311/lib/python3.11/site-packages/gradio/blocks.py", line 1188, in call_function
    prediction = await utils.async_iteration(iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/AI/miniconda3/envs/python311/lib/python3.11/site-packages/gradio/utils.py", line 525, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/AI/miniconda3/envs/python311/lib/python3.11/site-packages/gradio/utils.py", line 518, in __anext__
    return await anyio.to_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/AI/miniconda3/envs/python311/lib/python3.11/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/AI/miniconda3/envs/python311/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/mnt/AI/miniconda3/envs/python311/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/AI/miniconda3/envs/python311/lib/python3.11/site-packages/gradio/utils.py", line 501, in run_sync_iterator_async
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "/mnt/AI/miniconda3/envs/python311/lib/python3.11/site-packages/gradio/utils.py", line 684, in gen_wrapper
    response = next(iterator)
               ^^^^^^^^^^^^^^
  File "/mnt/AI/h2ogpt/src/gradio_runner.py", line 4520, in bot
    for res in get_response(fun1, history, chatbot_role1, speaker1, tts_language1, roles_state1,
  File "/mnt/AI/h2ogpt/src/gradio_runner.py", line 4415, in get_response
    for output_fun in fun1():
  File "/mnt/AI/h2ogpt/src/gen.py", line 3901, in evaluate
    for r in run_qa_db(
  File "/mnt/AI/h2ogpt/src/gpt_langchain.py", line 5499, in _run_qa_db
    query_embedding, llm_answers = yield from run_hyde(**locals())
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/AI/h2ogpt/src/gpt_langchain.py", line 6016, in run_hyde
    for ret in run_target_func(query=query,
  File "/mnt/AI/h2ogpt/src/gpt_langchain.py", line 5729, in run_target
    raise thread.exc
  File "/mnt/AI/h2ogpt/src/utils.py", line 476, in run
    self._return = self._target(*self._args, **self._kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/AI/miniconda3/envs/python311/lib/python3.11/site-packages/langchain/chains/base.py", line 316, in __call__
    raise e
  File "/mnt/AI/miniconda3/envs/python311/lib/python3.11/site-packages/langchain/chains/base.py", line 310, in __call__
    self._call(inputs, run_manager=run_manager)
  File "/mnt/AI/miniconda3/envs/python311/lib/python3.11/site-packages/langchain/chains/combine_documents/base.py", line 136, in _call
    output, extra_return_dict = self.combine_docs(
                                ^^^^^^^^^^^^^^^^^^
  File "/mnt/AI/miniconda3/envs/python311/lib/python3.11/site-packages/langchain/chains/combine_documents/stuff.py", line 244, in combine_docs
    return self.llm_chain.predict(callbacks=callbacks, **inputs), {}
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/AI/miniconda3/envs/python311/lib/python3.11/site-packages/langchain/chains/llm.py", line 293, in predict
    return self(kwargs, callbacks=callbacks)[self.output_key]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/AI/miniconda3/envs/python311/lib/python3.11/site-packages/langchain/chains/base.py", line 316, in __call__
    raise e
  File "/mnt/AI/miniconda3/envs/python311/lib/python3.11/site-packages/langchain/chains/base.py", line 310, in __call__
    self._call(inputs, run_manager=run_manager)
  File "/mnt/AI/miniconda3/envs/python311/lib/python3.11/site-packages/langchain/chains/llm.py", line 103, in _call
    response = self.generate([inputs], run_manager=run_manager)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/AI/miniconda3/envs/python311/lib/python3.11/site-packages/langchain/chains/llm.py", line 115, in generate
    return self.llm.generate_prompt(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/AI/miniconda3/envs/python311/lib/python3.11/site-packages/langchain_core/language_models/llms.py", line 521, in generate_prompt
    return self.generate(prompt_strings, stop=stop, callbacks=callbacks, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/AI/miniconda3/envs/python311/lib/python3.11/site-packages/langchain_core/language_models/llms.py", line 671, in generate
    output = self._generate_helper(
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/AI/miniconda3/envs/python311/lib/python3.11/site-packages/langchain_core/language_models/llms.py", line 558, in _generate_helper
    raise e
  File "/mnt/AI/miniconda3/envs/python311/lib/python3.11/site-packages/langchain_core/language_models/llms.py", line 545, in _generate_helper
    self._generate(
  File "/mnt/AI/miniconda3/envs/python311/lib/python3.11/site-packages/langchain_core/language_models/llms.py", line 1079, in _generate
    self._call(prompt, stop=stop, run_manager=run_manager, **kwargs)
  File "/mnt/AI/h2ogpt/src/gpt4all_llm.py", line 422, in _call
    for token in self.stream(input=prompt, stop=stop):
  File "/mnt/AI/miniconda3/envs/python311/lib/python3.11/site-packages/langchain_core/language_models/llms.py", line 405, in stream
    raise e
  File "/mnt/AI/miniconda3/envs/python311/lib/python3.11/site-packages/langchain_core/language_models/llms.py", line 397, in stream
    assert generation is not None
           ^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```
Please advise what could be an issue here ?
Thanks

**Comment by pseudotensor** [comment]
I don't see it generically occur.  That includes GGUF that you seemed to use.

![image](https://github.com/h2oai/h2ogpt/assets/2249614/eb1f96b7-7929-4b81-ade5-1f91c1a67c8e)

![image](https://github.com/h2oai/h2ogpt/assets/2249614/ba4dc1bb-4b49-415f-9138-03991b84291f)

**Comment by pseudotensor** [comment]
A random guess is that the model failed to be loaded or went out of memory.

**Comment by slavag** [comment]
@pseudotensor Thanks, from the logs I see that model is fine, there's answers (at least partially) from the model. Any idea how can I tackle it ?

**Comment by pseudotensor** [comment]
Can you give your run line details?  At least model so I can try to reproduce?

Also, are you using concurrency_limit > 1?  That won't work for llama.cpp as it is not thread safe.

https://github.com/ggerganov/llama.cpp/discussions/499

**Comment by slavag** [comment]
@pseudotensor this is the run line  python generate.py --base_model=llama --prompt_type=llama2 --score_model=None --langchain_modes="['MyData', 'ZenDeskTicketsWithDocs-gte-base','LLM']" --langchain_mode_types="{'ZenDeskTicketsWithDocs-gte-base':'shared'}" --chunk_size=256 --top_k_docs=3 --h2ocolors=False --model_path_llama=/mnt/AI/models/TheBloke/Mistral-7B-Instruct-v0.1-GGUF/mistral-7b-instruct-v0.1.Q6_K.gguf --max_seq_len=32768 --verbose=True

Tried to change different parameters, and seems that when I change number of documents to be -1 or > 15 it's failing. 
I'm not changing concurrency_limit parameter at all.

Thanks

**Comment by pseudotensor** [comment]
Was going to check but huggingface is offline.

**Comment by pseudotensor** [comment]
Also, why do you use v0.1, why not v0.2 for mistral 7b?

I had this v0.2 locally:
```
(h2ogpt) jon@gpu:~/h2ogpt$ python generate.py --prompt_type=llama2 --score_model=None --langchain_modes="['MyData', 'ZenDeskTicketsWithDocs-gte-base','LLM']" --langchain_mode_types="{'ZenDeskTicketsWithDocs-gte-base':'shared'}" --chunk_size=256 --top_k_docs=3 --h2ocolors=False --base_model=llama --model_path_llama=llamacpp_path/mistral-7b-instruct-v0.2.Q5_K_M.gguf --max_seq_len=32768 --verbose=True
```

Also, you said you see more often then -1 or > 15 chunks. 

Update: ok you said works for 8k.  I think makes sense.  Still good to use v0.2. 

You can try changing the GPU offloading to lower use of GPU in case GPU memory is issue.  Will be slower, but hard to say by how much, depends upon alot.

i.e. adding:
```
--llamacpp_dict="{'n_gpu_layers':15,'n_batch':128}"
```

try playing with llama.cpp parameters this way, any can be added and we pass them along.

**Comment by pseudotensor** [comment]
I'll close for now.  Probably can play with llama cpp parameters to optimize use of longer context for GGUF.
