### ISSUE TITLE
Text Embedding Inference Server -- how to use in windows.

### ISSUE THREAD

**Issue by oldgithubman** [h2oai/h2ogpt#1438]
Trying to follow the directions in the FAQ for setting up TEI and as far as I can tell, they're full of errors, at least for my windows environment. Considering there's no mention of linux or windows and you're obviously catering to windows users as well, this is a frustrating problem (and *far* too common in this space).
Regarding
`docker run -d --gpus '"device=0"' --shm-size 3g -v $HOME/.cache/huggingface/hub/:/data -p 5555:80 --pull always ghcr.io/huggingface/text-embeddings-inference:0.6 --model-id BAAI/bge-large-en-v1.5 --revision refs/pr/5 --hf-api-token=$HUGGING_FACE_HUB_TOKEN --max-client-batch-size=4096 --max-batch-tokens=2097152`

`'"device=0"'`
throws an error. Needs to be `0`.
`$HOME/.cache/huggingface/hub/:/data`
throws an error. On windows, you probably don't want to do this for performance reasons, but
`C:\Users\`[user]`\.cache\huggingface\hub\:/data`
works.
"Then for h2oGPT ensure pass:" makes no sense. What is this supposed to mean? I'm guessing you mean you should run something like:
 `C:\Users\[user]\AppData\Local\Programs\h2oGPT\Python\python.exe "C:\Users\[user]\AppData\Local\Programs\h2oGPT\h2oGPT.launch.pyw" --hf_embedding_model=tei:http://localhost:5555 --cut_distance=10000`

`--hf_embedding_model=tei:http://localhost:5555 --cut_distance=10000`
throws an error:
`ValueError: Path tei:http://localhost:5555 not found`
I haven't been able to fix that one because I don't even know where to start.
"or whatever address is required." is not helpful

```
C:\Users\J\AppData\Local\Programs\h2oGPT\..\src
C:\Users\J\AppData\Local\Programs\h2oGPT\pkgs\..\src
C:\Users\J\AppData\Local\Programs\h2oGPT\..\iterators
C:\Users\J\AppData\Local\Programs\h2oGPT\pkgs\..\iterators
C:\Users\J\AppData\Local\Programs\h2oGPT\..\gradio_utils
C:\Users\J\AppData\Local\Programs\h2oGPT\pkgs\..\gradio_utils
C:\Users\J\AppData\Local\Programs\h2oGPT\..\metrics
C:\Users\J\AppData\Local\Programs\h2oGPT\pkgs\..\metrics
C:\Users\J\AppData\Local\Programs\h2oGPT\..\models
C:\Users\J\AppData\Local\Programs\h2oGPT\pkgs\..\models
C:\Users\J\AppData\Local\Programs\h2oGPT\..\.
C:\Users\J\AppData\Local\Programs\h2oGPT\pkgs\..\.
Torch Status: have torch: True need get gpu torch: False CVD: None GPUs: 1
Fontconfig error: Cannot load default config file: No such file: (null)
fatal: not a git repository (or any of the parent directories): .git
Traceback (most recent call last):
  File "C:\Users\J\AppData\Local\Programs\h2oGPT\h2oGPT.launch.pyw", line 35, in <module>
    main()
  File "C:\Users\J\AppData\Local\Programs\h2oGPT\pkgs\win_run_app.py", line 150, in main
    _main()
  File "C:\Users\J\AppData\Local\Programs\h2oGPT\pkgs\win_run_app.py", line 136, in _main
    main_h2ogpt()
  File "C:\Users\J\AppData\Local\Programs\h2oGPT\generate.py", line 12, in entrypoint_main
    H2O_Fire(main)
  File "C:\Users\J\AppData\Local\Programs\h2oGPT\src\utils.py", line 65, in H2O_Fire
    fire.Fire(component=component, command=args)
  File "C:\Users\J\AppData\Local\Programs\h2oGPT\pkgs\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\Users\J\AppData\Local\Programs\h2oGPT\pkgs\fire\core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "C:\Users\J\AppData\Local\Programs\h2oGPT\pkgs\fire\core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "C:\Users\J\AppData\Local\Programs\h2oGPT\src\gen.py", line 1664, in main
    model=get_embedding(use_openai_embedding, hf_embedding_model=hf_embedding_model,
  File "C:\Users\J\AppData\Local\Programs\h2oGPT\src\gpt_langchain.py", line 461, in get_embedding
    embedding = HuggingFaceEmbeddings(model_name=hf_embedding_model, model_kwargs=model_kwargs)
  File "C:\Users\J\AppData\Local\Programs\h2oGPT\pkgs\langchain_community\embeddings\huggingface.py", line 65, in __init__
    self.client = sentence_transformers.SentenceTransformer(
  File "C:\Users\J\AppData\Local\Programs\h2oGPT\pkgs\sentence_transformers\SentenceTransformer.py", line 77, in __init__
    raise ValueError("Path {} not found".format(model_name_or_path))
ValueError: Path tei:http://localhost:5555 not found
```

**Comment by pseudotensor** [comment]
It's true that things in the FAQ are heavily geared towards linux/x86 explanations.  One would need to be able to understand both and translate to windows.

**Comment by pseudotensor** [comment]
If you are using the one-click windows installer as a base, that will also be behind main branch.  If you want to keep up with bleeding edge that's in main, need to use the manual installer.  I only added TEI 1 week ago.

It's not hard, it's just a script that's run.  Then it will be able to work with that FAQ element.

**Comment by pseudotensor** [comment]
@ChathurindaRanasinghe is working on a stable release, it's been in works, but our company is too small to do everything you are asking for.

**Comment by pseudotensor** [comment]
Good luck.
