### ISSUE TITLE
Error connection timeout

### ISSUE THREAD

**Issue by slavag** [h2oai/h2ogpt#1439]
After getting result on the question, in many case I started to get that error when I'm clicking on "Clear" button.
<img width="2290" alt="image" src="https://github.com/h2oai/h2ogpt/assets/511540/9d251c4d-5196-4a8b-ad67-1ac7479fc2f1">

in the console (verbose==True) I don't see anything suspicious :
```
Post-Generate Langchain: 2024-02-29 09:54:47.236477 decoded_output: 13402
INFO:     10.0.100.49:61784 - "POST /queue/join HTTP/1.1" 200 OK
INFO:     10.0.100.49:61784 - "GET /queue/data?session_hash=31z1275j41a HTTP/1.1" 200 OK
INFO:     10.0.100.49:61784 - "POST /queue/join HTTP/1.1" 200 OK
INFO:     10.0.100.49:61784 - "GET /queue/data?session_hash=31z1275j41a HTTP/1.1" 200 OK
INFO:     10.0.100.49:61784 - "POST /queue/join HTTP/1.1" 200 OK
INFO:     10.0.100.49:61784 - "GET /queue/data?session_hash=31z1275j41a HTTP/1.1" 200 OK
INFO:     10.0.100.49:62041 - "POST /queue/join HTTP/1.1" 200 OK
INFO:     10.0.100.49:62041 - "GET /queue/data?session_hash=31z1275j41a HTTP/1.1" 200 OK
INFO:     10.0.100.49:62041 - "POST /queue/join HTTP/1.1" 200 OK
INFO:     10.0.100.49:62041 - "GET /queue/data?session_hash=31z1275j41a HTTP/1.1" 200 OK
INFO:     10.0.100.49:62041 - "POST /queue/join HTTP/1.1" 200 OK
INFO:     10.0.100.49:62041 - "GET /queue/data?session_hash=31z1275j41a HTTP/1.1" 200 OK
INFO:     10.0.100.49:62044 - "POST /queue/join HTTP/1.1" 200 OK
INFO:     10.0.100.49:62044 - "GET /queue/data?session_hash=31z1275j41a HTTP/1.1" 200 OK
INFO:     10.0.100.49:62044 - "POST /queue/join HTTP/1.1" 200 OK
INFO:     10.0.100.49:62044 - "GET /queue/data?session_hash=31z1275j41a HTTP/1.1" 200 OK
INFO:     10.0.100.49:62044 - "POST /queue/join HTTP/1.1" 200 OK
INFO:     10.0.100.49:62044 - "GET /queue/data?session_hash=31z1275j41a HTTP/1.1" 200 OK
```

**Comment by pseudotensor** [comment]
I've seen that sometimes too, although rarely.  I think it is due to gradio 4.

If you want to go back to gradio 3, h2oGPT is compatible with that.  You just need to do:

```
pip uninstall gradio gradio_client gradio_pdf -y
pip install gradio==3.50.2
```

let me know if this helps.  In meantime, I'll see what gradio team think.

**Comment by slavag** [comment]
@pseudotensor  it's failing with that version of gradio (3.50.2)
```
/mnt/AI/h2ogpt/gradio_utils/prompt_form.py:209: GradioUnusedKwargWarning: You have unused kwarg parameters in Chatbot, please remove them: {'likeable': True}
  text_output = gr.Chatbot(label=output_label0,
/mnt/AI/h2ogpt/gradio_utils/prompt_form.py:214: GradioUnusedKwargWarning: You have unused kwarg parameters in Chatbot, please remove them: {'likeable': True}
  text_output2 = gr.Chatbot(label=output_label0_model2,
Traceback (most recent call last):
  File "/mnt/AI/h2ogpt/generate.py", line 20, in <module>
    entrypoint_main()
  File "/mnt/AI/h2ogpt/generate.py", line 16, in entrypoint_main
    H2O_Fire(main)
  File "/mnt/AI/h2ogpt/src/utils.py", line 69, in H2O_Fire
    fire.Fire(component=component, command=args)
  File "/mnt/AI/miniconda3/envs/python311/lib/python3.11/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/AI/miniconda3/envs/python311/lib/python3.11/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/mnt/AI/miniconda3/envs/python311/lib/python3.11/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/AI/h2ogpt/src/gen.py", line 2194, in main
    go_gradio(**locals())
  File "/mnt/AI/h2ogpt/src/gradio_runner.py", line 1268, in go_gradio
    text_output, text_output2, text_outputs = make_chatbots(output_label0, output_label0_model2,
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/AI/h2ogpt/gradio_utils/prompt_form.py", line 349, in make_chatbots
    rating1.click(ratingfn1, outputs=rating_text_output, js=review_js1)
TypeError: EventListenerMethod.__call__() got an unexpected keyword argument 'js'
```

**Comment by pseudotensor** [comment]
Yes thanks, recent commit from external contrib.  We don't test for this backwards compat.  I fixed the issue, please try again.

**Comment by pseudotensor** [comment]
![image](https://github.com/h2oai/h2ogpt/assets/2249614/33e3ec58-6881-442a-b16c-709d881413f0)

**Comment by slavag** [comment]
@pseudotensor Working much better, stable, Thanks
