### ISSUE TITLE
install fails with langchain requirements (overcome) then with No module named 'pandas._libs.reduction'

### ISSUE THREAD

**Issue by ramz35** [h2oai/h2ogpt#1447]
Windows.
It failed at this step:
pip install -r reqs_optional/requirements_optional_langchain.txt

The conflict is caused by:
    The user requested langchain-core==0.1.6
    langchain 0.0.354 depends on langchain-core<0.2 and >=0.1.5
    langchain-experimental 0.0.47 depends on langchain-core<0.2 and >=0.1
    langchain-community 0.0.8 depends on langchain-core<0.2 and >=0.1.5
    langchain-anthropic 0.1.1 depends on langchain-core<0.2 and >=0.1
    langchain-google-genai 0.0.6 depends on langchain-core<0.2 and >=0.1
    langchain-mistralai 0.0.5 depends on langchain-core<0.2.0 and >=0.1.27

I solved it (without knowing what knock on effects there may be) by removing version numbers for:
langchain
langchain-community
langchain-core
langchain_experimental
langchain-anthropic
langchain-google-genai
langchain_mistralai

Then the rest installed ok:
pip install -r reqs_optional/requirements_optional_gpt4all.txt
pip install -r reqs_optional/requirements_optional_langchain.urls.txt
pip install -r reqs_optional/requirements_optional_langchain.gpllike.txt

but when I try to run python generate.py --base_model=TheBloke/zephyr-7B-beta-GGUF --prompt_type=zephyr --max_seq_len=4096

I get:

**Comment by sorhtyre** [comment]
I'm getting the same issue on a clean install of Xubuntu 23.10

```
INFO: pip is looking at multiple versions of langchain-mistralai to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install -r reqs_optional/requirements_optional_langchain.txt (line 11), -r reqs_optional/requirements_optional_langchain.txt (line 12), -r reqs_optional/requirements_optional_langchain.txt (line 13), -r reqs_optional/requirements_optional_langchain.txt (line 27), -r reqs_optional/requirements_optional_langchain.txt (line 29), -r reqs_optional/requirements_optional_langchain.txt (line 31) and langchain-core==0.1.6 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested langchain-core==0.1.6
    langchain 0.0.354 depends on langchain-core<0.2 and >=0.1.5
    langchain-experimental 0.0.47 depends on langchain-core<0.2 and >=0.1
    langchain-community 0.0.8 depends on langchain-core<0.2 and >=0.1.5
    langchain-anthropic 0.1.1 depends on langchain-core<0.2 and >=0.1
    langchain-google-genai 0.0.6 depends on langchain-core<0.2 and >=0.1
    langchain-mistralai 0.0.5 depends on langchain-core<0.2.0 and >=0.1.27

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

```

**Comment by ramz35** [comment]
@sorhtyre I can get around that (see my post) but I don't know what knock on effects it may have.  Currently something in the install instructions is broken.

**Comment by sorhtyre** [comment]
I just attempted to install the others manually. I'm running this in CPU mode only and it needs langchain installed.

even after installing the other requirements:
```
pip install -r reqs_optional/requirements_optional_gpt4all.txt
pip install -r reqs_optional/requirements_optional_langchain.urls.txt
pip install -r reqs_optional/requirements_optional_langchain.gpllike.txt
```

I cannot run a mode.
```
python generate.py --base_model=llama --model_path_llama=https://huggingface.co/TheBloke/Llama-2-7b-Chat-GGUF/resolve/main/llama-2-7b-chat.Q6_K.gguf --llamacpp_dict="{'use_mlock':False,'n_batch':256}" --max_seq_len=512 --score_model=None --langchain_mode='UserData' --user_path=user_path
No GPUs detected
soundfile, librosa, and wavio not installed, disabling STT
soundfile, librosa, and wavio not installed, disabling TTS
Must install langchain for transcription, disabling
Using Model llama
Must install langchain for preloading embedding model, disabling
Must install DocTR and LangChain installed if enabled DocTR, disabling
Starting get_model: llama 
Starting get_model: llama 
Starting get_model: llama 
Starting get_model: llama 
Traceback (most recent call last):
  File "/home/rag/h2ogpt/generate.py", line 20, in <module>
    entrypoint_main()
  File "/home/rag/h2ogpt/generate.py", line 16, in entrypoint_main
    H2O_Fire(main)
  File "/home/rag/h2ogpt/src/utils.py", line 69, in H2O_Fire
    fire.Fire(component=component, command=args)
  File "/home/rag/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/rag/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/rag/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/rag/h2ogpt/src/gen.py", line 2141, in main
    model0, tokenizer0, device = get_model_retry(reward_type=False,
  File "/home/rag/h2ogpt/src/gen.py", line 2478, in get_model_retry
    model1, tokenizer1, device1 = get_model(**kwargs)
  File "/home/rag/h2ogpt/src/gen.py", line 2938, in get_model
    from gpt4all_llm import get_model_tokenizer_gpt4all
  File "/home/rag/h2ogpt/src/gpt4all_llm.py", line 4, in <module>
    from langchain.callbacks.manager import CallbackManagerForLLMRun
ModuleNotFoundError: No module named 'langchain'
```

**Comment by ramz35** [comment]
@pseudotensor 
> 
> Note that `-c reqs_optional/reqs_constraints.txt` is required, else pandas will update to latest and that will lead to the failure in the title of this issue.

I may have missed this somewhere but I don't see that in the install instructions :(

**Comment by pseudotensor** [comment]
It's in the windows and linux installer scripts, but not the basic readme.md quick start.  The wheel or one-click installer would also be consistent and constrained.

**Comment by ramz35** [comment]
Might be helpful to mention something in the readme and quickstart but since I have a working version I'm going to rerun the quickstart and then do the installer scripts (to satisfy my curiosity and for future reference).  Thanks for your quick replies here!

**Comment by pseudotensor** [comment]
Ya it's not in the readme.md basic quick install because it's not required.  torch and gradio only get messed up later by optional packages not listed.

This issue was just confusing because I had constrained pandas too, but this is no longer required after removing the unnecessary python code that gave the title of this issue.
