### ISSUE TITLE
unable to upload txt when running from wsl

### ISSUE THREAD

**Issue by stabilitygenius** [h2oai/h2ogpt#1464]
Thanks for the project. 

When using virtualenv and WSL with the GPU, just chatting works OK, but when trying to upload any files, e.g., txt, the following error appears:

Error
no such column: embedding_metadata.bool_value

When clicking upload, it does go to the windows and not the linux filesystem, so wondering if that might've caused the issue.

Any suggestions or thoughts regarding 1) the root cause and 2) how to work around? Thanks.

**Comment by stabilitygenius** [comment]
Traceback as below

Traceback (most recent call last):
  File "/home/username/project_name/venv/lib/python3.10/site-packages/gradio/queueing.py", line 501, in call_prediction
    output = await route_utils.call_process_api(
  File "/home/username/project_name/venv/lib/python3.10/site-packages/gradio/route_utils.py", line 252, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/username/project_name/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1664, in process_api
    result = await self.call_function(
  File "/home/username/project_name/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1205, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/username/project_name/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/home/username/project_name/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
  File "/home/username/project_name/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "/home/username/project_name/venv/lib/python3.10/site-packages/gradio/utils.py", line 702, in wrapper
    response = f(*args, **kwargs)
  File "/home/username/project_name/h2ogpt/src/gradio_runner.py", line 6702, in get_source_files_given_langchain_mode_gr
    return get_source_files_given_langchain_mode(db1s, selection_docs_state1, requests_state1, None,
  File "/home/username/project_name/h2ogpt/src/gpt_langchain.py", line 8112, in get_source_files_given_langchain_mode
    db = get_any_db(db1s, langchain_mode, langchain_mode_paths, langchain_mode_types,
  File "/home/username/project_name/h2ogpt/src/gpt_langchain.py", line 7639, in get_any_db
    get_existing_db(db, persist_directory, load_db_if_exists, db_type,
  File "/home/username/project_name/h2ogpt/src/gpt_langchain.py", line 4525, in get_existing_db
    db.similarity_search('')
  File "/home/username/project_name/venv/lib/python3.10/site-packages/langchain_community/vectorstores/chroma.py", line 348, in similarity_search
    docs_and_scores = self.similarity_search_with_score(
  File "/home/username/project_name/venv/lib/python3.10/site-packages/langchain_community/vectorstores/chroma.py", line 438, in similarity_search_with_score
    results = self.__query_collection(
  File "/home/username/project_name/venv/lib/python3.10/site-packages/langchain_core/utils/utils.py", line 35, in wrapper
    return func(*args, **kwargs)
  File "/home/username/project_name/venv/lib/python3.10/site-packages/langchain_community/vectorstores/chroma.py", line 155, in __query_collection
    return self._collection.query(
  File "/home/username/project_name/venv/lib/python3.10/site-packages/chromadb/api/models/Collection.py", line 345, in query
    query_results = self._client._query(
  File "/home/username/project_name/venv/lib/python3.10/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 127, in wrapper
    return f(*args, **kwargs)
  File "/home/username/project_name/venv/lib/python3.10/site-packages/chromadb/api/segment.py", line 717, in _query
    records = metadata_reader.get_metadata(ids=list(all_ids))
  File "/home/username/project_name/venv/lib/python3.10/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 127, in wrapper
    return f(*args, **kwargs)
  File "/home/username/project_name/venv/lib/python3.10/site-packages/chromadb/segment/impl/metadata/sqlite.py", line 214, in get_metadata
    return list(self._records(cur, q))
  File "/home/username/project_name/venv/lib/python3.10/site-packages/chromadb/segment/impl/metadata/sqlite.py", line 223, in _records
    cur.execute(sql, params)
sqlite3.OperationalError: no such column: embedding_metadata.bool_value

**Comment by pseudotensor** [comment]
Probably related to that.  Seems to be a pure chroma db issue with your system.

**Comment by stabilitygenius** [comment]
After deeper analysis appears to be an issue with the default python installation missing FTS5 support, causing the chromadb problem - so need to re-compile Python from source with ./configure --enable-loadable-sqlite-extensions CFLAGS="-DSQLITE_ENABLE_FTS5"
