### ISSUE TITLE
Failed base_model=h2oai/h2ogpt-4096-llama2-7b-chat

### ISSUE THREAD

**Issue by juerware** [h2oai/h2ogpt#1483]
There is problem with some models for h2oai huggingface
```
(h2ogpt) root@privategpt:~/h2ogpt# git status
HEAD detached from 9d4021dc
```

Cuda information:
```
# nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Feb__7_19:32:13_PST_2023
Cuda compilation tools, release 12.1, V12.1.66
Build cuda_12.1.r12.1/compiler.32415258_0
```
```
# nvidia-smi
Fri Mar 15 14:57:18 2024
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.30.02              Driver Version: 530.30.02    CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                  Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA A30                      On | 00000000:13:00.0 Off |                    0 |
| N/A   29C    P0               28W / 165W|      0MiB / 24576MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
```

Execution problem is:
```
# python generate.py --base_model=h2oai/h2ogpt-4096-llama2-7b-chat --prompt_type=llama2 --use_gpu_id=True --gpu_id=-1 --share=True
Using Model h2oai/h2ogpt-4096-llama2-7b-chat
load INSTRUCTOR_Transformer
max_seq_length  512
Starting get_model: h2oai/h2ogpt-4096-llama2-7b-chat
config.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 617/617 [00:00<00:00, 5.38MB/s]
tokenizer_config.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 776/776 [00:00<00:00, 11.0MB/s]
tokenizer.model: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 500k/500k [00:00<00:00, 1.66MB/s]
tokenizer.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.84M/1.84M [00:00<00:00, 3.79MB/s]
special_tokens_map.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 414/414 [00:00<00:00, 5.79MB/s]
Starting get_model: h2oai/h2ogpt-4096-llama2-7b-chat
Starting get_model: h2oai/h2ogpt-4096-llama2-7b-chat
Starting get_model: h2oai/h2ogpt-4096-llama2-7b-chat
Traceback (most recent call last):
  File "/root/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1390, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/root/miniconda3/envs/h2ogpt/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 53, in <module>
    from flash_attn import flash_attn_func, flash_attn_varlen_func
  File "/root/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/flash_attn/__init__.py", line 3, in <module>
    from flash_attn.flash_attn_interface import (
  File "/root/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/flash_attn/flash_attn_interface.py", line 10, in <module>
    import flash_attn_2_cuda as flash_attn_cuda
ImportError: /root/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops5zeros4callEN3c108ArrayRefINS2_6SymIntEEENS2_8optionalINS2_10ScalarTypeEEENS6_INS2_6LayoutEEENS6_INS2_6DeviceEEENS6_IbEE

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/REPOSITORIES/aramirez/h2ogpt/generate.py", line 20, in <module>
    entrypoint_main()
  File "/root/REPOSITORIES/aramirez/h2ogpt/generate.py", line 16, in entrypoint_main
    H2O_Fire(main)
  File "/root/REPOSITORIES/aramirez/h2ogpt/src/utils.py", line 69, in H2O_Fire
    fire.Fire(component=component, command=args)
  File "/root/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/root/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/root/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/root/REPOSITORIES/aramirez/h2ogpt/src/gen.py", line 2156, in main
    model0, tokenizer0, device = get_model_retry(reward_type=False,
  File "/root/REPOSITORIES/aramirez/h2ogpt/src/gen.py", line 2504, in get_model_retry
    model1, tokenizer1, device1 = get_model(**kwargs)
  File "/root/REPOSITORIES/aramirez/h2ogpt/src/gen.py", line 3103, in get_model
    return get_hf_model(load_8bit=load_8bit,
  File "/root/REPOSITORIES/aramirez/h2ogpt/src/gen.py", line 3298, in get_hf_model
    config, model, max_seq_len = get_config(base_model,
  File "/root/REPOSITORIES/aramirez/h2ogpt/src/gen.py", line 2280, in get_config
    model = AutoModel.from_config(
  File "/root/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 434, in from_config
    model_class = _get_model_class(config, cls._model_mapping)
  File "/root/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 381, in _get_model_class
    supported_models = model_mapping[type(config)]
  File "/root/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 732, in __getitem__
    return self._load_attr_from_module(model_type, model_name)
  File "/root/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 746, in _load_attr_from_module
    return getattribute_from_module(self._modules[module_name], attr)
  File "/root/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 690, in getattribute_from_module
    if hasattr(module, attr):
  File "/root/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1380, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/root/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1392, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.llama.modeling_llama because of the following error (look up to see its traceback):
/root/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops5zeros4callEN3c108ArrayRefINS2_6SymIntEEENS2_8optionalINS2_10ScalarTypeEEENS6_INS2_6LayoutEEENS6_INS2_6DeviceEEENS6_IbEE
```

Python version:
```
# python --version
Python 3.10.13
```

There are other models with no problems as: 
```
python generate.py --base_model=TheBloke/Mistral-7B-Instruct-v0.2-GGUF --prompt_type=mistral --max_seq_len=4096
```

**Comment by pseudotensor** [comment]
Can you try:
```
pip uninstall flash_attn autoawq autoawq-kernels
```
and see if works now.  And then try:
```
pip install  flash_attn autoawq autoawq-kernels
```

And what git hash did you build the env off of?

**Comment by juerware** [comment]
Hi, thanks in advance for the solutions, it works but there is no automatic process to work out it, I mean, I use this script to automate the process:
```
#!/bin/bash

set -x && \

apt-get clean all 2>&1 && \
apt-get update 2>&1 && \
apt-get -y full-upgrade 2>&1 && \
apt-get -y dist-upgrade 2>&1 && \
apt-get -y autoremove 2>&1 && \
apt-get clean all 2>&1 && \

cd ~/REPOSITORIES/aramirez && \
rm -fr h2ogpt && \
git clone https://github.com/h2oai/h2ogpt.git && \
cd h2ogpt && \

conda deactivate && \
conda remove -n h2ogpt --all -y && \
conda update conda -y && \
conda create -n h2ogpt -y && \
conda activate h2ogpt && \
conda install python=3.10 -c conda-forge -y && \

# pip install -r requirements.txt && \
# pip install -r reqs_optional/requirements_optional_langchain.txt && \
# pip install -r reqs_optional/requirements_optional_gpt4all.txt && \
# pip install -r reqs_optional/requirements_optional_langchain.urls.txt && \

export CUDA_HOME=/usr/local/cuda && \ # it is a soft link to /usr/local/cuda-12.1
export PIP_EXTRA_INDEX_URL="https://download.pytorch.org/whl/cu121" && \
export LLAMA_CUBLAS=1
export CMAKE_ARGS="-DLLAMA_CUBLAS=on -DCMAKE_CUDA_ARCHITECTURES=all"
export FORCE_CMAKE=1
set +x && \
GPLOK=1 bash docs/linux_install.sh && \

# https://github.com/h2oai/h2ogpt/issues/1483
pip uninstall flash_attn autoawq autoawq-kernels -y && pip install flash_attn autoawq autoawq-kernels && \

echo -e "\n\n\n\t\tFINISHED - Right\n\n\n";
```
Maybe the solution should be implemented in this script "docs/linux_install.sh" instead of doing it as a command apart.
This is only a suggestion and your point of view is appreciated.
As you can see last version of h2ogtp is always executed.

**Comment by pseudotensor** [comment]
Thanks good idea.  I started it by adding such a script, but will see how to avoid copy-paste issues.
