### ISSUE TITLE
"configure_parser" issue at install

### ISSUE THREAD

**Issue by Aloks6** [h2oai/h2ogpt#1523]
Hello !
First, thank you for your project, I'm looking forward to test it !

I tried to install it, following the [install instruction](https://github.com/h2oai/h2ogpt/blob/main/docs/README_LINUX.md) (Debian 12)
Getting to the "install h2ogpt env", I got an issue :
`# install h2ogpt env
conda remove -n h2ogpt --all -y`

returned 
```
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/iaeval1/miniconda3/lib/python3.10/site-packages/conda/exceptions.py", line 1124, in __call__
        return func(*args, **kwargs)
      File "/home/iaeval1/miniconda3/lib/python3.10/site-packages/conda/cli/main.py", line 57, in main_subshell
        p = generate_parser()
      File "/home/iaeval1/miniconda3/lib/python3.10/site-packages/conda/cli/conda_argparse.py", line 40, in generate_parser
        p = ArgumentParser(
      File "/home/iaeval1/miniconda3/lib/python3.10/site-packages/conda/cli/conda_argparse.py", line 117, in __init__
        self._subcommands = context.plugin_manager.get_hook_results("subcommands")
      File "/home/iaeval1/miniconda3/lib/python3.10/site-packages/conda/plugins/manager.py", line 77, in get_hook_results
        plugins = sorted(
      File "/home/iaeval1/miniconda3/lib/python3.10/site-packages/conda/plugins/manager.py", line 78, in <genexpr>
        (item for items in hook() for item in items),
      File "/home/iaeval1/miniconda3/lib/python3.10/site-packages/conda_libmamba_solver/plugin.py", line 23, in conda_subcommands
        yield plugins.CondaSubcommand(
    TypeError: CondaSubcommand.__new__() got an unexpected keyword argument 'configure_parser'

`$ /home/iaeval1/miniconda3/bin/conda remove -n h2ogpt --all -y`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/home/iaeval1/miniconda3/bin/conda
             CONDA_PREFIX=/home/iaeval1/miniconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/home/iaeval1/miniconda3/bin/python
               CONDA_ROOT=/home/iaeval1/miniconda3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
          LD_LIBRARY_PATH=/usr/local/cuda-12.4/lib64:/usr/local/cuda-12.4/lib64:
               LD_PRELOAD=<not set>
                     PATH=/home/iaeval1/miniconda3/bin:/home/iaeval1/miniconda3/condabin:/usr/lo
                          cal/cuda-12.4/bin:/usr/local/cuda-
                          12.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
               WINDOWPATH=2

     active environment : base
    active env location : /home/iaeval1/miniconda3
            shell level : 1
       user config file : /home/iaeval1/.condarc
 populated config files : 
          conda version : 23.1.0
    conda-build version : not installed
         python version : 3.10.9.final.0
       virtual packages : __archspec=1=haswell
                          __cuda=12.4=0
                          __glibc=2.36=0
                          __linux=6.1.0=0
                          __unix=0=0
       base environment : /home/iaeval1/miniconda3  (writable)
      conda av data dir : /home/iaeval1/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/iaeval1/miniconda3/pkgs
                          /home/iaeval1/.conda/pkgs
       envs directories : /home/iaeval1/miniconda3/envs
                          /home/iaeval1/.conda/envs
               platform : linux-64
             user-agent : conda/23.1.0 requests/2.28.1 CPython/3.10.9 Linux/6.1.0-18-amd64 debian/12 glibc/2.36
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.


```

I went to the "plugin.py" to check : 
```
from conda import plugins

from .repoquery import configure_parser, repoquery
from .solver import LibMambaSolver


@plugins.hookimpl
def conda_solvers():
    """
    The conda plugin hook implementation to load the solver into conda.
    """
    yield plugins.CondaSolver(
        name="libmamba",
        backend=LibMambaSolver,
    )


@plugins.hookimpl
def conda_subcommands():
    yield plugins.CondaSubcommand(
        name="repoquery",
        summary="Advanced search for repodata.",
        action=repoquery,
        configure_parser=configure_parser,
    )
```

What `configure_parser` do ? Can I replace it with `configparser` ?
How to fix that issue ? I checked but it seems no other issues of that type was reported

Thank you very much for your help !

**Comment by pseudotensor** [comment]
I'm not familiar with that issue or know why it happened.  But `conda remove -n h2ogpt --all -y` can be avoided if don't already have h2oGPT installed.

**Comment by Aloks6** [comment]
Hello !
Thank you for your answer ! Though, this issue is not completed. Could you please reopen it ?

I knew it could be avoided, so I already ran the next command and got the same issue. So is for the `conda create -n h2ogpt -y`, and so is for the quick install... The same error keep repeating, with `configure_parser` not being recognized 
`TypeError: CondaSubcommand.__new__() got an unexpected keyword argument 'configure_parser'`

Thanks to anyone who could explain why this error appear or how to fix it !

**Comment by Aloks6** [comment]
Hello !
Thank you for your answer ! 

I knew it could be avoided, so I already ran the next command and got the same issue. So is for the conda create -n h2ogpt -y, and so is for the quick install... The same error keep repeating, with configure_parser not being recognized
TypeError: CondaSubcommand.__new__() got an unexpected keyword argument 'configure_parser'

Thing was on my side, I performed a clean install of miniconda and it now works :) 
Thank you again for checking it

**Comment by pseudotensor** [comment]
Ah ok, makes sense.
