### ISSUE TITLE
AWQ Model Works from UI in Windows, But Fails When Launched from .bat File

### ISSUE THREAD

**Issue by Yusuf-Demiryurek** [h2oai/h2ogpt#1561]
Hi,

I need your help :)

I'm trying to launch H2OGPT from a .bat file on Windows with an AWQ model as a parameter, but it doesn't seem to work. Below is the content of the .bat file :
`cd %HOMEDRIVE%\%HOMEPATH%\h2ogpt_data`
`C:\Users\yuyu\AppData\Local\Programs\h2oGPT\Python\pythonw.exe "C:\Users\yuyu\AppData\Local\Programs\h2oGPT\h2oGPT.launch.pyw" --load_awq=model --base_model=TheBloke/zephyr-7B-beta-AWQ `

When I use a GGUF model instead of AWQ, it works fine. Also, loading the AWQ model from the UI works without any issues.

I've tried various parameters and searched through the documentation, but nothing has helped me to get it running from the .bat file.

I'm running it on a computer with 128GB of RAM and an RTX 4090 GPU.

Could someone please help me? Thanks. 😄

**Comment by pseudotensor** [comment]
I'm not an expert at .bat files.  I used chatgpt to help me with .bat file stuff for h2oGPT, so I recommend doing same with your errors or seeing if someone else will respond.

Also, you didn't say what the issue is.

**Comment by Yusuf-Demiryurek** [comment]
I don't believe the issue lies with the .bat file itself. The .bat file functions similarly to the python generate.py command with parameters. The problem arises when attempting to run the AWQ model through the .bat file. Interestingly, the AWQ model runs perfectly fine when loaded from the UI, but H2OGPT doesn't start when using the .bat file.

Furthermore, if I use --base_model=TheBloke/zephyr-7B-beta-GGUF instead of --base_model=TheBloke/zephyr-7B-beta-AWQ in the .bat file, H2OGPT starts without any issues with the GGUF model loaded.

There appears to be a discrepancy in behavior between loading the model from the UI and using the --base_model input in the .bat file.

**Comment by pseudotensor** [comment]
I can import upper level thing but I don't have the other thing:

```
(h2ogpt) jon@pseudotensor:~/h2ogpt$ python
Python 3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:45:18) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import awq_inference_engine
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'awq_inference_engine'
>>> from awq import AutoAWQForCausalLM
>>> 
```

Probably the awq install instructions are out of date for windows, will check on it.

**Comment by Yusuf-Demiryurek** [comment]
I got this:
```
Traceback (most recent call last):
  File "C:\Users\balas\AppData\Local\Programs\h2oGPT\Python\test.py", line 1, in <module>
    import awq_inference_engine
ImportError: DLL load failed while importing awq_inference_engine: Le module spécifié est introuvable.
```
I don't understand why it works when I load the model from UI and not in this way
