### ISSUE TITLE
ValueError: load_in_8bit must be a boolean

### ISSUE THREAD

**Issue by Noctis-SC** [h2oai/h2ogpt#1585]
Hello, I'm having trouble running a `h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3` model using h2opgt.

**Here is a command that I call:**
`CUDA_VISIBLE_DEVICES=1 python generate.py --base_model=h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3 --score_model=None prompt_type=human_bot --cli=False load_in_4bit=True device_map=auto`

**Here is an output:**
`Using Model h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3
load INSTRUCTOR_Transformer
max_seq_length  512
Must install DocTR and LangChain installed if enabled DocTR, disabling
Starting get_model: h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3 
Could not determine --max_seq_len, setting to 2048.  Pass if not correct
Could not determine --max_seq_len, setting to 2048.  Pass if not correct
Starting get_model: h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3 
Could not determine --max_seq_len, setting to 2048.  Pass if not correct
Could not determine --max_seq_len, setting to 2048.  Pass if not correct
Starting get_model: h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3 
Could not determine --max_seq_len, setting to 2048.  Pass if not correct
Could not determine --max_seq_len, setting to 2048.  Pass if not correct
Starting get_model: h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3 
Could not determine --max_seq_len, setting to 2048.  Pass if not correct
Could not determine --max_seq_len, setting to 2048.  Pass if not correct
Traceback (most recent call last):
  File "/home/alexander/h2ogpt/generate.py", line 20, in <module>
    entrypoint_main()
  File "/home/alexander/h2ogpt/generate.py", line 16, in entrypoint_main
    H2O_Fire(main)
  File "/home/alexander/h2ogpt/src/utils.py", line 73, in H2O_Fire
    fire.Fire(component=component, command=args)
  File "/home/alexander/anaconda3/envs/h2ogpt/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/alexander/anaconda3/envs/h2ogpt/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/alexander/anaconda3/envs/h2ogpt/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/alexander/h2ogpt/src/gen.py", line 2269, in main
    model0, tokenizer0, device = get_model_retry(reward_type=False,
  File "/home/alexander/h2ogpt/src/gen.py", line 2621, in get_model_retry
    model1, tokenizer1, device1 = get_model(**kwargs)
  File "/home/alexander/h2ogpt/src/gen.py", line 3277, in get_model
    return get_hf_model(load_8bit=load_8bit,
  File "/home/alexander/h2ogpt/src/gen.py", line 3437, in get_hf_model
    model_kwargs['quantization_config'] = BitsAndBytesConfig(
  File "/home/alexander/anaconda3/envs/h2ogpt/lib/python3.10/site-packages/transformers/utils/quantization_config.py", line 284, in __init__
    self.post_init()
  File "/home/alexander/anaconda3/envs/h2ogpt/lib/python3.10/site-packages/transformers/utils/quantization_config.py", line 320, in post_init
    raise ValueError("load_in_8bit must be a boolean")
ValueError: load_in_8bit must be a boolean`

I have tried `CUDA_VISIBLE_DEVICES=1 python generate.py --base_model=TheBloke/CapybaraHermes-2.5-Mistral-7B-GGUF --score_model=None prompt_type=human_bot --cli=False load_in_4bit=True device_map=auto` this command with TheBloke model and works perfectly fine. 

What is the problem?

**Comment by pseudotensor** [comment]
You are missing -- in front of your `load_in_4bit`

**Comment by Noctis-SC** [comment]
> You are missing -- in front of your `load_in_4bit`
Thank you for your reply, I tried your solution, however the problem persists
```
CUDA_VISIBLE_DEVICES=1 python generate.py --base_model=h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3 --score_model=None prompt_type=human_bot --cli=False --load_in_4bit=True device_map=auto
Using Model h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3
load INSTRUCTOR_Transformer
max_seq_length  512
Must install DocTR and LangChain installed if enabled DocTR, disabling
Starting get_model: h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3 
Could not determine --max_seq_len, setting to 2048.  Pass if not correct
Could not determine --max_seq_len, setting to 2048.  Pass if not correct
Starting get_model: h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3 
Could not determine --max_seq_len, setting to 2048.  Pass if not correct
Could not determine --max_seq_len, setting to 2048.  Pass if not correct
Starting get_model: h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3 
Could not determine --max_seq_len, setting to 2048.  Pass if not correct
Could not determine --max_seq_len, setting to 2048.  Pass if not correct
Starting get_model: h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3 
Could not determine --max_seq_len, setting to 2048.  Pass if not correct
Could not determine --max_seq_len, setting to 2048.  Pass if not correct
Traceback (most recent call last):
  File "/home/alexander/h2ogpt/generate.py", line 20, in <module>
    entrypoint_main()
  File "/home/alexander/h2ogpt/generate.py", line 16, in entrypoint_main
    H2O_Fire(main)
  File "/home/alexander/h2ogpt/src/utils.py", line 73, in H2O_Fire
    fire.Fire(component=component, command=args)
  File "/home/alexander/anaconda3/envs/h2ogpt/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/alexander/anaconda3/envs/h2ogpt/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/alexander/anaconda3/envs/h2ogpt/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/alexander/h2ogpt/src/gen.py", line 2269, in main
    model0, tokenizer0, device = get_model_retry(reward_type=False,
  File "/home/alexander/h2ogpt/src/gen.py", line 2621, in get_model_retry
    model1, tokenizer1, device1 = get_model(**kwargs)
  File "/home/alexander/h2ogpt/src/gen.py", line 3277, in get_model
    return get_hf_model(load_8bit=load_8bit,
  File "/home/alexander/h2ogpt/src/gen.py", line 3437, in get_hf_model
    model_kwargs['quantization_config'] = BitsAndBytesConfig(
  File "/home/alexander/anaconda3/envs/h2ogpt/lib/python3.10/site-packages/transformers/utils/quantization_config.py", line 284, in __init__
    self.post_init()
  File "/home/alexander/anaconda3/envs/h2ogpt/lib/python3.10/site-packages/transformers/utils/quantization_config.py", line 320, in post_init
    raise ValueError("load_in_8bit must be a boolean")
```
`ValueError: load_in_8bit must be a boolean`

**Comment by pseudotensor** [comment]
At end you have `device_map=auto` that has no meaning to the CLI.  It interprets it as the next argument.

**Comment by Noctis-SC** [comment]
> At end you have `device_map=auto` that has no meaning to the CLI. It interprets it as the next argument.

Before it worked fine, now even 
`python generate.py --base_model=h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3 --score_model=None prompt_type=human_bot --cli=False` this command doesn't work 

However, 
`python generate.py --base_model=TheBloke/CapybaraHermes-2.5-Mistral-7B-GGUF --score_model=None prompt_type=human_bot --cli=False` when I call base model from TheBloke works for me

What do you think?

**Comment by pseudotensor** [comment]
YOu again miss -- before "prompt_type".
