### ISSUE TITLE
Support for https://huggingface.co/lightblue/suzume-llama-3-8B-multilingual

### ISSUE THREAD

**Issue by plitc** [h2oai/h2ogpt#1594]
Dear h2o team,

please add support for llama3 based models like: https://huggingface.co/lightblue/suzume-llama-3-8B-multilingual

thanks in advance and best regards

Daniel Plominski

**Comment by pseudotensor** [comment]
It already has a chat template, which means it would work OOTB.

https://huggingface.co/lightblue/suzume-llama-3-8B-multilingual/blob/main/tokenizer_config.json#L2053

**Comment by plitc** [comment]
Documents Parsing doesnt work:

Step 1: Create DB
```
#!/bin/sh

export HUGGING_FACE_HUB_TOKEN=XXX
export CUDA_VISIBLE_DEVICES="0,1"
docker run \
       --gpus all \
       --runtime=nvidia \
       --shm-size=64g \
       -p 7860:7860 \
       --rm --init \
       -v /etc/passwd:/etc/passwd:ro \
       -v /etc/group:/etc/group:ro \
       -u 1000:1000 \
       -v /opt/h2ogpt_data/.cache:/workspace/.cache \
       -v /opt/h2ogpt_data/save:/workspace/save \
       -v /opt/h2ogpt_data/db_dir_MyData:/workspace/db_dir_MyData \
       -v /opt/h2ogpt_data/db_dir_UserData:/workspace/db_dir_UserData \
       -v /opt/h2ogpt_data/tmp:/tmp \
       -v /opt/h2ogpt_data/DATA:/workspace/user_path/DATA \
       -e HUGGING_FACE_HUB_TOKEN=$HUGGING_FACE_HUB_TOKEN \
       -e TOKENIZERS_PARALLELISM=false \
       -e ADMIN_PASS=XXX \
       -e CONCURRENCY_COUNT=1 \
       gcr.io/vorvan/h2oai/h2ogpt-runtime:latest /workspace/src/make_db.py --db_type=chroma

# EOF
```

Step 2: Run
```
#!/bin/sh

export HUGGING_FACE_HUB_TOKEN=XXX
export CUDA_VISIBLE_DEVICES="0,1"
docker run \
       --gpus all \
       --runtime=nvidia \
       --shm-size=64g \
       -p 7860:7860 \
       --rm --init \
       -v /etc/passwd:/etc/passwd:ro \
       -v /etc/group:/etc/group:ro \
       -u 1000:1000 \
       -v /opt/h2ogpt_data/.cache:/workspace/.cache \
       -v /opt/h2ogpt_data/save:/workspace/save \
       -v /opt/h2ogpt_data/db_dir_UserData:/workspace/db_dir_UserData \
       -v /opt/h2ogpt_data/tmp:/tmp \
       -v /opt/h2ogpt_data/DATA:/workspace/user_path/DATA \
       -e HUGGING_FACE_HUB_TOKEN=$HUGGING_FACE_HUB_TOKEN \
       -e TOKENIZERS_PARALLELISM=false \
       -e ADMIN_PASS=XXX \
       -e CONCURRENCY_COUNT=1 \
       -e API_OPEN=1 \
       -e ALLOW_API=1 \
       gcr.io/vorvan/h2oai/h2ogpt-runtime:latest /workspace/generate.py \
          --use_safetensors=True \
          --prompt_type=unknown \
          --max_seq_len=8192 \
          --use_chat_template=True \
          --base_model=lightblue/suzume-llama-3-8B-multilingual \
          --save_dir='/workspace/save/' \
          --use_auth_token=$HUGGING_FACE_HUB_TOKEN \
          --use_gpu_id=False \
          --allow_upload_to_user_data=False \
          --allow_upload_to_my_data=True \
          --enable_ocr='off' \
          --enable_pdf_ocr='off' \
          --langchain_mode='UserData' \
          --langchain_modes="['LLM', 'UserData', 'MyData']" \
          --user_path=/workspace/user_path \
          --db_type=chroma \
          --visible_h2ogpt_header=False \
          --visible_doc_selection_tab=False \
          --visible_doc_view_tab=False \
          --visible_chat_history_tab=False \
          --visible_expert_tab=False \
          --visible_models_tab=False \
          --visible_system_tab=False \
          --visible_tos_tab=False \
          --visible_hosts_tab=False

# EOF
```

Error:
```
Traceback (most recent call last):
  File "/h2ogpt_conda/envs/h2ogpt/lib/python3.10/site-packages/gradio/queueing.py", line 566, in process_events
    response = await route_utils.call_process_api(
... ... ...
  File "/workspace/src/gpt_langchain.py", line 7985, in get_chain
    assert hasattr(llm, 'chat_conversation')
AssertionError
```

**Comment by pseudotensor** [comment]
There is no `--use_chat_template` parameter and if using chat template, it's automatically default behavior if the model has chat template and you don't pass `--prompt_type` so I don't recommend passing that.

I fixed the particular issue, thanks.

```
python generate.py --use_safetensors=True
--max_seq_len=8192
--base_model=lightblue/suzume-llama-3-8B-multilingual
--use_auth_token=$HUGGING_FACE_HUB_TOKEN
--add_disk_models_to_ui=False
```
works now
