### ISSUE TITLE
EventListener Failure

### ISSUE THREAD

**Issue by jaysunl** [h2oai/h2ogpt#1623]
Hi, every time I run the python generate.py command, it always results in this error:

End auto-detect HF cache text generation models
Begin auto-detect llama.cpp models
End auto-detect llama.cpp models
Traceback (most recent call last):
  File "/lsc/scratch/eda/jliang2/h2ogpt/generate.py", line 20, in <module>
    entrypoint_main()
  File "/lsc/scratch/eda/jliang2/h2ogpt/generate.py", line 16, in entrypoint_main
    H2O_Fire(main)
  File "/lsc/scratch/eda/jliang2/h2ogpt/src/utils.py", line 72, in H2O_Fire
    fire.Fire(component=component, command=args)
  File "/home/wleong01/gpt4all/wai_gpt_pdf_file/gpt_env_gguf/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/wleong01/gpt4all/wai_gpt_pdf_file/gpt_env_gguf/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/wleong01/gpt4all/wai_gpt_pdf_file/gpt_env_gguf/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/lsc/scratch/eda/jliang2/h2ogpt/src/gen.py", line 2277, in main
    go_gradio(**locals().copy())
  File "/lsc/scratch/eda/jliang2/h2ogpt/src/gradio_runner.py", line 1331, in go_gradio
    text_output, text_output2, text_outputs = make_chatbots(output_label0, output_label0_model2,
  File "/lsc/scratch/eda/jliang2/h2ogpt/gradio_utils/prompt_form.py", line 372, in make_chatbots
    rating1.click(ratingfn1, outputs=rating_text_output, _js=review_js1)
TypeError: EventListener._setup.<locals>.event_trigger() got an unexpected keyword argument '_js'

Any reason what may be causing this issue?

**Comment by pseudotensor** [comment]
Looks like a mix-up in your gradio version.  gradio4 should handle that fine.  We detect which gradio you should have.  What does 
```
pip freeze | grep gradio
```
show?

**Comment by jaysunl** [comment]
Just resolved it. There was an issue with some of my packages not being fully installed properly.
