### ISSUE TITLE
AttributeError: 'list' object has no attribute 'shape' when in cpu and langchain mode 

### ISSUE THREAD

**Issue by rzilkha** [h2oai/h2ogpt#168]
I am experiencing this error when running locally on mac M1 

when running  **python3 generate.py --base_model=gptj --score_model=None --langchain_mode=UserData --user_path=user_path**

`langchain_mode UserData has no sources, not making db
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/gradio/routes.py", line 414, in run_predict
    output = await app.get_blocks().process_api(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/gradio/blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/gradio/blocks.py", line 1067, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/gradio/utils.py", line 339, in async_iteration
    return await iterator.__anext__()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/gradio/utils.py", line 332, in __anext__
    return await anyio.to_thread.run_sync(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/gradio/utils.py", line 315, in run_sync_iterator_async
    return next(iterator)
  File "/Users/roeezilkha/h2ogpt/h2ogpt/gradio_runner.py", line 927, in bot
    for output in fun1(*tuple(args_list)):
  File "/Users/roeezilkha/h2ogpt/h2ogpt/generate.py", line 1059, in evaluate
    # if inputs['input_ids'].shape[1] >= max_length_tokenize - 1:
AttributeError: 'list' object has no attribute 'shape'
`

**Comment by pseudotensor** [comment]
Hi, @NidhiMehta hit this issue too.  It seems to be only possible when the CPU  model returns back empty response.

I've added protection now so just that empty response will be returned.  Can you try head of main?

@NidhiMehta any thoughts?
