### ISSUE TITLE
Offline mode is still attempting to fetch from HF

### ISSUE THREAD

**Issue by machinelearning2014** [h2oai/h2ogpt#1702]
I am running in Offline mode with this command:

HF_DATASETS_OFFLINE=1 TRANSFORMERS_OFFLINE=1 python generate.py --base_model=mistral --model_path_llama=mistral-7b-instruct-v0.2.Q2_K.gguf --prompt_type=mistral --cli=True

I have already downloaded the following models manually from HF:

/home/letro/.cache/huggingface/hub/models--hkunlp--instructor-large
/home/letro/.cache/huggingface/hub/models--sentence-transformers--all-MiniLM-L6-v2
/home/letro/h2ogpt/llamacpp_path/mistral-7b-instruct-v0.2.Q2_K.gguf

When I run the command above I get following:

(h2ogpt) letro@jupyterhub-gpu-alpha-bw:~/h2ogpt$ TRANSFORMERS_OFFLINE=1 python generate.py --base_model=mistral --model_path_llama=mistral-7b-instruct-v0.2.Q2_K.gguf --prompt_type=mistral --cli=True
/home/letro/.conda/envs/h2ogpt/lib/python3.10/site-packages/pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
Using Model mistral
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
WARNING:root:USER_AGENT environment variable not set, consider setting it to identify your requests.
Traceback (most recent call last):
  File "/home/letro/h2ogpt/generate.py", line 20, in <module>
    entrypoint_main()
  File "/home/letro/h2ogpt/generate.py", line 16, in entrypoint_main
    H2O_Fire(main)
  File "/home/letro/h2ogpt/src/utils.py", line 75, in H2O_Fire
    fire.Fire(component=component, command=args)
  File "/home/letro/.conda/envs/h2ogpt/lib/python3.10/site-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/letro/.conda/envs/h2ogpt/lib/python3.10/site-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/letro/.conda/envs/h2ogpt/lib/python3.10/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/letro/h2ogpt/src/gen.py", line 2044, in main
    model=get_embedding(use_openai_embedding, hf_embedding_model=hf_embedding_model,
  File "/home/letro/h2ogpt/src/gpt_langchain.py", line 551, in get_embedding
    embedding = HuggingFaceInstructEmbeddings(model_name=hf_embedding_model,
  File "/home/letro/.conda/envs/h2ogpt/lib/python3.10/site-packages/langchain_community/embeddings/huggingface.py", line 164, in __init__
    self.client = INSTRUCTOR(
  File "/home/letro/.conda/envs/h2ogpt/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py", line 87, in __init__
    snapshot_download(model_name_or_path,
  File "/home/letro/.conda/envs/h2ogpt/lib/python3.10/site-packages/sentence_transformers/util.py", line 442, in snapshot_download
    model_info = _api.model_info(repo_id=repo_id, revision=revision, token=token)
  File "/home/letro/.conda/envs/h2ogpt/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/letro/.conda/envs/h2ogpt/lib/python3.10/site-packages/huggingface_hub/hf_api.py", line 2300, in model_info
    r = get_session().get(path, headers=headers, timeout=timeout, params=params)
  File "/home/letro/.conda/envs/h2ogpt/lib/python3.10/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/home/letro/.conda/envs/h2ogpt/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/letro/.conda/envs/h2ogpt/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/letro/.conda/envs/h2ogpt/lib/python3.10/site-packages/huggingface_hub/utils/_http.py", line 77, in send
    raise OfflineModeIsEnabled(
huggingface_hub.errors.OfflineModeIsEnabled: Cannot reach https://huggingface.co/api/models/hkunlp/instructor-large: offline mode is enabled. To disable it, please unset the `HF_HUB_OFFLINE` environment variable.

Question: why is the command still trying to fetch from HF? and why is it not seeing these already in local:
/home/letro/.cache/huggingface/hub/models--hkunlp--instructor-large
/home/letro/.cache/huggingface/hub/models--sentence-transformers--all-MiniLM-L6-v2

**Comment by machinelearning2014** [comment]
I have now downloaded the embedding models at:

/home/letro/.cache/torch/hkunlp/hkunlp_instructor-large
/home/letro/.cache/torch/sentence-transformers/sentence-transformers_all-MiniLM-L6-v2

and running: 
TRANSFORMERS_OFFLINE=1 python generate.py --base_model=mistral-7b-instruct-v0.2.Q2_K.gguf --prompt_type=mistral --max_seq_len=4096 --cli=True

But still it is still does not recognise the models in .cache so attempts to download from https://huggingface.co/api/models/hkunlp/instructor-large, which I want to avoid, as I am in corporate firewall

**Comment by llmwesee** [comment]
I'm also facing the same issue.

**Comment by pseudotensor** [comment]
I see same thing but only for the instructor model and only if using `HF_DATASETS_OFFLINE=1 TRANSFORMERS_OFFLINE=1`.  If I don't set those it's fine.

If one unsets those, then "mistral" model is trying to be obtained from HF, but this is just an error in the command line.  If one is offline one needs to ensure the HF smart attempts are not used by using:

```
python generate.py --base_model=llama --model_path_llama=mistral-7b-instruct-v0.2.Q5_K_M.gguf --prompt_type=mistral --cli=True
```

this works just fine.

This is what is documented here:

https://github.com/h2oai/h2ogpt/blob/main/docs/README_offline.md#tldr

**Comment by pseudotensor** [comment]
As long as you already have the model int he cache, this can still be run:

```
TRANSFORMERS_OFFLINE=1 CONCURRENCY_COUNT=1 python generate.py --base_model=llama --model_path_llama=mistral-7b-instruct-v0.2.Q5_K_M.gguf --prompt_type=mistral --cli=True
```

I only see an issue with instructor and this:
```
TRANSFORMERS_OFFLINE=1 python
Python 3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:45:18) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from InstructorEmbedding import INSTRUCTOR
client = INSTRUCTOR("hkunlp/instructor-large")
```

when I didn't run online first recently.
