### ISSUE TITLE
intfloat_multilingual-e5-large-instruct and file sentence_xlnet_config.json

### ISSUE THREAD

**Issue by juerware** [h2oai/h2ogpt#1774]
I have executed the following command line:
```shell
python generate.py \
    --base_model=mistralai/Mistral-Nemo-Instruct-2407 --use_gpu_id=True --gpu_id=-1 --max_seq_len=8192 \
    --user_path=/opt/myDocuments/all/ --langchain_mode='UserData' --max_quality=True \
    --add_chat_history_to_context=True --keep_sources_in_context=True --enable_ocr=True --enable_doctr=True \
    --answer_with_sources=True --show_link_in_sources=True --append_sources_to_chat=True \
    --hf_embedding_model="intfloat/multilingual-e5-large-instruct" \
    --memory_restriction_level=0 --score_model=None --verbose=True --debug=True \
    --show_examples=True --compile_model=True \
    --share=True
``` 
and I get the following error:
```shell
FileNotFoundError: [Errno 2] No such file or directory: '/root/.cache/torch/sentence_transformers/intfloat_multilingual-e5-large-instruct/sentence_xlnet_config.json'
```

I have used the repository with the last commit at the time I write this issue:
- Commit: 47e14672
- SO: Ubuntu 20.04

As you can see the problem point out that problem is from the embedding model "intfloat/multilingual-e5-large-instruct", with the embedding model ""intfloat/multilingual-e5-large" I did not get that kind of error.

Thanks in advance for help.

**Comment by llmwesee** [comment]
I'm also facing the same thing when running docker offline

**Comment by pseudotensor** [comment]
If I'm online, I see the same error.

```
(h2ogpt) jon@pseudotensor:~/h2ogpt$ python generate.py     --base_model=llama --use_gpu_id=True --gpu_id=-1 --max_seq_len=8192     --user_path=user_path --langchain_mode='UserData' --max_quality=True     --add_chat_history_to_context=True --keep_sources_in_context=True --enable_ocr=True --enable_doctr=True     --answer_with_sources=True --show_link_in_sources=True --append_sources_to_chat=True     --hf_embedding_model="intfloat/multilingual-e5-large-instruct"     --memory_restriction_level=0 --score_model=None --verbose=True --debug=True     --show_examples=True --compile_model=True     --share=True
```
gives:
```
Command: generate.py --base_model=llama --use_gpu_id=True --gpu_id=-1 --max_seq_len=8192 --user_path=user_path --langchain_mode=UserData --max_quality=True --add_chat_history_to_context=True --keep_sources_in_context=True --enable_ocr=True --enable_doctr=True --answer_with_sources=True --show_link_in_sources=True --append_sources_to_chat=True --hf_embedding_model=intfloat/multilingual-e5-large-instruct --memory_restriction_level=0 --score_model=None --verbose=True --debug=True --show_examples=True --compile_model=True --share=True
Hash: 47e14672da4fc926aef7eeccd09d1119f112db3c
WARNING:langchain_community.utils.user_agent:USER_AGENT environment variable not set, consider setting it to identify your requests.
/home/jon/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/langchain_core/_api/deprecation.py:139: LangChainDeprecationWarning: The class `HuggingFaceEmbeddings` was deprecated in LangChain 0.2.2 and will be removed in 0.3.0. An updated version of the class exists in the langchain-huggingface package and should be used instead. To use it run `pip install -U langchain-huggingface` and import as `from langchain_huggingface import HuggingFaceEmbeddings`.
  warn_deprecated(
/home/jon/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/huggingface_hub/utils/_deprecation.py:131: FutureWarning: 'cached_download' (from 'huggingface_hub.file_download') is deprecated and will be removed from version '0.26'. Use `hf_hub_download` instead.
  warnings.warn(warning_message, FutureWarning)
.gitattributes: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.57k/1.57k [00:00<00:00, 4.43MB/s]
1_Pooling/config.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 271/271 [00:00<00:00, 3.06MB/s]
README.md: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 140k/140k [00:00<00:00, 40.4MB/s]
config.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 690/690 [00:00<00:00, 1.72MB/s]
config_sentence_transformers.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 128/128 [00:00<00:00, 368kB/s]
model.safetensors: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉| 1.12G/1.12G [00:11<00:00, 93.5MB/s]
sentencepiece.bpe.model: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5.07M/5.07M [00:00<00:00, 27.0MB/s]
special_tokens_map.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 964/964 [00:00<00:00, 2.79MB/s]
tokenizer.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 17.1M/17.1M [00:00<00:00, 37.0MB/s]
tokenizer_config.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.18k/1.18k [00:00<00:00, 3.37MB/s]
modules.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 349/349 [00:00<00:00, 886kB/s]
WARNING:sentence_transformers.SentenceTransformer:You try to use a model that was created with version 2.4.0.dev0, however, your version is 2.2.2. This might cause unexpected behavior or errors. In that case, try to update to the latest version.



Traceback (most recent call last):
  File "/home/jon/h2ogpt/generate.py", line 20, in <module>
    entrypoint_main()
  File "/home/jon/h2ogpt/generate.py", line 16, in entrypoint_main
    H2O_Fire(main)
  File "/home/jon/h2ogpt/src/utils.py", line 75, in H2O_Fire
    fire.Fire(component=component, command=args)
  File "/home/jon/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/jon/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/jon/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/jon/h2ogpt/src/gen.py", line 1996, in main
    model=get_embedding(use_openai_embedding, hf_embedding_model=hf_embedding_model,
  File "/home/jon/h2ogpt/src/gpt_langchain.py", line 558, in get_embedding
    embedding = HuggingFaceEmbeddings(model_name=hf_embedding_model, model_kwargs=model_kwargs)
  File "/home/jon/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/langchain_core/_api/deprecation.py", line 203, in warn_if_direct_instance
    return wrapped(self, *args, **kwargs)
  File "/home/jon/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/langchain_community/embeddings/huggingface.py", line 79, in __init__
    self.client = sentence_transformers.SentenceTransformer(
  File "/home/jon/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py", line 95, in __init__
    modules = self._load_sbert_model(model_path)
  File "/home/jon/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py", line 840, in _load_sbert_model
    module = module_class.load(os.path.join(model_path, module_config['path']))
  File "/home/jon/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/sentence_transformers/models/Transformer.py", line 135, in load
    with open(sbert_config_path) as fIn:
FileNotFoundError: [Errno 2] No such file or directory: '/home/jon/.cache/torch/sentence_transformers/intfloat_multilingual-e5-large-instruct/sentence_xlnet_config.json'
(h2ogpt) jon@pseudotensor:~/h2ogpt$ 
```

I'm guessing sentence-transforemrs==2.2.2 is too old for this model.  However, that version is required for langchain's HF embedding wrapper code to work.

Otherwise I get an error from sentence transformers complaining about how Langchain is misusing it:

```
Command: generate.py --base_model=llama --use_gpu_id=True --gpu_id=-1 --max_seq_len=8192 --user_path=user_path --langchain_mode=UserData --max_quality=True --add_chat_history_to_context=True --keep_sources_in_context=True --enable_ocr=True --enable_doctr=True --answer_with_sources=True --show_link_in_sources=True --append_sources_to_chat=True --hf_embedding_model=intfloat/multilingual-e5-large-instruct --memory_restriction_level=0 --score_model=None --verbose=True --debug=True --show_examples=True --compile_model=True --share=True
Hash: 47e14672da4fc926aef7eeccd09d1119f112db3c
WARNING:langchain_community.utils.user_agent:USER_AGENT environment variable not set, consider setting it to identify your requests.
/home/jon/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/langchain_core/_api/deprecation.py:139: LangChainDeprecationWarning: The class `HuggingFaceEmbeddings` was deprecated in LangChain 0.2.2 and will be removed in 0.3.0. An updated version of the class exists in the langchain-huggingface package and should be used instead. To use it run `pip install -U langchain-huggingface` and import as `from langchain_huggingface import HuggingFaceEmbeddings`.
  warn_deprecated(
modules.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 349/349 [00:00<00:00, 603kB/s]
config_sentence_transformers.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 128/128 [00:00<00:00, 387kB/s]
README.md: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 140k/140k [00:00<00:00, 6.15MB/s]
config.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 690/690 [00:00<00:00, 2.11MB/s]
model.safetensors: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉| 1.12G/1.12G [00:10<00:00, 103MB/s]
tokenizer_config.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.18k/1.18k [00:00<00:00, 3.64MB/s]
sentencepiece.bpe.model: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5.07M/5.07M [00:00<00:00, 5.64MB/s]
tokenizer.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 17.1M/17.1M [00:01<00:00, 14.5MB/s]
special_tokens_map.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 964/964 [00:00<00:00, 2.83MB/s]
1_Pooling/config.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 271/271 [00:00<00:00, 2.50MB/s]
Prep: persist_directory=db_dir_UserData exists, user_path=user_path passed, adding any changed or new documents
DO Loading db: UserData
Traceback (most recent call last):
  File "/home/jon/h2ogpt/generate.py", line 20, in <module>
    entrypoint_main()
  File "/home/jon/h2ogpt/generate.py", line 16, in entrypoint_main
    H2O_Fire(main)
  File "/home/jon/h2ogpt/src/utils.py", line 75, in H2O_Fire
    fire.Fire(component=component, command=args)
  File "/home/jon/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/jon/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/jon/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/jon/h2ogpt/src/gen.py", line 2121, in main
    db = prep_langchain(persist_directory1,
  File "/home/jon/h2ogpt/src/gpt_langchain.py", line 5701, in prep_langchain
    db, num_new_sources, new_sources_metadata = make_db(**langchain_kwargs)
  File "/home/jon/h2ogpt/src/gpt_langchain.py", line 5962, in make_db
    return _make_db(**langchain_kwargs)
  File "/home/jon/h2ogpt/src/gpt_langchain.py", line 6187, in _make_db
    get_existing_db(db, persist_directory, load_db_if_exists, db_type,
  File "/home/jon/h2ogpt/src/gpt_langchain.py", line 5858, in get_existing_db
    embedding = get_embedding(use_openai_embedding, hf_embedding_model=hf_embedding_model,
  File "/home/jon/h2ogpt/src/gpt_langchain.py", line 553, in get_embedding
    embedding = HuggingFaceInstructEmbeddings(model_name=hf_embedding_model,
  File "/home/jon/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/langchain_community/embeddings/huggingface.py", line 167, in __init__
    self.client = INSTRUCTOR(
  File "/home/jon/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py", line 287, in __init__
    modules = self._load_sbert_model(
TypeError: INSTRUCTOR._load_sbert_model() got an unexpected keyword argument 'token'

```

**Comment by pseudotensor** [comment]
However, if you have no databases with instructor models, you can do:
```
pip install sentence-transformers --upgrade
```

And it'll work fine.

**Comment by pseudotensor** [comment]
To be clear, all other RAG platforms have the same issues with sentence_transformers being broken still.


https://github.com/UKPLab/sentence-transformers/issues/2474

Looks like instructor-large is no longer a good default choice.

**Comment by juerware** [comment]
Ok, thanks
