### ISSUE TITLE
TypeError: INSTRUCTOR._load_sbert_model() got an unexpected keyword argument 'token'

### ISSUE THREAD

**Issue by juerware** [h2oai/h2ogpt#1787]
This is the command line lauched:
```shell
python generate.py \
    --base_model=h2oai/h2ogpt-4096-llama2-7b-chat --prompt_type=llama2 \
    --use_gpu_id=True --gpu_id=-1 --max_seq_len=8192 \
    --user_path=/opt/myDocuments/arsys.es/all/ --langchain_mode='UserData' --max_quality=True \
    --add_chat_history_to_context=True --keep_sources_in_context=True --enable_ocr=True --enable_doctr=True \
    --answer_with_sources=True --show_link_in_sources=True --append_sources_to_chat=True \
    --hf_embedding_model="hkunlp/instructor-base" \
    --memory_restriction_level=0 --score_model=None --verbose=True --debug=True
```
---
This is the error found:
```shell
Traceback (most recent call last):
  File "/root/REPOSITORIES/aramirez/void_h2ogtp/generate.py", line 20, in <module>
    entrypoint_main()
  File "/root/REPOSITORIES/aramirez/void_h2ogtp/generate.py", line 16, in entrypoint_main
    H2O_Fire(main)
  File "/root/REPOSITORIES/aramirez/void_h2ogtp/src/utils.py", line 75, in H2O_Fire
    fire.Fire(component=component, command=args)
  File "/root/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/root/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/root/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/root/REPOSITORIES/aramirez/void_h2ogtp/src/gen.py", line 2015, in main
    model=get_embedding(use_openai_embedding, hf_embedding_model=hf_embedding_model,
  File "/root/REPOSITORIES/aramirez/void_h2ogtp/src/gpt_langchain.py", line 556, in get_embedding
    embedding = HuggingFaceInstructEmbeddings(model_name=hf_embedding_model,
  File "/root/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/langchain_community/embeddings/huggingface.py", line 167, in __init__
    self.client = INSTRUCTOR(
  File "/root/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py", line 287, in __init__
    modules = self._load_sbert_model(
TypeError: INSTRUCTOR._load_sbert_model() got an unexpected keyword argument 'token'
```
---
System:
- SO: Ubuntu 22.04 LTS utterly updated.
- Commit: 7435b4bc (the last one at the moment this issue is written)
- Environment utterly updated and clean after execution of script ```bash docs/linux_install_full.sh```
---
Observations:
- This only happens with embedding models based on BERT
- Embedding models as "intfloat/multilingual-e5-small" does not report any problem.
---
Thanks for everything.

**Comment by pseudotensor** [comment]
did you use fresh env?   new packages are required for instructor

**Comment by pseudotensor** [comment]
677bf0817d3e342ffc32a31a94cf63cc05096660

**Comment by pseudotensor** [comment]
Building new image with above fix to see if order helps.  I saw in jenkins that earlier requirements.txt file triggered instructorembedding install, so needs to be early and not as late as langchain one.

**Comment by pseudotensor** [comment]
Seems to work.  Thanks for reporting!

**Comment by juerware** [comment]
It´s working right now, thanks.
