### ISSUE TITLE
Bug while changing the model

### ISSUE THREAD

**Issue by lelapin123** [h2oai/h2ogpt#185]
Traceback (most recent call last):
  File "/home/lelapin123/anaconda3/envs/h2oa/lib/python3.10/site-packages/gradio/routes.py", line 414, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/lelapin123/anaconda3/envs/h2oa/lib/python3.10/site-packages/gradio/blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "/home/lelapin123/anaconda3/envs/h2oa/lib/python3.10/site-packages/gradio/blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  
File "/home/lelapin123/anaconda3/envs/h2oa/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/lelapin123/anaconda3/envs/h2oa/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/lelapin123/anaconda3/envs/h2oa/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/lelapin123/work/h2oa/h2ogpt/gradio_runner.py", line 1246, in load_model
    model1, tokenizer1, device1 = get_model(**get_kwargs(get_model, all_kwargs1))
  File "/home/lelapin123/work/h2oa/h2ogpt/utils.py", line 800, in get_kwargs
    assert not missing_kwargs, "Missing %s" % missing_kwargs
AssertionError: Missing ['reward_type']

**Comment by pseudotensor** [comment]
Thanks, sounds like a plain bug, should be easy to fix.  Need more testing of model selection and model comparison stuff.

**Comment by pseudotensor** [comment]
Fixed change.  Started without any model:

```

```

Then added distilgpt2 and (in its pretraining mode) used it fine now, before failed as @lelapin123 said:

![image](https://github.com/h2oai/h2ogpt/assets/2249614/ac8fb937-e737-4c87-9f28-837236016c7d)

**Comment by pseudotensor** [comment]
And compare mode works fine:

![image](https://github.com/h2oai/h2ogpt/assets/2249614/7840f729-111d-4788-b181-09a16c0eac61)

**Comment by pseudotensor** [comment]
The placement of buttons is off for adding new model/LORA name, will fix.

**Comment by lelapin123** [comment]
So now i am able to change the model, it is just that if i change the model again.
Lets say from from Model: h2oai/h2ogpt-oig-oasst1-512-6_9b to h2oai/h2ogpt-oasst1-512-12b
then it return a out of memory error
I guess the model should also be released from the memory
