### ISSUE TITLE
pydantic.errors.PydanticUserError: A non-annotated attribute was detected: `allow_map_1 = True`

### ISSUE THREAD

**Issue by ricvolpi** [h2oai/h2ogpt#1898]
I have installed packages in `requirements.txt` and `reqs_optional/requirements_optional_gpu_only.txt`.

When I run `python src/make_db.py --download_some=True`, I get

```unix
Traceback (most recent call last):
  File "/home/jupyter/Desktop/h2ogpt/src/make_db.py", line 9, in <module>
    from gpt_langchain import path_to_docs, get_some_dbs_from_hf, all_db_zips, some_db_zips, create_or_update_db, \
  File "/home/jupyter/Desktop/h2ogpt/src/gpt_langchain.py", line 97, in <module>
    from h2o_serpapi import H2OSerpAPIWrapper
  File "/home/jupyter/Desktop/h2ogpt/src/h2o_serpapi.py", line 8, in <module>
    from utils_langchain import _chunk_sources, add_parser, _add_meta
  File "/home/jupyter/Desktop/h2ogpt/src/utils_langchain.py", line 396, in <module>
    class H2OMapReduceDocumentsChain(MapReduceDocumentsChain):
  File "/home/jupyter/conda/envs/h2o/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py", line 115, in __new__
    private_attributes = inspect_namespace(
  File "/home/jupyter/conda/envs/h2o/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py", line 428, in inspect_namespace
    raise PydanticUserError(
pydantic.errors.PydanticUserError: A non-annotated attribute was detected: `allow_map_1 = True`. All model fields require a type annotation; if `allow_map_1` is not meant to be a field, you may be able to resolve this error by annotating it as a `ClassVar` or updating `model_config['ignored_types']`.
```

Am I missing any dependency?

OS: Debian GNU/Linux 11.
Python version: 3.10
Packages:

```unix
absl-py                                  2.1.0
accelerate                               1.1.1
aiofiles                                 23.2.1
aiohappyeyeballs                         2.4.3
aiohttp                                  3.10.10
aiosignal                                1.3.1
annotated-types                          0.7.0
anthropic                                0.39.0
anyio                                    4.6.2.post1
appdirs                                  1.4.4
APScheduler                              3.10.4
asgiref                                  3.8.1
async-timeout                            4.0.3
attrs                                    24.2.0
auto_gptq                                0.7.1
autoawq                                  0.2.6
autoawq_kernels                          0.0.7
backoff                                  2.2.1
bcrypt                                   4.2.0
beautifulsoup4                           4.12.3
bioc                                     2.1
bitsandbytes                             0.44.1
blis                                     0.7.11
boto3                                    1.35.58
botocore                                 1.35.58
build                                    1.2.2.post1
cachetools                               5.5.0
catalogue                                2.0.10
certifi                                  2024.8.30
charset-normalizer                       3.4.0
chroma-hnswlib                           0.7.6
chromadb                                 0.5.18
click                                    8.1.7
cloudpathlib                             0.20.0
colorama                                 0.4.6
coloredlogs                              15.0.1
confection                               0.1.5
contourpy                                1.3.0
cycler                                   0.12.1
cymem                                    2.0.8
dataclasses-json                         0.6.7
datasets                                 3.1.0
defusedxml                               0.7.1
Deprecated                               1.2.14
dill                                     0.3.8
distro                                   1.9.0
docopt                                   0.6.2
docutils                                 0.21.2
durationpy                               0.9
einops                                   0.8.0
et_xmlfile                               2.0.0
evaluate                                 0.4.3
exceptiongroup                           1.2.2
execnet                                  2.1.1
exllama                                  0.0.18+cu121
faiss-gpu                                1.7.2
fastapi                                  0.115.4
fastapi-utils                            0.8.0
ffmpy                                    0.4.0
filelock                                 3.16.1
fire                                     0.7.0
flatbuffers                              24.3.25
fonttools                                4.54.1
frozenlist                               1.5.0
fsspec                                   2024.9.0
gekko                                    1.2.1
google-ai-generativelanguage             0.6.10
google-api-core                          2.23.0
google-api-python-client                 2.151.0
google-auth                              2.36.0
google-auth-httplib2                     0.2.0
google-generativeai                      0.8.3
googleapis-common-protos                 1.65.0
gradio                                   4.44.0
gradio_client                            1.3.0
greenlet                                 3.1.1
grpcio                                   1.67.1
grpcio-status                            1.67.1
gunicorn                                 23.0.0
h11                                      0.14.0
hf_transfer                              0.1.8
httpcore                                 1.0.6
httplib2                                 0.22.0
httptools                                0.6.4
httpx                                    0.27.2
httpx-sse                                0.4.0
huggingface-hub                          0.26.2
humanfriendly                            10.0
idna                                     3.10
importlib_metadata                       8.5.0
importlib_resources                      6.4.5
iniconfig                                2.0.0
InstructorEmbedding                      1.0.1
intervaltree                             3.1.0
Jinja2                                   3.1.4
jiter                                    0.7.0
jmespath                                 1.0.1
joblib                                   1.4.2
json_repair                              0.30.1
jsonlines                                4.0.0
jsonpatch                                1.33
jsonpointer                              3.0.0
jsonschema                               4.23.0
jsonschema-specifications                2024.10.1
kiwisolver                               1.4.7
kubernetes                               31.0.0
langchain                                0.3.4
langchain-anthropic                      0.2.4
langchain-chroma                         0.1.4
langchain-community                      0.3.3
langchain-core                           0.3.13
langchain-experimental                   0.3.3
langchain-google-genai                   2.0.4
langchain-mistralai                      0.2.0
langchain-ollama                         0.2.0
langchain-text-splitters                 0.3.0
langcodes                                3.4.1
langsmith                                0.1.137
language_data                            1.2.0
limits                                   3.13.0
lm-dataformat                            0.0.20
loralib                                  0.1.2
lxml                                     5.3.0
marisa-trie                              1.2.1
Markdown                                 3.7
markdown-it-py                           3.0.0
MarkupSafe                               2.1.5
marshmallow                              3.23.1
matplotlib                               3.9.2
mdurl                                    0.1.2
mmh3                                     5.0.1
monotonic                                1.6
mpmath                                   1.3.0
multidict                                6.1.0
multiprocess                             0.70.16
murmurhash                               1.0.10
mypy-extensions                          1.0.0
networkx                                 3.4.2
nltk                                     3.9.1
numpy                                    1.26.4
nvidia-cublas-cu12                       12.1.3.1
nvidia-cuda-cupti-cu12                   12.1.105
nvidia-cuda-nvrtc-cu12                   12.1.105
nvidia-cuda-runtime-cu12                 12.1.105
nvidia-cudnn-cu12                        8.9.2.26
nvidia-cufft-cu12                        11.0.2.54
nvidia-curand-cu12                       10.3.2.106
nvidia-cusolver-cu12                     11.4.5.107
nvidia-cusparse-cu12                     12.1.0.106
nvidia-nccl-cu12                         2.20.5
nvidia-nvjitlink-cu12                    12.6.77
nvidia-nvtx-cu12                         12.1.105
oauthlib                                 3.2.2
ollama                                   0.3.3
onnxruntime                              1.20.0
onnxruntime-gpu                          1.15.0
openai                                   1.54.3
openpyxl                                 3.1.5
opentelemetry-api                        1.28.1
opentelemetry-exporter-otlp-proto-common 1.28.1
opentelemetry-exporter-otlp-proto-grpc   1.28.1
opentelemetry-instrumentation            0.49b1
opentelemetry-instrumentation-asgi       0.49b1
opentelemetry-instrumentation-fastapi    0.49b1
opentelemetry-proto                      1.28.1
opentelemetry-sdk                        1.28.1
opentelemetry-semantic-conventions       0.49b1
opentelemetry-util-http                  0.49b1
orjson                                   3.10.11
overrides                                7.7.0
packaging                                24.2
pandas                                   2.2.3
peft                                     0.13.2
pillow                                   10.4.0
pip                                      24.3.1
pluggy                                   1.5.0
portalocker                              2.10.1
posthog                                  3.7.0
preshed                                  3.0.9
propcache                                0.2.0
proto-plus                               1.25.0
protobuf                                 5.28.3
psutil                                   5.9.8
pyarrow                                  18.0.0
pyasn1                                   0.6.1
pyasn1_modules                           0.4.1
pydantic                                 2.9.2
pydantic_core                            2.23.4
pydantic-settings                        2.6.1
pydub                                    0.25.1
pyexiv2                                  2.15.3
Pygments                                 2.18.0
pynvml                                   11.5.3
pypandoc_binary                          1.14
pyparsing                                3.2.0
pyphen                                   0.17.0
PyPika                                   0.48.9
pyproject_hooks                          1.2.0
pytest                                   8.3.3
pytest-xdist                             3.6.1
python-dateutil                          2.9.0.post0
python-dotenv                            1.0.1
python-multipart                         0.0.17
pytz                                     2024.2
PyYAML                                   6.0.2
referencing                              0.35.1
regex                                    2024.11.6
requests                                 2.32.3
requests-oauthlib                        2.0.0
requests-toolbelt                        1.0.0
rich                                     13.9.4
rouge                                    1.0.1
rouge_score                              0.1.2
rpds-py                                  0.21.0
rsa                                      4.9
ruff                                     0.7.3
s3transfer                               0.10.3
sacrebleu                                2.4.3
safetensors                              0.4.5
scikit-learn                             1.5.2
scipy                                    1.14.1
semantic-version                         2.10.0
sentence-transformers                    3.3.0
sentence-transformers-old                2.2.2
sentencepiece                            0.2.0
setuptools                               75.3.0
shellingham                              1.5.4
six                                      1.16.0
slowapi                                  0.1.9
smart-open                               7.0.5
sniffio                                  1.3.1
sortedcontainers                         2.4.0
soupsieve                                2.6
spacy                                    3.7.5
spacy-legacy                             3.0.12
spacy-loggers                            1.0.5
SQLAlchemy                               2.0.35
srsly                                    2.4.8
sse-starlette                            2.1.3
starlette                                0.41.2
sympy                                    1.13.3
tabulate                                 0.9.0
tenacity                                 9.0.0
termcolor                                2.5.0
text-generation                          0.7.0
textstat                                 0.7.4
thinc                                    8.2.5
threadpoolctl                            3.5.0
tiktoken                                 0.8.0
tokenizers                               0.20.3
tomli                                    2.1.0
tomlkit                                  0.12.0
torch                                    2.3.1
torchvision                              0.18.1
tqdm                                     4.67.0
transformers                             4.46.2
triton                                   2.3.1
typer                                    0.13.0
typing_extensions                        4.12.2
typing-inspect                           0.9.0
tzdata                                   2024.2
tzlocal                                  5.2
ujson                                    5.10.0
uritemplate                              4.1.1
urllib3                                  2.2.3
uvicorn                                  0.32.0
uvloop                                   0.21.0
wasabi                                   1.1.3
watchfiles                               0.24.0
weasel                                   0.4.1
websocket-client                         1.8.0
websockets                               12.0
wheel                                    0.45.0
wrapt                                    1.16.0
xxhash                                   3.5.0
yarl                                     1.17.1
zipp                                     3.21.0
zstandard                                0.23.0
```

**Comment by ricvolpi** [comment]
My bad, just found proper install instructions [here](https://github.com/h2oai/h2ogpt/blob/main/docs/linux_install.sh).
