### ISSUE TITLE
ModuleNotFoundError: No module named 'langchain_openai.chat_models'; 'langchain_openai' is not a package

### ISSUE THREAD

**Issue by ricvolpi** [h2oai/h2ogpt#1899]
Running `python src/make_db.py --download_some=True` I get the following error

```unix
Traceback (most recent call last):
  File "/home/jupyter/Desktop/h2ogpt/src/make_db.py", line 9, in <module>
    from gpt_langchain import path_to_docs, get_some_dbs_from_hf, all_db_zips, some_db_zips, create_or_update_db, \
  File "/home/jupyter/Desktop/h2ogpt/src/gpt_langchain.py", line 2077, in <module>
    from langchain_together import ChatTogether
  File "/home/jupyter/conda/envs/h2ogpt/lib/python3.10/site-packages/langchain_together/__init__.py", line 1, in <module>
    from langchain_together.chat_models import ChatTogether
  File "/home/jupyter/conda/envs/h2ogpt/lib/python3.10/site-packages/langchain_together/chat_models.py", line 18, in <module>
    from langchain_openai.chat_models.base import BaseChatOpenAI
ModuleNotFoundError: No module named 'langchain_openai.chat_models'; 'langchain_openai' is not a package
```

the reason is the langchain_openai wrapper `src/langchain_openai.py` (see a similar issue [here](https://github.com/langchain-ai/langchain/issues/2079#issuecomment-1487416187)). I fixed it by renaming `src/langchain_openai.py` into `src/langchain_openai_wrapper.py` and updating related imports. Things work now, but maybe we can think about a cleaner fix for this? I wonder if the other wrappers cause other issues here and there.

OS Linux / Debian 11
Python 10.3

**Comment by pseudotensor** [comment]
It's already been renamed last week to langchain_openai_local.py .  You must be out of date on repo. Thanks!
