### ISSUE TITLE
RuntimeError: expected scalar type Half but found Float

### ISSUE THREAD

**Issue by pseudotensor** [h2oai/h2ogpt#268]
```
tests/test_client_calls.py::test_client_chat_stream_langchain_steps[100-2048] Using Model h2oai/h2ogpt-oig-oasst1-512-6_9b
```

```
Traceback (most recent call last):
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/gradio/routes.py", line 414, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/gradio/blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/gradio/blocks.py", line 1067, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/gradio/utils.py", line 339, in async_iteration
    return await iterator.__anext__()
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/gradio/utils.py", line 332, in __anext__
    return await anyio.to_thread.run_sync(
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/gradio/utils.py", line 315, in run_sync_iterator_async
    return next(iterator)
  File "/home/jon/h2ogpt/gradio_runner.py", line 1061, in bot
    for output_fun in fun1(*tuple(args_list)):
  File "/home/jon/h2ogpt/generate.py", line 1085, in evaluate
    for r in run_qa_db(query=query,
  File "/home/jon/h2ogpt/gpt_langchain.py", line 1384, in _run_qa_db
    raise thread.exc
  File "/home/jon/h2ogpt/utils.py", line 313, in run
    self._return = self._target(*self._args, **self._kwargs)
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/langchain/chains/base.py", line 145, in __call__
    raise e
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/langchain/chains/base.py", line 139, in __call__
    self._call(inputs, run_manager=run_manager)
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/langchain/chains/combine_documents/base.py", line 84, in _call
    output, extra_return_dict = self.combine_docs(
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/langchain/chains/combine_documents/stuff.py", line 87, in combine_docs
    return self.llm_chain.predict(callbacks=callbacks, **inputs), {}
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/langchain/chains/llm.py", line 213, in predict
    return self(kwargs, callbacks=callbacks)[self.output_key]
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/langchain/chains/base.py", line 145, in __call__
    raise e
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/langchain/chains/base.py", line 139, in __call__
    self._call(inputs, run_manager=run_manager)
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/langchain/chains/llm.py", line 69, in _call
    response = self.generate([inputs], run_manager=run_manager)
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/langchain/chains/llm.py", line 79, in generate
    return self.llm.generate_prompt(
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/langchain/llms/base.py", line 135, in generate_prompt
    return self.generate(prompt_strings, stop=stop, callbacks=callbacks)
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/langchain/llms/base.py", line 192, in generate
    raise e
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/langchain/llms/base.py", line 186, in generate
    self._generate(prompts, stop=stop, run_manager=run_manager)
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/langchain/llms/base.py", line 449, in _generate
    self._call(prompt, stop=stop, run_manager=run_manager)
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/langchain/llms/huggingface_pipeline.py", line 168, in _call
    response = self.pipeline(prompt)
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/transformers/pipelines/text_generation.py", line 201, in __call__
    return super().__call__(text_inputs, **kwargs)
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/transformers/pipelines/base.py", line 1118, in __call__
    return self.run_single(inputs, preprocess_params, forward_params, postprocess_params)
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/transformers/pipelines/base.py", line 1125, in run_single
    model_outputs = self.forward(model_inputs, **forward_params)
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/transformers/pipelines/base.py", line 1024, in forward
    model_outputs = self._forward(model_inputs, **forward_params)
  File "/home/jon/h2ogpt/h2oai_pipeline.py", line 129, in _forward
    return self.__forward(model_inputs, **generate_kwargs)
  File "/home/jon/h2ogpt/h2oai_pipeline.py", line 165, in __forward
    generated_sequence = self.model.generate(input_ids=input_ids, attention_mask=attention_mask, **generate_kwargs)
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/transformers/generation/utils.py", line 1568, in generate
    return self.sample(
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/transformers/generation/utils.py", line 2615, in sample
    outputs = self(
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/transformers/models/gpt_neox/modeling_gpt_neox.py", line 673, in forward
    outputs = self.gpt_neox(
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/transformers/models/gpt_neox/modeling_gpt_neox.py", line 564, in forward
    outputs = layer(
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/transformers/models/gpt_neox/modeling_gpt_neox.py", line 331, in forward
    attention_layer_outputs = self.attention(
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/transformers/models/gpt_neox/modeling_gpt_neox.py", line 163, in forward
    attn_output, attn_weights = self._attn(query, key, value, attention_mask, head_mask)
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/transformers/models/gpt_neox/modeling_gpt_neox.py", line 217, in _attn
    attn_scores = torch.baddbmm(
RuntimeError: expected scalar type Half but found Float
FAILED

```

**Comment by pseudotensor** [comment]
autocast helps, but if OOM can still hit
