### ISSUE TITLE
E   ImportError: cannot import name 'DEFAULT_CIPHERS' from 'urllib3.util.ssl_' 

### ISSUE THREAD

**Issue by pseudotensor** [h2oai/h2ogpt#282]
```
for fil in requirements.txt reqs_optional/requirements_optional_langchain.txt reqs_optional/requirements_optional_gpt4all.txt reqs_optional/requirements_optional_langchain.gpllike.txt ; do pip install -r $fil ; done
```
then for client:
```
cd client
make setup
make lint
make build
# install (choose version if multiple builds in dist directory)
pip install dist/h2ogpt_client-*-py3-none-any.whl
# test
cd ..
pytest -s -v --forked client
```

```
E   ImportError: cannot import name 'DEFAULT_CIPHERS' from 'urllib3.util.ssl_' (/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/urllib3/util/ssl_.py)
```

Seems order matters, like installing again requirements.txt helps.  Can you figure out please?

Once pip install client wheel, basic `generate.py` calls fail:

```
(env) arno@rippa:/nfs4/llm/h2ogpt(main)$ python generate.py --base_model=eugenepentland/Minotaur-13b-Landmark --trust_remote_code=True
Traceback (most recent call last):
  File "/nfs4/llm/h2ogpt/generate.py", line 37, in <module>
    from accelerate import init_empty_weights, infer_auto_device_map
  File "/nfs4/llm/h2o-llm/env/lib/python3.10/site-packages/accelerate/__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "/nfs4/llm/h2o-llm/env/lib/python3.10/site-packages/accelerate/accelerator.py", line 33, in <module>
    from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
  File "/nfs4/llm/h2o-llm/env/lib/python3.10/site-packages/accelerate/checkpointing.py", line 24, in <module>
    from .utils import (
  File "/nfs4/llm/h2o-llm/env/lib/python3.10/site-packages/accelerate/utils/__init__.py", line 109, in <module>
    from .launch import (
  File "/nfs4/llm/h2o-llm/env/lib/python3.10/site-packages/accelerate/utils/launch.py", line 23, in <module>
    from ..commands.config.config_args import SageMakerConfig
  File "/nfs4/llm/h2o-llm/env/lib/python3.10/site-packages/accelerate/commands/config/__init__.py", line 19, in <module>
    from .config import config_command_parser
  File "/nfs4/llm/h2o-llm/env/lib/python3.10/site-packages/accelerate/commands/config/config.py", line 25, in <module>
    from .sagemaker import get_sagemaker_input
  File "/nfs4/llm/h2o-llm/env/lib/python3.10/site-packages/accelerate/commands/config/sagemaker.py", line 35, in <module>
    import boto3  # noqa: F401
  File "/nfs4/llm/h2o-llm/env/lib/python3.10/site-packages/boto3/__init__.py", line 17, in <module>
    from boto3.session import Session
  File "/nfs4/llm/h2o-llm/env/lib/python3.10/site-packages/boto3/session.py", line 17, in <module>
    import botocore.session
  File "/nfs4/llm/h2o-llm/env/lib/python3.10/site-packages/botocore/session.py", line 26, in <module>
    import botocore.client
  File "/nfs4/llm/h2o-llm/env/lib/python3.10/site-packages/botocore/client.py", line 15, in <module>
    from botocore import waiter, xform_name
  File "/nfs4/llm/h2o-llm/env/lib/python3.10/site-packages/botocore/waiter.py", line 18, in <module>
    from botocore.docs.docstring import WaiterDocstring
  File "/nfs4/llm/h2o-llm/env/lib/python3.10/site-packages/botocore/docs/__init__.py", line 15, in <module>
    from botocore.docs.service import ServiceDocumenter
  File "/nfs4/llm/h2o-llm/env/lib/python3.10/site-packages/botocore/docs/service.py", line 14, in <module>
    from botocore.docs.client import ClientDocumenter, ClientExceptionsDocumenter
  File "/nfs4/llm/h2o-llm/env/lib/python3.10/site-packages/botocore/docs/client.py", line 17, in <module>
    from botocore.docs.example import ResponseExampleDocumenter
  File "/nfs4/llm/h2o-llm/env/lib/python3.10/site-packages/botocore/docs/example.py", line 13, in <module>
    from botocore.docs.shape import ShapeDocumenter
  File "/nfs4/llm/h2o-llm/env/lib/python3.10/site-packages/botocore/docs/shape.py", line 19, in <module>
    from botocore.utils import is_json_value_header
  File "/nfs4/llm/h2o-llm/env/lib/python3.10/site-packages/botocore/utils.py", line 37, in <module>
    import botocore.httpsession
  File "/nfs4/llm/h2o-llm/env/lib/python3.10/site-packages/botocore/httpsession.py", line 22, in <module>
    from urllib3.util.ssl_ import (
ImportError: cannot import name 'DEFAULT_CIPHERS' from 'urllib3.util.ssl_' (/nfs4/llm/h2o-llm/env/lib/python3.10/site-packages/urllib3/util/ssl_.py)
```

This is only fixed if I go back and repeat reqs again:
```
for fil in requirements.txt reqs_optional/requirements_optional_langchain.txt reqs_optional/requirements_optional_gpt4all.txt reqs_optional/requirements_optional_langchain.gpllike.txt ; do pip install -r $fil ; done
```

**Comment by this** [comment]
@pseudotensor I couldn't reproduce this error in a fresh Python venv.
```sh
virtualenv -p python3.10 venv
source venv/bin/activate
for fil in requirements.txt reqs_optional/requirements_optional_langchain.txt reqs_optional/requirements_optional_gpt4all.txt reqs_optional/requirements_optional_langchain.gpllike.txt ; do pip install -r $fil ; done
cd client
make setup
make lint # this gave a lint error
make build
pip install dist/h2ogpt_client-0.1.0-py3-none-any.whl
cd ..
pytest -s -v --forked client
```
`pytest -s -v --forked client` gave a different error
```
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --forked
  inifile: /home/sajith/src/h2ogpt/client/pyproject.toml
  rootdir: /home/sajith/src/h2ogpt/client
```
Then I tried `pytest -s -v client` and test failed with a `ModuleNotFoundError`.
```
================================================================ test session starts =================================================================
platform linux -- Python 3.10.12, pytest-7.3.1, pluggy-1.0.0 -- /home/sajith/src/h2ogpt/venv/bin/python
cachedir: .pytest_cache
rootdir: /home/sajith/src/h2ogpt/client
configfile: pyproject.toml
plugins: anyio-3.6.2, xdist-3.2.1, asyncio-0.21.0
asyncio: mode=strict
collected 3 items                                                                                                                                    

client/tests/test_client.py::test_text_completion FAILED
client/tests/test_client.py::test_text_completion_async SKIPPED (async def function and no async plugin installed (see warnings))
client/tests/test_client.py::test_chat_completion FAILED

====================================================================== FAILURES ======================================================================
________________________________________________________________ test_text_completion ________________________________________________________________

    def test_text_completion():
>       launch_server()

client/tests/test_client.py:12: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    def launch_server():
>       from generate import main
E       ModuleNotFoundError: No module named 'generate'

client/tests/test_client.py:53: ModuleNotFoundError
________________________________________________________________ test_chat_completion ________________________________________________________________

    def test_chat_completion():
>       launch_server()

client/tests/test_client.py:30: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    def launch_server():
>       from generate import main
E       ModuleNotFoundError: No module named 'generate'

client/tests/test_client.py:53: ModuleNotFoundError
================================================================== warnings summary ==================================================================
tests/test_client.py::test_text_completion_async
  /home/sajith/src/h2ogpt/venv/lib/python3.10/site-packages/_pytest/python.py:183: PytestUnhandledCoroutineWarning: async def functions are not natively supported and have been skipped.
  You need to install a suitable plugin for your async framework, for example:
    - anyio
    - pytest-asyncio
    - pytest-tornasync
    - pytest-trio
    - pytest-twisted
    warnings.warn(PytestUnhandledCoroutineWarning(msg.format(nodeid)))

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
============================================================== short test summary info ===============================================================
FAILED client/tests/test_client.py::test_text_completion - ModuleNotFoundError: No module named 'generate'
FAILED client/tests/test_client.py::test_chat_completion - ModuleNotFoundError: No module named 'generate'
====================================================== 2 failed, 1 skipped, 1 warning in 0.29s =======================================================
````

**Comment by this** [comment]
@pseudotensor May be the reported issue happens because the Client relies on different set of dependencies.

Is it must to have the ability to run Client tests from the h2oGPT Python environment? We recently added [problematically starting h2oGPT server for the Client tests inside the test file](https://github.com/h2oai/h2ogpt/blob/0d69134c1a4135b01677285459a1cf1f93e1112b/client/tests/test_client.py#L52-L55). I think it is best to use Make & bash to achieve that. Furthermore, the Client has different set of requirements hence it is best maintain a separate set of dependencies and separate venv Python environment for the Client IMO.

**Comment by pseudotensor** [comment]
Your missing a step that's listed:
```
cd ..
```

I added the server in the test because otherwise nothing was actually tested without some separate effort outside the test framework.

I think building the client can be using deps outside those used by non-client, like poetry.  However, it seems too much to have it impossible for the client to work within the same env as non-client.  One couldn't even test the client without a separate env if one had to have 2 envs, which is unusual IMO.  E.g. gradio and gradio_client work together.  DAI client and DAI are in same env, etc.

**Comment by slavag** [comment]
I got this error few times , solved by :
python -m pip install requests "urllib3<2"
