### ISSUE TITLE
ValueError: generator already executing

### ISSUE THREAD

**Issue by pseudotensor** [h2oai/h2ogpt#368]
Happens for even gradio -> TGI
```
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/h2ollm/lib/python3.10/site-packages/gradio/routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/ubuntu/miniconda3/envs/h2ollm/lib/python3.10/site-packages/gradio/blocks.py", line 1352, in process_api
    result = await self.call_function(
  File "/home/ubuntu/miniconda3/envs/h2ollm/lib/python3.10/site-packages/gradio/blocks.py", line 1093, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/home/ubuntu/miniconda3/envs/h2ollm/lib/python3.10/site-packages/gradio/utils.py", line 341, in async_iteration
    return await iterator.__anext__()
  File "/home/ubuntu/miniconda3/envs/h2ollm/lib/python3.10/site-packages/gradio/utils.py", line 334, in __anext__
    return await anyio.to_thread.run_sync(
  File "/home/ubuntu/miniconda3/envs/h2ollm/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/ubuntu/miniconda3/envs/h2ollm/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/ubuntu/miniconda3/envs/h2ollm/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/ubuntu/miniconda3/envs/h2ollm/lib/python3.10/site-packages/gradio/utils.py", line 317, in run_sync_iterator_async
    return next(iterator)
ValueError: generator already executing

```

**Comment by pseudotensor** [comment]
https://stackoverflow.com/questions/1131430/are-generators-threadsafe

**Comment by konradzuse** [comment]
I'm getting a similar error when making multiple concurrent calls from Python using the Gradio client.

 Using the latest Docker image (0.1.0-287), and vLLM for inferencing engine.

The first call works, but then second concurrent call results in this stack trace...

`Traceback (most recent call last):
  File "/h2ogpt_conda/lib/python3.10/site-packages/gradio/queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
  File "/h2ogpt_conda/lib/python3.10/site-packages/gradio/route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
  File "/h2ogpt_conda/lib/python3.10/site-packages/gradio/blocks.py", line 1550, in process_api
    result = await self.call_function(
  File "/h2ogpt_conda/lib/python3.10/site-packages/gradio/blocks.py", line 1199, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/h2ogpt_conda/lib/python3.10/site-packages/gradio/utils.py", line 519, in async_iteration
    return await iterator.__anext__()
  File "/h2ogpt_conda/lib/python3.10/site-packages/gradio/utils.py", line 512, in __anext__
    return await anyio.to_thread.run_sync(
  File "/h2ogpt_conda/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/h2ogpt_conda/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/h2ogpt_conda/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/h2ogpt_conda/lib/python3.10/site-packages/gradio/utils.py", line 495, in run_sync_iterator_async
    return next(iterator)
ValueError: generator already executing`

**Comment by pseudotensor** [comment]
You need to use a different client (or change the session_hash) to talk to the server.  E.g. like done in GradioClient class in gradio_utils/grclient.py.

I recommend using GradioClient class if you can.  Then first time setting up the client you use .setup().  Then every new client connection only needs to run .clone().
