### ISSUE TITLE
AttributeError: 'AsyncRequest' object has no attribute '_json_response_data'

### ISSUE THREAD

**Issue by pseudotensor** [h2oai/h2ogpt#379]
```
Task exception was never retrieved
future: <Task finished name='47d82wcfhtl_44' coro=<Queue.process_events() done, defined at /home/ubuntu/miniconda3/envs/h2ollm/lib/python3.10/site-packages/gradio/queueing.py:342> exception=AttributeError("'AsyncRequest'>
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/h2ollm/lib/python3.10/site-packages/gradio/queueing.py", line 369, in process_events
    while response.json.get("is_generating", False):
  File "/home/ubuntu/miniconda3/envs/h2ollm/lib/python3.10/site-packages/gradio/utils.py", line 543, in json
    return self._json_response_data
AttributeError: 'AsyncRequest' object has no attribute '_json_response_data'
```

**Comment by idiotcommerce** [comment]
i want to work on this error. but one doubt. which file name are you getting error.

File "/home/ubuntu/miniconda3/envs/h2ollm/lib/python3.10/site-packages/gradio/queueing.py", line 369, in process_events
    while response.json.get("is_generating", False):
  File "/home/ubuntu/miniconda3/envs/h2ollm/lib/python3.10/site-packages/gradio/utils.py", line 543, in json
    return self._json_response_data
 these seems to be you local machine locations.

may i get the file name

**Comment by idiotcommerce** [comment]
thank you for this if i can i will try on this. one week. if not completed by me please assign to other. 

thank for this
