### ISSUE TITLE
Warn if pdf used does not have any text.

### ISSUE THREAD

**Issue by gerhean** [h2oai/h2ogpt#396]
I was saving websites as pdf, and used them for doing question answering. However, I did not realize that the pdfs were saved as images of the website instead of text. Despite being a simple problem, it took me some time to figure out the issue.

This also causes an unhelpful error message to show up when I try to refresh sources:
`Can't pickle local object 'Selectable.__init__.<locals>.<lambda>'`
![image](https://github.com/h2oai/h2ogpt/assets/16630400/c4b0b9fb-0b59-4021-a727-66d063b7c4ae)

Suggestion:
Add a warning when a pdf used does not contain any text.
Make the error message more helpful.

**Comment by pseudotensor** [comment]
Thanks!  Will take a look.

**Comment by pseudotensor** [comment]
@gerhean Do you happen to have the CLI's full stack trace for that odd error?  By itself it's hard to know why it happened or where it came from.

**Comment by pseudotensor** [comment]
@gerhean Also, curious if you tried the URL entry instead for websites, might work better.

Also, if you have a list  of urls, that can be uploaded as a file itself in the drop area.

**Comment by gerhean** [comment]
I wasn't able to reproduce that issue, but I got another odd error:
```
Loaded 1 new files as sources to add to UserData
Loaded 1 sources for potentially adding to UserData
Existing db, potentially adding 1 sources from user_path=user_path/tmp
Found 1 new sources (1 have no hash in original source, so have to reprocess for migration to sources with hash)
Removing 1 duplicate files from db because ingesting those as new documents
Existing db, added 1 new sources from user_path=user_path/tmp
Detected new embedding, updating db: UserData
load INSTRUCTOR_Transformer
max_seq_length  512
Done updating db for new embedding: UserData
Number of requested results 1000 is greater than number of elements in index 5, updating n_results = 5
Detected new embedding, updating db: UserData
Done updating db for new embedding: UserData
  0%|                                                                                             | 0/1 [00:00<?, ?it/s]Failed to ingest user_path/tmp/./Best Centres website.pdf due to Traceback (most recent call last):
  File "/home/me/repos_wsl/h2ogpt/gpt_langchain.py", line 1213, in path_to_doc1
    res = file_to_doc(file, base_path=None, verbose=verbose, fail_any_exception=fail_any_exception,
  File "/home/me/repos_wsl/h2ogpt/gpt_langchain.py", line 1151, in file_to_doc
    doc1 = chunk_sources(doc1, chunk=chunk, chunk_size=chunk_size)
  File "/home/me/repos_wsl/h2ogpt/gpt_langchain.py", line 2243, in chunk_sources
    splitter = RecursiveCharacterTextSplitter(chunk_size=chunk_size, chunk_overlap=0, keep_separator=keep_separator,
  File "/home/me/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/langchain/text_splitter.py", line 585, in __init__
    super().__init__(keep_separator=keep_separator, **kwargs)
  File "/home/me/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/langchain/text_splitter.py", line 76, in __init__
    if chunk_overlap > chunk_size:
TypeError: '>' not supported between instances of 'int' and 'Number'
```

I should also say that this is done on wsl2.

**Comment by gerhean** [comment]
I was able to get the error again:
```
~/repos_wsl/h2ogpt$ python generate.py --base_model='llama' --prompt_type=wizard2 --score_model=None --langchain_mode='UserData' --user_path=user_path/tmp
Using Model llama
Prep: persist_directory=db_dir_UserData exists, user_path=user_path/tmp passed, adding any changed or new documents
load INSTRUCTOR_Transformer
max_seq_length  512
Detected new embedding, updating db: UserData
load INSTRUCTOR_Transformer
max_seq_length  512
Done updating db for new embedding: UserData
0it [00:00, ?it/s]huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
100%|█████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00,  3.53it/s]
0it [00:00, ?it/s]
Loaded 0 sources for potentially adding to UserData
ggml_init_cublas: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 4080
llama.cpp: loading model from nous-hermes-13b.ggmlv3.q4_K_M.bin
llama_model_load_internal: format     = ggjt v3 (latest)
llama_model_load_internal: n_vocab    = 32001
llama_model_load_internal: n_ctx      = 1792
llama_model_load_internal: n_embd     = 5120
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 40
llama_model_load_internal: n_layer    = 40
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 15 (mostly Q4_K - Medium)
llama_model_load_internal: n_ff       = 13824
llama_model_load_internal: model size = 13B
llama_model_load_internal: ggml ctx size =    0.09 MB
llama_model_load_internal: using CUDA for GPU acceleration
llama_model_load_internal: mem required  = 2135.99 MB (+ 1608.00 MB per state)
llama_model_load_internal: allocating batch_size x (640 kB + n_ctx x 160 B) = 460 MB VRAM for the scratch buffer
llama_model_load_internal: offloading 40 repeating layers to GPU
llama_model_load_internal: offloading non-repeating layers to GPU
llama_model_load_internal: offloading v cache to GPU
llama_model_load_internal: offloading k cache to GPU
llama_model_load_internal: offloaded 43/43 layers to GPU
llama_model_load_internal: total VRAM used: 9441 MB
llama_new_context_with_model: kv self size  = 1400.00 MB
AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | VSX = 0 |
Model {'base_model': 'llama', 'tokenizer_base_model': '', 'lora_weights': '', 'inference_server': '', 'prompt_type': 'wizard2', 'prompt_dict': {'promptA': "Below is an instruction that describes a task. Write a response that appropriately completes the request. If you don't know the answer, say that you don't know.", 'promptB': "Below is an instruction that describes a task. Write a response that appropriately completes the request. If you don't know the answer, say that you don't know.", 'PreInstruct': '\n### Instruction:\n', 'PreInput': None, 'PreResponse': '\n### Response:\n', 'terminate_response': ['\n### Response:\n'], 'chat_sep': '\n', 'chat_turn_sep': '\n', 'humanstr': '\n### Instruction:\n', 'botstr': '\n### Response:\n', 'generates_leading_space': False}}
Running on local URL:  http://0.0.0.0:7860
Detected new embedding, updating db: UserData
Done updating db for new embedding: UserData
0it [00:00, ?it/s]huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/home/me/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/gradio/routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/me/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/gradio/blocks.py", line 1352, in process_api
    result = await self.call_function(
  File "/home/me/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/gradio/blocks.py", line 1077, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/me/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/me/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/me/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/me/repos_wsl/h2ogpt/gradio_runner.py", line 2396, in update_and_get_source_files_given_langchain_mode
    db, num_new_sources, new_sources_metadata = make_db(use_openai_embedding=False,
  File "/home/me/repos_wsl/h2ogpt/gpt_langchain.py", line 1511, in make_db
    return _make_db(**langchain_kwargs)
  File "/home/me/repos_wsl/h2ogpt/gpt_langchain.py", line 1612, in _make_db
    sources1 = path_to_docs(user_path, n_jobs=n_jobs, chunk=chunk, chunk_size=chunk_size,
  File "/home/me/repos_wsl/h2ogpt/gpt_langchain.py", line 1328, in path_to_docs
    documents = ProgressParallel(n_jobs=n_jobs, verbose=10 if verbose else 0, backend='multiprocessing')(
  File "/home/me/repos_wsl/h2ogpt/utils.py", line 805, in __call__
    return Parallel.__call__(self, *args, **kwargs)
  File "/home/me/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/joblib/parallel.py", line 1944, in __call__
    return output if self.return_generator else list(output)
  File "/home/me/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/joblib/parallel.py", line 1587, in _get_outputs
    yield from self._retrieve()
  File "/home/me/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/joblib/parallel.py", line 1691, in _retrieve
    self._raise_error_fast()
  File "/home/me/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/joblib/parallel.py", line 1726, in _raise_error_fast
    error_job.get_result(self.timeout)
  File "/home/me/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/joblib/parallel.py", line 735, in get_result
    return self._return_or_raise()
  File "/home/me/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/joblib/parallel.py", line 753, in _return_or_raise
    raise self._result
AttributeError: Can't pickle local object 'Selectable.__init__.<locals>.<lambda>'
```

**Comment by pseudotensor** [comment]
Those are very odd errors.  Do they happen every time?

I googled each.

The int vs. Number is *super* odd.  What if you add change `chunk_size` to `int(chunk_size)` when passing into that `RecursiveCharacterTextSplitter` function?  I'm assuming it's WSL specific.

 The pickle thing might be windows specific issue with joblib.  A work-around might be to rename `ProgressParallel` to just `Parallel` in gpt_langchain.py when used (not import, just where used twice inside the functions).

Let me know if that works, and we can make a PR to adjust for WSL.

**Comment by pseudotensor** [comment]
Using this:

[image-based-pdf-sample.pdf](https://github.com/h2oai/h2ogpt/files/12066215/image-based-pdf-sample.pdf)
