### ISSUE TITLE
Image captioning crashing, gibberish output.

### ISSUE THREAD

**Issue by gerhean2** [h2oai/h2ogpt#412]
I added an image into the user_path and ran the app. When I asked a question, an error message was displayed. When I restarted, it does not crash, but the captions are somewhat gibberish.
Running on native Windows.

```
(h2ogpt) C:\Users\me\Documents\repos\h2ogpt>python generate.py --base_model='llama' --prompt_type=wizard2 --score_model=None --langchain_mode='UserData' --user_path=../t_user_path
Using Model llama
Prep: persist_directory=db_dir_UserData exists, user_path=../t_user_path passed, adding any changed or new documents
load INSTRUCTOR_Transformer
max_seq_length  512
0it [00:00, ?it/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:10<00:00, 10.55s/it] 
Loaded 1 new files as sources to add to UserData
Loaded 1 sources for potentially adding to UserData
Existing db, potentially adding 1 sources from user_path=../t_user_path
Found 1 new sources (0 have no hash in original source, so have to reprocess for migration to sources with hash)
Removing 0 duplicate files from db because ingesting those as new documents
Existing db, added 1 new sources from user_path=../t_user_path
ggml_init_cublas: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 4080
llama.cpp: loading model from nous-hermes-13b.ggmlv3.q4_K_M.bin
llama_model_load_internal: format     = ggjt v3 (latest)
llama_model_load_internal: n_vocab    = 32001
llama_model_load_internal: n_ctx      = 1792
llama_model_load_internal: n_embd     = 5120
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 40
llama_model_load_internal: n_layer    = 40
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 15 (mostly Q4_K - Medium)
llama_model_load_internal: n_ff       = 13824
llama_model_load_internal: model size = 13B
llama_model_load_internal: ggml ctx size =    0.09 MB
llama_model_load_internal: using CUDA for GPU acceleration
llama_model_load_internal: mem required  = 2135.99 MB (+ 1608.00 MB per state)
llama_model_load_internal: allocating batch_size x (640 kB + n_ctx x 160 B) = 460 MB VRAM for the scratch buffer
llama_model_load_internal: offloading 40 repeating layers to GPU
llama_model_load_internal: offloading non-repeating layers to GPU
llama_model_load_internal: offloading v cache to GPU
llama_model_load_internal: offloading k cache to GPU
llama_model_load_internal: offloaded 43/43 layers to GPU
llama_model_load_internal: total VRAM used: 9441 MB
llama_new_context_with_model: kv self size  = 1400.00 MB
AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | VSX = 0 |
Model {'base_model': 'llama', 'tokenizer_base_model': '', 'lora_weights': '', 'inference_server': '', 'prompt_type': 'wizard2', 'prompt_dict': {'promptA': 'Below is an instruction that describes a task. Write a response that appropriately completes the request.', 'promptB': 'Below is an instruction that describes a task. Write a response that appropriately completes the request.', 'PreInstruct': '\n### Instruction:\n', 'PreInput': None, 'PreResponse': '\n### Response:\n', 'terminate_response': ['\n### Response:\n'], 'chat_sep': '\n', 'chat_turn_sep': '\n', 'humanstr': '\n### Instruction:\n', 'botstr': '\n### Response:\n', 'generates_leading_space': False}}
Running on local URL:  http://0.0.0.0:7860
Running on public URL: https://a388d583d5a808de43.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)
Number of requested results 1000 is greater than number of elements in index 3, updating n_results = 3
Traceback (most recent call last):
  File "C:\Users\me\miniconda3\envs\h2ogpt\lib\site-packages\gradio\routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\me\miniconda3\envs\h2ogpt\lib\site-packages\gradio\blocks.py", line 1352, in process_api
    result = await self.call_function(
  File "C:\Users\me\miniconda3\envs\h2ogpt\lib\site-packages\gradio\blocks.py", line 1093, in call_function
    prediction = await utils.async_iteration(iterator)
  File "C:\Users\me\miniconda3\envs\h2ogpt\lib\site-packages\gradio\utils.py", line 341, in async_iteration
    return await iterator.__anext__()
  File "C:\Users\me\miniconda3\envs\h2ogpt\lib\site-packages\gradio\utils.py", line 334, in __anext__
    return await anyio.to_thread.run_sync(
  File "C:\Users\me\miniconda3\envs\h2ogpt\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\me\miniconda3\envs\h2ogpt\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\me\miniconda3\envs\h2ogpt\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\me\miniconda3\envs\h2ogpt\lib\site-packages\gradio\utils.py", line 317, in run_sync_iterator_async
    return next(iterator)
  File "C:\Users\me\Documents\repos\h2ogpt\src\gradio_runner.py", line 1350, in bot
    for res in get_response(fun1, history):
  File "C:\Users\me\Documents\repos\h2ogpt\src\gradio_runner.py", line 1307, in get_response
    for output_fun in fun1():
  File "C:\Users\me\Documents\repos\h2ogpt\src\gen.py", line 1417, in evaluate
    for r in run_qa_db(query=instruction,
  File "C:\Users\me\Documents\repos\h2ogpt\src\gpt_langchain.py", line 1887, in _run_qa_db
    docs, chain, scores, use_context, have_any_docs = get_similarity_chain(**sim_kwargs)
  File "C:\Users\me\Documents\repos\h2ogpt\src\gpt_langchain.py", line 2139, in get_similarity_chain
    docs_with_score = db.similarity_search_with_score(query, k=k_db, **filter_kwargs)[
  File "C:\Users\me\miniconda3\envs\h2ogpt\lib\site-packages\langchain\vectorstores\chroma.py", line 247, in similarity_search_with_score
    results = self.__query_collection(
  File "C:\Users\me\miniconda3\envs\h2ogpt\lib\site-packages\langchain\utils.py", line 55, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\me\miniconda3\envs\h2ogpt\lib\site-packages\langchain\vectorstores\chroma.py", line 121, in __query_collection
    return self._collection.query(
  File "C:\Users\me\miniconda3\envs\h2ogpt\lib\site-packages\chromadb\api\models\Collection.py", line 230, in query
    return self._client._query(
  File "C:\Users\me\miniconda3\envs\h2ogpt\lib\site-packages\chromadb\api\local.py", line 439, in _query
    uuids, distances = self._db.get_nearest_neighbors(
  File "C:\Users\me\miniconda3\envs\h2ogpt\lib\site-packages\chromadb\db\clickhouse.py", line 591, in get_nearest_neighbors
    uuids, distances = index.get_nearest_neighbors(embeddings, n_results, ids)
  File "C:\Users\me\miniconda3\envs\h2ogpt\lib\site-packages\chromadb\db\index\hnswlib.py", line 296, in get_nearest_neighbors
    database_labels, distances = self._index.knn_query(
RuntimeError: Cannot return the results in a contigious 2D array. Probably ef or M is too small
```

After restart:
![image](https://github.com/h2oai/h2ogpt/assets/139114856/f2cd2d63-4b6b-4ddc-a999-38affe4c45e6)

giraffe-spots.jpg image for reference:
![giraffe-spots](https://github.com/h2oai/h2ogpt/assets/139114856/95c45277-9aa2-4427-a257-64bad7fbb3cc)

**Comment by pseudotensor** [comment]
Thanks.  The default BLIP model "Salesforce/blip-image-captioning-base" may not be good enough.  What I get for caption is:

```
a gifefe gifefefefefefefefefefefefefefefefefefefe
```

However, if I use ` --captions_model=Salesforce/blip2-flan-t5-xl` (i.e. a larger BLIP2 model), then I get:

```
a giraffe and a baby giraffe in the wild with a tree in the background
```
(it's truncated just because I only show first part

**Comment by pseudotensor** [comment]
One alternative is to use OpenAI for the LLM but all else is local, in case you don't have sufficient GPU memory or CPU models are too slow.

i.e.

```
python generate.py  --inference_server=openai_chat --base_model=gpt-3.5-turbo --score_model=None --langchain_mode=ChatLLM --visible_langchain_modes="['ChatLLM', 'UserData', 'MyData']" --captions_model=Salesforce/blip2-flan-t5-xl
```
