### ISSUE TITLE
RuntimeError: weight lm_head.weight does not exist when loading 40B into TGI

### ISSUE THREAD

**Issue by arnocandel** [h2oai/h2ogpt#423]
```
2023-07-11T19:05:30.867858Z  INFO text_generation_launcher: Args { model_id: "h2oai/h2ogpt-oasst1-2048-falcon-40b", revision: None, sharded: Some(true), num_shard: Some(2), quantize: None, dtype: None, trust_remote_code: false, max_concurrent_requests: 128, max_best_of: 2, max_stop_sequences: 6, max_input_length: 2048, max_total_tokens: 4096, waiting_served_ratio: 1.2, max_batch_prefill_tokens: 4096, max_batch_total_tokens: 16000, max_waiting_tokens: 20, hostname: "58413f2d4942", port: 80, shard_uds_path: "/tmp/text-generation-server", master_addr: "localhost", master_port: 29500, huggingface_hub_cache: Some("/data"), weights_cache_override: None, disable_custom_kernels: false, json_output: false, otlp_endpoint: None, cors_allow_origin: [], watermark_gamma: None, watermark_delta: None, ngrok: false, ngrok_authtoken: None, ngrok_domain: None, ngrok_username: None, ngrok_password: None, env: false }
2023-07-11T19:05:30.867902Z  INFO text_generation_launcher: Sharding model on 2 processes
2023-07-11T19:05:30.868010Z  INFO text_generation_launcher: Starting download process.
2023-07-11T19:05:37.156236Z  INFO download: text_generation_launcher: Files are already present on the host. Skipping download.

2023-07-11T19:05:38.018601Z  INFO text_generation_launcher: Successfully downloaded weights.
2023-07-11T19:05:38.018958Z  INFO text_generation_launcher: Starting shard 0
2023-07-11T19:05:38.019475Z  INFO text_generation_launcher: Starting shard 1
2023-07-11T19:05:41.796890Z  WARN shard-manager: text_generation_launcher: We're not using custom kernels.
 rank=1
2023-07-11T19:05:41.796911Z  WARN shard-manager: text_generation_launcher: We're not using custom kernels.
 rank=0
2023-07-11T19:05:48.031607Z  INFO text_generation_launcher: Waiting for shard 0 to be ready...
2023-07-11T19:05:48.033419Z  INFO text_generation_launcher: Waiting for shard 1 to be ready...
2023-07-11T19:05:58.041723Z  INFO text_generation_launcher: Waiting for shard 0 to be ready...
2023-07-11T19:05:58.045233Z  INFO text_generation_launcher: Waiting for shard 1 to be ready...
2023-07-11T19:06:08.088001Z  INFO text_generation_launcher: Waiting for shard 1 to be ready...
2023-07-11T19:06:08.097966Z  INFO text_generation_launcher: Waiting for shard 0 to be ready...
2023-07-11T19:06:18.124193Z  INFO text_generation_launcher: Waiting for shard 1 to be ready...
2023-07-11T19:06:18.156394Z  INFO text_generation_launcher: Waiting for shard 0 to be ready...
2023-07-11T19:06:28.150596Z  INFO text_generation_launcher: Waiting for shard 1 to be ready...
2023-07-11T19:06:28.219268Z  INFO text_generation_launcher: Waiting for shard 0 to be ready...
2023-07-11T19:06:38.229018Z  INFO text_generation_launcher: Waiting for shard 1 to be ready...
2023-07-11T19:06:38.244650Z  INFO text_generation_launcher: Waiting for shard 0 to be ready...
2023-07-11T19:06:48.253346Z  INFO text_generation_launcher: Waiting for shard 1 to be ready...
2023-07-11T19:06:48.266698Z  INFO text_generation_launcher: Waiting for shard 0 to be ready...
2023-07-11T19:06:58.284536Z  INFO text_generation_launcher: Waiting for shard 1 to be ready...
2023-07-11T19:06:58.293939Z  INFO text_generation_launcher: Waiting for shard 0 to be ready...
2023-07-11T19:07:08.322518Z  INFO text_generation_launcher: Waiting for shard 1 to be ready...
2023-07-11T19:07:08.324448Z  INFO text_generation_launcher: Waiting for shard 0 to be ready...
2023-07-11T19:07:18.353307Z  INFO text_generation_launcher: Waiting for shard 0 to be ready...
2023-07-11T19:07:18.362146Z  INFO text_generation_launcher: Waiting for shard 1 to be ready...
2023-07-11T19:07:28.376571Z  INFO text_generation_launcher: Waiting for shard 0 to be ready...
2023-07-11T19:07:28.395475Z  INFO text_generation_launcher: Waiting for shard 1 to be ready...
2023-07-11T19:07:38.424558Z  INFO text_generation_launcher: Waiting for shard 1 to be ready...
2023-07-11T19:07:38.426917Z  INFO text_generation_launcher: Waiting for shard 0 to be ready...
2023-07-11T19:07:48.463834Z  INFO text_generation_launcher: Waiting for shard 1 to be ready...
2023-07-11T19:07:48.475293Z  INFO text_generation_launcher: Waiting for shard 0 to be ready...
2023-07-11T19:07:58.511842Z  INFO text_generation_launcher: Waiting for shard 0 to be ready...
2023-07-11T19:07:58.514634Z  INFO text_generation_launcher: Waiting for shard 1 to be ready...
2023-07-11T19:08:08.542792Z  INFO text_generation_launcher: Waiting for shard 1 to be ready...
2023-07-11T19:08:08.599046Z  INFO text_generation_launcher: Waiting for shard 0 to be ready...
2023-07-11T19:08:18.631755Z  INFO text_generation_launcher: Waiting for shard 1 to be ready...
2023-07-11T19:08:18.635139Z  INFO text_generation_launcher: Waiting for shard 0 to be ready...
2023-07-11T19:08:20.610267Z ERROR shard-manager: text_generation_launcher: Error when initializing model
Traceback (most recent call last):
  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())
  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py", line 78, in serve
    server.serve(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 166, in serve
    asyncio.run(
  File "/opt/conda/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 133, in serve_inner
    model = get_model(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/__init__.py", line 241, in get_model
    return FlashRWSharded(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_rw.py", line 56, in __init__
    model = FlashRWForCausalLM(config, weights)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_rw_modeling.py", line 630, in __init__
    self.lm_head = TensorParallelHead.load(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/layers.py", line 183, in load
    weight = weights.get_sharded(f"{prefix}.weight", dim=0)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/weights.py", line 73, in get_sharded
    filename, tensor_name = self.get_filename(tensor_name)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/weights.py", line 49, in get_filename
    raise RuntimeError(f"weight {tensor_name} does not exist")
RuntimeError: weight lm_head.weight does not exist
```

**Comment by arnocandel** [comment]
Created by 8b127fae2bcdfc69266ce35f917a096fe5824a48 export script.

**Comment by arnocandel** [comment]
same thing for locally created 7B export
```
export MODEL=h2ogpt-oasst1-2048-falcon-7b
export HF_PORT=5000
export CUDA_VISIBLE_DEVICES=0
```

`docker run --gpus all --shm-size 1g -e CUDA_VISIBLE_DEVICES=$CUDA_VISIBLE_DEVICES -e HUGGING_FACE_HUB_TOKEN=$HUGGING_FACE_HUB_TOKEN -e TRANSFORMERS_CACHE="/.cache/" -p $HF_PORT:80 -v $HOME/.cache:/.cache/ -v $PWD/$MODEL:/data/$MODEL ghcr.io/huggingface/text-generation-inference:latest --model-id /data/$MODEL --weights-cache-override $MODEL --max-input-length 2048 --max-total-tokens 4096 --max-stop-sequences 6 --sharded false`

```
2023-07-11T19:51:03.512830Z  INFO text_generation_launcher: Args { model_id: "/data/h2ogpt-oasst1-2048-falcon-7b", revision: None, sharded: Some(false), num_shard: None, quantize: None, trust_remote_code: false, max_concurrent_requests: 128, max_best_of: 2, max_stop_sequences: 6, max_input_length: 2048, max_total_tokens: 4096, max_batch_size: None, waiting_served_ratio: 1.2, max_batch_total_tokens: 32000, max_waiting_tokens: 20, port: 80, shard_uds_path: "/tmp/text-generation-server", master_addr: "localhost", master_port: 29500, huggingface_hub_cache: Some("/data"), weights_cache_override: Some("h2ogpt-oasst1-2048-falcon-7b"), disable_custom_kernels: false, json_output: false, otlp_endpoint: None, cors_allow_origin: [], watermark_gamma: None, watermark_delta: None, ngrok: false, ngrok_authtoken: None, ngrok_domain: None, ngrok_username: None, ngrok_password: None, env: false }
2023-07-11T19:51:03.512934Z  INFO text_generation_launcher: Starting download process.
2023-07-11T19:51:05.614839Z  INFO download: text_generation_launcher: Files are already present on the host. Skipping download.

2023-07-11T19:51:06.116444Z  INFO text_generation_launcher: Successfully downloaded weights.
2023-07-11T19:51:06.116581Z  INFO text_generation_launcher: Starting shard 0
2023-07-11T19:51:08.079559Z  WARN shard-manager: text_generation_launcher: We're not using custom kernels.
 rank=0
2023-07-11T19:51:08.266374Z ERROR shard-manager: text_generation_launcher: Error when initializing model
Traceback (most recent call last):
  File "/opt/conda/bin/text-generation-server", line 8, in <module>
    sys.exit(app())
  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/opt/conda/lib/python3.9/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/cli.py", line 67, in serve
    server.serve(model_id, revision, sharded, quantize, trust_remote_code, uds_path)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 155, in serve
    asyncio.run(serve_inner(model_id, revision, sharded, quantize, trust_remote_code))
  File "/opt/conda/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "/opt/conda/lib/python3.9/site-packages/text_generation_server/server.py", line 124, in serve_inner
    model = get_model(model_id, revision, sharded, quantize, trust_remote_code)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/__init__.py", line 220, in get_model
    return FlashRWSharded(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/flash_rw.py", line 55, in __init__
    model = FlashRWForCausalLM(config, weights)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_rw_modeling.py", line 692, in __init__
    self.transformer = FlashRWModel(config, weights)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/models/custom_modeling/flash_rw_modeling.py", line 573, in __init__
    self.word_embeddings = TensorParallelEmbedding(
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/layers.py", line 268, in __init__
    weight = weights.get_sharded(f"{prefix}.weight", dim=0)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/weights.py", line 66, in get_sharded
    filename, tensor_name = self.get_filename(tensor_name)
  File "/opt/conda/lib/python3.9/site-packages/text_generation_server/utils/weights.py", line 42, in get_filename
    raise RuntimeError(f"weight {tensor_name} does not exist")
RuntimeError: weight transformer.word_embeddings.weight does not exist
```

**Comment by arnocandel** [comment]
compare with
https://github.com/h2oai/h2o-llmstudio/blob/fd8d879ac9e56203394afca76079c383dcf8ddc0/app_utils/sections/chat.py#L290-L340

**Comment by arnocandel** [comment]
https://discuss.huggingface.co/t/merged-lora-text-generation-inference-issues/45902

**Comment by arnocandel** [comment]
https://github.com/lm-sys/FastChat/blob/main/fastchat/model/apply_lora.py
