### ISSUE TITLE
TypeError: Chroma.__init__() got an unexpected keyword argument 'anonymized_telemetry'

### ISSUE THREAD

**Issue by Hybredm** [h2oai/h2ogpt#433]
Running this command python generate.py --base_model=h2oai/h2ogpt-gm-oasst1-en-2048-open-llama-7b --langchain_mode=MyData --score_model=None

I'm getting the title'd error while trying to parse a single PDF. 

Have tried PDFs of varying sizes.

Not sure if it's related to not being able to install this AutoGPTQ dependency as it is erroring out:

pip install -r https://github.com/PanQiWei/AutoGPTQ/releases/download/v0.2.2/auto_gptq-0.2.2+cu118-cp310-cp310-win_amd64.whl

ERROR: Invalid requirement: 'PK\x03\x04\x14\x00\x00\x00\x08\x00�.�V���/��\t\x00\x00`(\x00!\x00\x00\x00autogptq_cuda.cp310-win_amd64.pydĽ\t|TE\x120�f&\x03�\x11ޠ' (from line 1 of https://github.com/PanQiWei/AutoGPTQ/releases/download/v0.2.2/auto_gptq-0.2.2+cu118-cp310-cp310-win_amd64.whl)

Full error: 

load INSTRUCTOR_Transformer
max_seq_length  512
Traceback (most recent call last):
  File "C:\Users\2023\h2ogpt\src\gradio_runner.py", line 2339, in update_user_db
    return _update_user_db(file, db1=db1, chunk=chunk, chunk_size=chunk_size,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\2023\h2ogpt\src\gradio_runner.py", line 2470, in _update_user_db
    db = get_db(sources, use_openai_embedding=use_openai_embedding,
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\2023\h2ogpt\src\gpt_langchain.py", line 97, in get_db
    db = Chroma.from_documents(documents=sources,
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\2023\miniconda3\Lib\site-packages\langchain\vectorstores\chroma.py", line 564, in from_documents
    return cls.from_texts(
           ^^^^^^^^^^^^^^^
  File "C:\Users\2023\miniconda3\Lib\site-packages\langchain\vectorstores\chroma.py", line 519, in from_texts
    chroma_collection = cls(
                        ^^^^
TypeError: Chroma.__init__() got an unexpected keyword argument 'anonymized_telemetry'

**Comment by pseudotensor** [comment]
https://github.com/h2oai/h2ogpt/issues/426#issuecomment-1633241606

**Comment by pseudotensor** [comment]
Which steps exactly was confusing or missing?

**Comment by pseudotensor** [comment]
@Hybredm I think you must have different chroma etc.  Can you do:

```
pip freeze &> freeze.log
```

and share?

Here's mine (after a few more items.  You can also run the test:
```
pytest -s -v tests/test_requirements.py::test_requirements
```
which will test everything except peft version.

```
(h2ogpt) jon@pseudotensor:~/h2ogpt$ pip freeze
absl-py==1.4.0
accelerate==0.20.3
aiofiles==23.1.0
aiohttp==3.8.4
aiosignal==1.3.1
alt-profanity-check==1.2.2
altair==5.0.1
antlr4-python3-runtime==4.9.3
anyio==3.7.1
appdirs==1.4.4
APScheduler==3.10.1
argilla==1.12.0
arrow==1.2.3
arxiv==1.4.7
asttokens==2.2.1
async-timeout==4.0.2
attrs==23.1.0
Authlib==1.2.1
auto-gptq==0.2.2
backcall==0.2.0
backoff==2.2.1
beautifulsoup4==4.12.2
better-profanity==0.7.0
bioc==2.0
bitsandbytes==0.39.0
boto3==1.26.101
botocore==1.29.101
bravado==11.0.3
bravado-core==5.17.1
cachetools==5.3.1
certifi==2023.5.7
cffi==1.15.1
chardet==5.1.0
charset-normalizer==3.2.0
chromadb==0.3.25
click==8.1.4
clickhouse-connect==0.6.6
cmake==3.26.4
colorama==0.4.6
coloredlogs==15.0.1
comm==0.1.3
commonmark==0.9.1
contourpy==1.1.0
cryptography==41.0.1
cycler==0.11.0
dataclasses-json==0.5.9
datasets==2.13.0
debugpy==1.6.7
decorator==5.1.1
Deprecated==1.2.14
dill==0.3.6
diskcache==5.6.1
docker-pycreds==0.4.0
docutils==0.20.1
duckdb==0.8.1
effdet==0.4.1
einops==0.6.1
et-xmlfile==1.1.0
evaluate==0.4.0
exceptiongroup==1.1.2
execnet==2.0.2
executing==1.2.0
fastapi==0.100.0
feedparser==6.0.10
ffmpy==0.3.0
filelock==3.12.2
filetype==1.2.0
fire==0.5.0
flatbuffers==23.5.26
fonttools==4.40.0
fqdn==1.5.1
frozenlist==1.3.3
-e git+https://github.com/lm-sys/FastChat.git@807f15809c3290ab53cf8e94da2abf7b19b528d0#egg=fschat
fsspec==2023.6.0
future==0.18.3
gitdb==4.0.10
GitPython==3.1.32
google-auth==2.21.0
google-auth-oauthlib==1.0.0
gpt4all==0.3.3
gradio==3.35.2
gradio_client==0.2.7
greenlet==2.0.1
grpcio==1.56.0
h11==0.14.0
h2ogpt==0.1.0
hnswlib==0.7.0
httpcore==0.16.3
httptools==0.6.0
httpx==0.23.3
huggingface-hub==0.15.1
humanfriendly==10.0
idna==3.4
importlib-metadata==6.8.0
iniconfig==2.0.0
InstructorEmbedding==1.0.1
intervaltree==3.1.0
iopath==0.1.10
ipykernel==6.24.0
ipython==8.14.0
isoduration==20.11.0
jedi==0.18.2
Jinja2==3.1.2
jmespath==1.0.1
joblib==1.3.1
jsonlines==3.1.0
jsonpointer==2.4
jsonref==1.1.0
jsonschema==4.18.0
jsonschema-specifications==2023.6.1
jupyter-console==6.6.3
jupyter_client==8.3.0
jupyter_core==5.3.1
kiwisolver==1.4.4
langchain==0.0.202
langchainplus-sdk==0.0.20
layoutparser==0.3.4
linkify-it-py==2.0.2
lit==16.0.6
llama-cpp-python==0.1.68
lm-dataformat==0.0.20
loralib==0.1.1
lxml==4.9.3
lz4==4.3.2
Markdown==3.4.3
markdown-it-py==2.2.0
markdown2==2.4.9
MarkupSafe==2.1.3
marshmallow==3.19.0
marshmallow-enum==1.5.1
matplotlib==3.7.1
matplotlib-inline==0.1.6
mdit-py-plugins==0.3.3
mdurl==0.1.2
monotonic==1.6
mpmath==1.3.0
msg-parser==1.2.0
msgpack==1.0.5
multidict==6.0.4
multiprocess==0.70.14
mypy-extensions==1.0.0
neptune==1.2.0
nest-asyncio==1.5.6
networkx==3.1
nh3==0.2.14
nltk==3.8.1
numexpr==2.8.4
numpy==1.23.5
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-ml-py==11.525.131
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
nvitop==1.1.2
oauthlib==3.2.2
olefile==0.46
omegaconf==2.3.0
onnxruntime==1.15.1
openai==0.27.8
openapi-schema-pydantic==1.2.4
opencv-python==4.8.0.74
openpyxl==3.1.2
orjson==3.9.2
outcome==1.2.0
overrides==7.3.1
packaging==23.1
pandas==1.5.3
parso==0.8.3
pathtools==0.1.2
pdf2image==1.16.3
pdfminer.six==20221105
pdfplumber==0.9.0
peft @ git+https://github.com/huggingface/peft.git@0b62b4378b4ce9367932c73540349da9a41bdea8
pexpect==4.8.0
pickleshare==0.7.5
Pillow==10.0.0
pip-licenses==4.3.0
platformdirs==3.8.1
playwright==1.33.0
pluggy==1.2.0
portalocker==2.7.0
posthog==3.0.1
prettytable==3.8.0
prompt-toolkit==3.0.39
protobuf==3.20.0
psutil==5.9.5
ptyprocess==0.7.0
pure-eval==0.2.2
pyarrow==12.0.1
pyasn1==0.5.0
pyasn1-modules==0.3.0
pycocotools==2.0.6
pycparser==2.21
pydantic==1.10.11
pydub==0.25.1
pyee==9.0.4
Pygments==2.15.1
PyJWT==2.7.0
PyMuPDF==1.22.3
pynvml==11.5.0
pypandoc==1.11
pypandoc-binary==1.11
pyparsing==3.1.0
pypdf==3.9.1
pyphen==0.14.0
PySocks==1.7.1
pytesseract==0.3.10
pytest==7.2.2
pytest-xdist==3.2.1
python-dateutil==2.8.2
python-docx==0.8.11
python-dotenv==1.0.0
python-magic==0.4.27
python-multipart==0.0.6
python-pptx==0.6.21
pytz==2023.3
PyYAML==6.0
pyzmq==25.1.0
referencing==0.29.1
regex==2023.6.3
requests==2.31.0
requests-file==1.5.1
requests-oauthlib==1.3.1
responses==0.18.0
rfc3339-validator==0.1.4
rfc3986==1.5.0
rfc3987==1.3.8
rich==13.0.1
rouge==1.0.1
rouge-score==0.1.2
rpds-py==0.8.10
rsa==4.9
s3transfer==0.6.1
sacrebleu==2.3.1
safetensors==0.3.1
scikit-learn==1.2.2
scipy==1.11.1
selenium==4.10.0
semantic-version==2.10.0
sentence-transformers==2.2.2
sentencepiece==0.1.99
sentry-sdk==1.28.0
setproctitle==1.3.2
sgmllib3k==1.0.0
shortuuid==1.0.11
simplejson==3.19.1
six==1.16.0
smmap==5.0.0
sniffio==1.3.0
sortedcontainers==2.4.0
soupsieve==2.4.1
SQLAlchemy==2.0.18
stack-data==0.6.2
starlette==0.27.0
svgwrite==1.4.3
swagger-spec-validator==3.0.3
sympy==1.12
tabulate==0.9.0
tenacity==8.2.2
tensorboard==2.13.0
tensorboard-data-server==0.7.1
termcolor==2.3.0
text-generation==0.6.0
textstat==0.7.3
threadpoolctl==3.1.0
tiktoken==0.4.0
timm==0.9.2
tokenizers==0.13.3
tomli==2.0.1
toolz==0.12.0
torch==2.0.1
torchvision==0.15.2
tornado==6.3.2
tqdm==4.65.0
traitlets==5.9.0
transformers==4.30.2
trio==0.22.1
trio-websocket==0.10.3
triton==2.0.0
typer==0.7.0
typing-inspect==0.9.0
typing_extensions==4.7.1
tzdata==2023.3
tzlocal==5.0.1
uc-micro-py==1.0.2
ujson==5.8.0
unstructured==0.7.4
unstructured-inference==0.5.1
uri-template==1.3.0
urllib3==1.26.16
uvicorn==0.22.0
uvloop==0.17.0
validators==0.20.0
Wand==0.6.11
wandb==0.15.5
watchfiles==0.19.0
wavedrom==2.0.3.post3
wcwidth==0.2.6
weaviate-client==3.20.0
webcolors==1.13
websocket-client==1.6.1
websockets==11.0.3
Werkzeug==2.3.6
wrapt==1.14.1
wsproto==1.2.0
xlrd==2.0.1
XlsxWriter==3.1.2
xxhash==3.2.0
yarl==1.9.2
zipp==3.16.0
zstandard==0.21.0

```

**Comment by pseudotensor** [comment]
Closing, since clear has to be wrong langchain version.
