### ISSUE TITLE
oig-oasst1-512-6_9b RuntimeError: MPS does not support cumsum op with int64 input

### ISSUE THREAD

**Issue by wizzard0** [h2oai/h2ogpt#464]
Command: `python generate.py --score_model=None`

Expected: something could be generated on default settings

Observed:
```
Auto set langchain_mode=ChatLLM.  Could use MyData instead.  To allow UserData to pull files from disk, set user_path and ensure allow_upload_to_user_data=True
Using Model h2oai/h2ogpt-oig-oasst1-512-6_9b
Prep: persist_directory=db_dir_UserData does not exist, regenerating
Chose UserData but user_path is empty/None
Starting get_model: h2oai/h2ogpt-oig-oasst1-512-6_9b
Downloading (…)l-00001-of-00003.bin: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5.03G/5.03G [04:53<00:00, 16.0MB/s]
Downloading (…)l-00002-of-00003.bin: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5.02G/5.02G [05:13<00:00, 16.0MB/s]
Downloading (…)l-00003-of-00003.bin: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3.80G/3.80G [04:01<00:00, 15.7MB/s]
Downloading shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [14:10<00:00, 283.37s/it]
The model weights are not tied. Please use the `tie_weights` method before using the `infer_auto_device` function.
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:05<00:00,  1.97s/it]
Downloading (…)neration_config.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 111/111 [00:00<00:00, 457kB/s]
Model {'base_model': 'h2oai/h2ogpt-oig-oasst1-512-6_9b', 'tokenizer_base_model': '', 'lora_weights': '', 'inference_server': '', 'prompt_type': 'human_bot', 'prompt_dict': {'promptA': '', 'promptB': '', 'PreInstruct': '<human>: ', 'PreInput': None, 'PreResponse': '<bot>:', 'terminate_response': ['\n<human>:', '\n<bot>:', '<human>:', '<bot>:', '<bot>:'], 'chat_sep': '\n', 'chat_turn_sep': '\n', 'humanstr': '<human>:', 'botstr': '<bot>:', 'generates_leading_space': True}}
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
thread exception: (<class 'RuntimeError'>, RuntimeError('MPS does not support cumsum op with int64 input'), <traceback object at 0x45de78940>)
make stop: (<class 'RuntimeError'>, RuntimeError('MPS does not support cumsum op with int64 input'), <traceback object at 0x45de78940>)
hit stop
Traceback (most recent call last):
  File "/Users/user/dev/lib/python3.10/site-packages/gradio/routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "/Users/user/dev/lib/python3.10/site-packages/gradio/blocks.py", line 1352, in process_api
    result = await self.call_function(
  File "/Users/user/dev/lib/python3.10/site-packages/gradio/blocks.py", line 1093, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/Users/user/dev/lib/python3.10/site-packages/gradio/utils.py", line 341, in async_iteration
    return await iterator.__anext__()
  File "/Users/user/dev/lib/python3.10/site-packages/gradio/utils.py", line 334, in __anext__
    return await anyio.to_thread.run_sync(
  File "/Users/user/dev/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/Users/user/dev/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/Users/user/dev/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/Users/user/dev/lib/python3.10/site-packages/gradio/utils.py", line 317, in run_sync_iterator_async
    return next(iterator)
  File "/Users/user/dev/h2ogpt/src/gradio_runner.py", line 1428, in bot
    for res in get_response(fun1, history):
  File "/Users/user/dev/h2ogpt/src/gradio_runner.py", line 1385, in get_response
    for output_fun in fun1():
  File "/Users/user/dev/h2ogpt/src/gen.py", line 2011, in evaluate
    raise thread.exc
  File "/Users/user/dev/h2ogpt/src/utils.py", line 340, in run
    self._return = self._target(*self._args, **self._kwargs)
  File "/Users/user/dev/h2ogpt/src/gen.py", line 2114, in generate_with_exceptions
    func(*args, **kwargs)
  File "/Users/user/dev/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/user/dev/lib/python3.10/site-packages/transformers/generation/utils.py", line 1522, in generate
    return self.greedy_search(
  File "/Users/user/dev/lib/python3.10/site-packages/transformers/generation/utils.py", line 2336, in greedy_search
    model_inputs = self.prepare_inputs_for_generation(input_ids, **model_kwargs)
  File "/Users/user/dev/lib/python3.10/site-packages/transformers/models/gpt_neox/modeling_gpt_neox.py", line 723, in prepare_inputs_for_generation
    position_ids = attention_mask.long().cumsum(-1) - 1
RuntimeError: MPS does not support cumsum op with int64 input
```

**Comment by pseudotensor** [comment]
@Mathanraj-Sharma please take a look for MPS.

**Comment by alexng88** [comment]
i m using Mac and I got this error before.  Once I upgrade my MacOS, errors got (now is 13.5beta)

**Comment by nesimtunc** [comment]
Same error with these commands: 
```
python generate.py --base_model=h2oai/h2ogpt-gm-oasst1-en-2048-open-llama-7b --langchain_mode=MyData --score_model=None
python generate.py --base_model=h2oai/h2ogpt-gm-oasst1-en-2048-open-llama-7b --cli=True
python generate.py --base_model=h2oai/h2ogpt-gm-oasst1-en-2048-open-llama-7b --cli=True --load_8bit=True
```

RuntimeError: MPS does not support cumsum op with int64 input

**Comment by Mathanraj-Sharma** [comment]
@wizzard0 @nesimtunc what is the torch version you have? You should install the torch from nightly in order to get MPS support

try

```bash
pip3 install --upgrade --no-deps --force-reinstall --pre torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/nightly/cpu
```

**Comment by wizzard0** [comment]
hmm will check soon

**Comment by wizzard0** [comment]
Yeah that helps! Maybe we can add a temporary torch version check and a warning that it's not expected to work?

**Comment by nesimtunc** [comment]
Yeah that worked for me too! Thanks!

**Comment by pseudotensor** [comment]
Thanks @Mathanraj-Sharma !  Please add to readme.

**Comment by Mathanraj-Sharma** [comment]
Will do it @pseudotensor
