### ISSUE TITLE
Cannot import docs from user_data AttributeError: Can't pickle local object 'Selectable.__init__.<locals>.<lambda>'

### ISSUE THREAD

**Issue by wizzard0** [h2oai/h2ogpt#465]
Added a number of files to user_data

Expected them to import and become available in search

If I add files and restart the h2ogpt the files import fine.

If I add files and click `Update db with new/changed files` i'm receiving the following error:
```
Traceback (most recent call last):
  File "/Users/user/dev/lib/python3.10/site-packages/gradio/routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "/Users/user/dev/lib/python3.10/site-packages/gradio/blocks.py", line 1352, in process_api
    result = await self.call_function(
  File "/Users/user/dev/lib/python3.10/site-packages/gradio/blocks.py", line 1077, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/Users/user/dev/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/Users/user/dev/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/Users/user/dev/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/Users/user/dev/h2ogpt/src/gradio_runner.py", line 2641, in update_and_get_source_files_given_langchain_mode
    db, num_new_sources, new_sources_metadata = make_db(use_openai_embedding=False,
  File "/Users/user/dev/h2ogpt/src/gpt_langchain.py", line 1495, in make_db
    return _make_db(**langchain_kwargs)
  File "/Users/user/dev/h2ogpt/src/gpt_langchain.py", line 1596, in _make_db
    sources1 = path_to_docs(user_path, n_jobs=n_jobs, chunk=chunk, chunk_size=chunk_size,
  File "/Users/user/dev/h2ogpt/src/gpt_langchain.py", line 1322, in path_to_docs
    image_documents = ProgressParallel(n_jobs=n_jobs, verbose=10 if verbose else 0, backend='multiprocessing')(
  File "/Users/user/dev/h2ogpt/src/utils.py", line 807, in __call__
    return Parallel.__call__(self, *args, **kwargs)
  File "/Users/user/dev/lib/python3.10/site-packages/joblib/parallel.py", line 1944, in __call__
    return output if self.return_generator else list(output)
  File "/Users/user/dev/lib/python3.10/site-packages/joblib/parallel.py", line 1587, in _get_outputs
    yield from self._retrieve()
  File "/Users/user/dev/lib/python3.10/site-packages/joblib/parallel.py", line 1691, in _retrieve
    self._raise_error_fast()
  File "/Users/user/dev/lib/python3.10/site-packages/joblib/parallel.py", line 1726, in _raise_error_fast
    error_job.get_result(self.timeout)
  File "/Users/user/dev/lib/python3.10/site-packages/joblib/parallel.py", line 735, in get_result
    return self._return_or_raise()
  File "/Users/user/dev/lib/python3.10/site-packages/joblib/parallel.py", line 753, in _return_or_raise
    raise self._result
AttributeError: Can't pickle local object 'Selectable.__init__.<locals>.<lambda>'
```

**Comment by pseudotensor** [comment]
Would be nice to know what OS etc. you have.

Similar here for someone who has WSL.  Maybe try what I said there: 
https://github.com/h2oai/h2ogpt/issues/396#issuecomment-1626909592

**Comment by pseudotensor** [comment]
Ah, I was able to reproduce. 
1) I have 1 file in `user_path`
2) Load h2oGPT:
```
python generate.py --user_path=user_path
```
3) In shell, add  new files to user_path (various files types, about 6 files)
4) Choose UserData in database
5) Click Update DB with new/changed files on disk

```
 File "/home/jon/h2ogpt/src/gpt_langchain.py", line 1415, in path_to_docs
    documents = ProgressParallel(n_jobs=n_jobs, verbose=10 if verbose else 0, backend='multiprocessing')(
  File "/home/jon/h2ogpt/src/utils.py", line 807, in __call__
    return Parallel.__call__(self, *args, **kwargs)
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/joblib/parallel.py", line 1944, in __call__
    return output if self.return_generator else list(output)
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/joblib/parallel.py", line 1587, in _get_outputs
    yield from self._retrieve()
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/joblib/parallel.py", line 1691, in _retrieve
    self._raise_error_fast()
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/joblib/parallel.py", line 1726, in _raise_error_fast
    error_job.get_result(self.timeout)
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/joblib/parallel.py", line 735, in get_result
    return self._return_or_raise()
  File "/home/jon/miniconda3/envs/h2ollm/lib/python3.10/site-packages/joblib/parallel.py", line 753, in _return_or_raise
    raise self._result
AttributeError: Can't pickle local object 'Selectable.__init__.<locals>.<lambda>'

```

**Comment by wizzard0** [comment]
> Would be nice to know what OS etc. you have.

macOS Ventura 13.4.1 (Apple Silicon)

**Comment by pseudotensor** [comment]
Thanks for stack trace.  I was able to fix it and it also fixed the other error mentioned in Issue #396:
```
TypeError: '>' not supported between instances of 'int' and 'Number'
```

Thanks!

**Comment by pseudotensor** [comment]
If you see again or in some context, let me know!

**Comment by wizzard0** [comment]
Yeah I've also seen that TypeError but just patched it to int() > int() as that seemed like a harmless fix %)
