### ISSUE TITLE
getting error in setting up llama cpu

### ISSUE THREAD

**Issue by Sarabhian** [h2oai/h2ogpt#468]
``
```
(h2ogpt) abhijeet@sarabhian-mod11:~/h2ogpt$ python generate.py --base_model='llama' --prompt_type=wizard2 --score_model=None --langchain_mode='UserData' --user_path=user_path

Traceback (most recent call last):
  File "/home/abhijeet/h2ogpt/generate.py", line 16, in <module>
    entrypoint_main()

  File "/home/abhijeet/h2ogpt/generate.py", line 12, in entrypoint_main
    fire.Fire(main)

  File "/home/abhijeet/anaconda3/envs/h2ogpt/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)

  File "/home/abhijeet/anaconda3/envs/h2ogpt/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/abhijeet/anaconda3/envs/h2ogpt/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/abhijeet/h2ogpt/src/gen.py", line 435, in main
    raise RuntimeError("Asked for LangChain mode but langchain python package cannot be found.")
RuntimeError: Asked for LangChain mode but langchain python package cannot be found.
```
``
I want to create a local copy of the llama I went through the getting started documentation but received this error after running python generate.py, can anyone help me setting up llama cpu version ...please!

**Comment by pseudotensor** [comment]
It means you didn't install the other "optional" packages including langchain one.  Try to install those other ones listed in the readme.

https://github.com/h2oai/h2ogpt#tldr
