### ISSUE TITLE
RuntimeError: Cannot return the results in a contigious 2D array. Probably ef or M is too small

### ISSUE THREAD

**Issue by ba2710** [h2oai/h2ogpt#505]
Thank you for adding collection management features. It's really great! I created a couple of new collections and added PDF's and text files without a problem. However when I started chatting I got the error below. It looks like it's related to chromaDB: 
`AttributeError: module 'chromadb.errors' has no attribute 'NotEnoughElementsException'`

I also loaded the h2ogpt on another browser from my LAN and didn't see the new collections. How do I make them persistent across sessions? Thank you! 

```
`Traceback (most recent call last):
  File "C:\Users\basem\miniconda3\envs\h2ogpt\lib\site-packages\langchain\vectorstores\chroma.py", line 121, in __query_collection
    return self._collection.query(
  File "C:\Users\basem\miniconda3\envs\h2ogpt\lib\site-packages\chromadb\api\models\Collection.py", line 230, in query
    return self._client._query(
  File "C:\Users\basem\miniconda3\envs\h2ogpt\lib\site-packages\chromadb\api\local.py", line 439, in _query
    uuids, distances = self._db.get_nearest_neighbors(
  File "C:\Users\basem\miniconda3\envs\h2ogpt\lib\site-packages\chromadb\db\clickhouse.py", line 591, in get_nearest_neighbors
    uuids, distances = index.get_nearest_neighbors(embeddings, n_results, ids)
  File "C:\Users\basem\miniconda3\envs\h2ogpt\lib\site-packages\chromadb\db\index\hnswlib.py", line 296, in get_nearest_neighbors
    database_labels, distances = self._index.knn_query(
RuntimeError: Cannot return the results in a contigious 2D array. Probably ef or M is too small

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\basem\miniconda3\envs\h2ogpt\lib\site-packages\gradio\routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\basem\miniconda3\envs\h2ogpt\lib\site-packages\gradio\blocks.py", line 1352, in process_api
    result = await self.call_function(
  File "C:\Users\basem\miniconda3\envs\h2ogpt\lib\site-packages\gradio\blocks.py", line 1093, in call_function
    prediction = await utils.async_iteration(iterator)
  File "C:\Users\basem\miniconda3\envs\h2ogpt\lib\site-packages\gradio\utils.py", line 341, in async_iteration
    return await iterator.__anext__()
  File "C:\Users\basem\miniconda3\envs\h2ogpt\lib\site-packages\gradio\utils.py", line 334, in __anext__
    return await anyio.to_thread.run_sync(
  File "C:\Users\basem\miniconda3\envs\h2ogpt\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\basem\miniconda3\envs\h2ogpt\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\basem\miniconda3\envs\h2ogpt\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\basem\miniconda3\envs\h2ogpt\lib\site-packages\gradio\utils.py", line 317, in run_sync_iterator_async
    return next(iterator)
  File "C:\Users\basem\Dev\h2ogpt\src\gradio_runner.py", line 1648, in bot
    for res in get_response(fun1, history):
  File "C:\Users\basem\Dev\h2ogpt\src\gradio_runner.py", line 1603, in get_response
    for output_fun in fun1():
  File "C:\Users\basem\Dev\h2ogpt\src\gen.py", line 1572, in evaluate
    for r in run_qa_db(query=instruction,
  File "C:\Users\basem\Dev\h2ogpt\src\gpt_langchain.py", line 1987, in _run_qa_db
    docs, chain, scores, use_context, have_any_docs = get_chain(**sim_kwargs)
  File "C:\Users\basem\Dev\h2ogpt\src\gpt_langchain.py", line 2254, in get_chain
    docs_with_score = db.similarity_search_with_score(query, k=k_db, **filter_kwargs)[
  File "C:\Users\basem\miniconda3\envs\h2ogpt\lib\site-packages\langchain\vectorstores\chroma.py", line 230, in similarity_search_with_score
    results = self.__query_collection(
  File "C:\Users\basem\miniconda3\envs\h2ogpt\lib\site-packages\langchain\utils.py", line 53, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\basem\miniconda3\envs\h2ogpt\lib\site-packages\langchain\vectorstores\chroma.py", line 128, in __query_collection
    except chromadb.errors.NotEnoughElementsException:
AttributeError: module 'chromadb.errors' has no attribute 'NotEnoughElementsException'`
```

**Comment by pseudotensor** [comment]
Yes, the `RuntimeError: Cannot return the results in a contigious 2D array. Probably ef or M is too small` is annoying.

https://github.com/hwchase17/langchain/issues/3665

**Comment by Cupiii** [comment]
I also get this error with 200 Documents uploaded. Does anyone know what to do?

**Comment by pseudotensor** [comment]
A possible work-around is to set k_db to much smaller number than 100-1000, i.e. maybe 10 in src/gpt_langchain.py.

**Comment by enriquedecote** [comment]
I'm on the same boat, however, this behaviour only started with the last commit.

**Comment by pseudotensor** [comment]
@enriquedecote which commit(s)?  Do you think something got worse?  I updated langchain a few days ago, but otherwise nothing should be causing this directly in h2oGPT AFAIK.

If anyone finds a reproducible example, would be good.  So far it seems to be not reproducible, and happens or not for exactly same steps/PDF.  The one time I hit it a few days ago I did exact same steps, and it didn't do it.

**Comment by enriquedecote** [comment]
@pseudotensor The last pull that I know worked on my local docs was 0fec9b83. Today I only pulled and did not add/remove any doc nor made any code changes.

**Comment by Cupiii** [comment]
With k_db set to 10 it worked for me, but will try again tomorrow.

**Comment by pseudotensor** [comment]
@ba2710 I added a work-around for that issue, but you have the wrong langchain version.

**Comment by Cupiii** [comment]
Great, Thank you!
