### ISSUE TITLE
Issue running client API

### ISSUE THREAD

**Issue by naumfujimori** [h2oai/h2ogpt#519]
Hi guys , Ive been testing H2ogpt for while and notice that from one or 2 weeks ago the client api stopped after some git pull.

Running api client on Windows 
Successfully installed gradio-client-0.2.10

Source code :
from gradio_client import Client
import ast

HOST_URL = "https://xxx.xx.xx.cloud"
client = Client(HOST_URL)

kwargs = dict(instruction_nochat='Who are you?')
res = client.predict(str(dict(kwargs)), api_name='/submit_nochat_api')

response = ast.literal_eval(res)['response']
print(response)
port used is 443 and is functional
result:

C:\CMD\LLM\lab\h2ogpt\tests>python api.py
Loaded as API: https://xxx.xx.xx.cloud/ ✔
Traceback (most recent call last):
  File "C:\Users\CMD\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\gradio_client\client.py", line 595, in _get_config
    config = json.loads(result.group(1))  # type: ignore
AttributeError: 'NoneType' object has no attribute 'group'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\CMD\LLM\lab\h2ogpt\tests\api.py", line 5, in <module>
    client = Client(HOST_URL)
  File "C:\Users\CMD\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\gradio_client\client.py", line 127, in __init__
    self.config = self._get_config()
  File "C:\Users\CMD\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\gradio_client\client.py", line 597, in _get_config
    raise ValueError(
ValueError: Could not get Gradio config from: https://xxx.xx.xx.cloud/

C:\CMD\LLM\lab\h2ogpt\tests>

**Comment by pseudotensor** [comment]
Hi.  We have extensive tests for the gradio client.  I cannot tell what is wrong in above, except that "result" is None, but I don't know what that is about.

You'd probably have to share code api.py.

**Comment by pseudotensor** [comment]
stale
