### ISSUE TITLE
Error with Charset Normalizer

### ISSUE THREAD

**Issue by loginlogout3** [h2oai/h2ogpt#540]
`Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/envs/h2ogpt/lib/python3.10/site-packages/requests/compat.py", line 11, in <module>
    import chardet
ModuleNotFoundError: No module named 'chardet'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/landonaune/Documents/H2Ogpt/h2ogpt/generate.py", line 8, in <module>
    from src.gen import main
  File "/Users/landonaune/Documents/H2Ogpt/h2ogpt/src/gen.py", line 15, in <module>
    import requests
  File "/opt/homebrew/anaconda3/envs/h2ogpt/lib/python3.10/site-packages/requests/__init__.py", line 45, in <module>
    from .exceptions import RequestsDependencyWarning
  File "/opt/homebrew/anaconda3/envs/h2ogpt/lib/python3.10/site-packages/requests/exceptions.py", line 9, in <module>
    from .compat import JSONDecodeError as CompatJSONDecodeError
  File "/opt/homebrew/anaconda3/envs/h2ogpt/lib/python3.10/site-packages/requests/compat.py", line 13, in <module>
    import charset_normalizer as chardet
  File "/opt/homebrew/anaconda3/envs/h2ogpt/lib/python3.10/site-packages/charset_normalizer/__init__.py", line 23, in <module>
    from charset_normalizer.api import from_fp, from_path, from_bytes, normalize
  File "/opt/homebrew/anaconda3/envs/h2ogpt/lib/python3.10/site-packages/charset_normalizer/api.py", line 10, in <module>
    from charset_normalizer.md import mess_ratio
  File "charset_normalizer/md.py", line 5, in <module>
ImportError: cannot import name 'COMMON_SAFE_ASCII_CHARACTERS' from 'charset_normalizer.constant' (/opt/homebrew/anaconda3/envs/h2ogpt/lib/python3.10/site-packages/charset_normalizer/constant.py)`

This is when trying to run `python generate.py --base_model='llama' --prompt_type=wizard2 --score_model=None --langchain_mode='UserData' --user_path=user_path` as shown in MacOS install guide.

**Comment by pseudotensor** [comment]
Try this?  Let me know if it works and I can add to mac issues:

https://github.com/huggingface/transformers/issues/21858#issuecomment-1469265495


```
System Info
macbook air m2 with anaconda, python 3.9

I got a similar bug bug
ImportError: cannot import name 'COMMON_SAFE_ASCII_CHARACTERS' from 'charset_normalizer.constant'

When I encountered this I used:

pip install chardet
```

**Comment by Mathanraj-Sharma** [comment]
@pseudotensor I am taking this. 

@loginlogout3 are you on Mac (M1/M2) or on Mac Intel?

**Comment by Mathanraj-Sharma** [comment]
Closing since no activity in this ticket, feel free to reopen it if required!
