### ISSUE TITLE
Error related to Chroma

### ISSUE THREAD

**Issue by pktCoder** [h2oai/h2ogpt#548]
Downloaded the repo and install some python modules but when running, got error about Chroma.  
Any idea what may be wrong here.

```
python generate.py --base_model=h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3 --hf_embedding_model=sentence-transformers/all-MiniLM-L6-v2 --score_model=None --load_4bit=True --langchain_mode='UserData'
...
Traceback (most recent call last):
  File "/home/ji03/pkgs/h2ogpt/src/gradio_runner.py", line 2596, in update_user_db
    return _update_user_db(file, db1s=db1s, chunk=chunk, chunk_size=chunk_size,
  File "/home/ji03/pkgs/h2ogpt/src/gradio_runner.py", line 2763, in _update_user_db
    db = get_db(sources, use_openai_embedding=use_openai_embedding,
  File "/home/ji03/pkgs/h2ogpt/src/gpt_langchain.py", line 103, in get_db
    db = Chroma.from_documents(documents=sources,
  File "/home/ji03/anaconda3/envs/h2ogpt/lib/python3.10/site-packages/langchain/vectorstores/chroma.py", line 578, in from_documents
    return cls.from_texts(
  File "/home/ji03/anaconda3/envs/h2ogpt/lib/python3.10/site-packages/langchain/vectorstores/chroma.py", line 533, in from_texts
    chroma_collection = cls(
  File "/home/ji03/anaconda3/envs/h2ogpt/lib/python3.10/site-packages/langchain/vectorstores/chroma.py", line 109, in __init__
    self._client = chromadb.Client(_client_settings)
  File "/home/ji03/anaconda3/envs/h2ogpt/lib/python3.10/site-packages/chromadb/__init__.py", line 107, in Client
    system = System(settings)
  File "/home/ji03/anaconda3/envs/h2ogpt/lib/python3.10/site-packages/chromadb/config.py", line 175, in __init__
    if settings[key] is not None:
  File "/home/ji03/anaconda3/envs/h2ogpt/lib/python3.10/site-packages/chromadb/config.py", line 110, in __getitem__
    raise ValueError(LEGACY_ERROR)
ValueError: You are using a deprecated configuration of Chroma.

If you do not have data you wish to migrate, you only need to change how you construct
your Chroma client. Please see the "New Clients" section of https://docs.trychroma.com/migration.
________________________________________________________________________________________________

If you do have data you wish to migrate, we have a migration tool you can use in order to
migrate your data to the new Chroma architecture.
Please `pip install chroma-migrate` and run `chroma-migrate` to migrate your data and then
change how you construct your Chroma client.

See https://docs.trychroma.com/migration for more information or join our discord at https://discord.gg/8g5FESbj for help!
```

Thanks

**Comment by pseudotensor** [comment]
Looks like your dependencies are wrong.  You have chroma 0.4.  You need to use the exact dependencies in h2oGPT requirements in fresh env.
