### ISSUE TITLE
GPU NameError: Field name "stream" shadows a BaseModel attribute; use a different field name with "alias='stream'".

### ISSUE THREAD

**Issue by wozniaczek123** [h2oai/h2ogpt#555]
h2o test\h2ogpt>python generate.py --base_model=h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3 --langchain_mode=UserData --score_model=None --load_4bit=True
Using Model h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3
Traceback (most recent call last):
  File "C:\Users\Jakub\Documents\h2o test\h2ogpt\generate.py", line 16, in <module>
    entrypoint_main()
  File "C:\Users\Jakub\Documents\h2o test\h2ogpt\generate.py", line 12, in entrypoint_main
    fire.Fire(main)
  File "C:\Users\Jakub\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jakub\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\fire\core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jakub\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\fire\core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jakub\Documents\h2o test\h2ogpt\src\gen.py", line 658, in main
    from gpt_langchain import prep_langchain, get_some_dbs_from_hf
  File "C:\Users\Jakub\Documents\h2o test\h2ogpt\src\gpt_langchain.py", line 289, in <module>
    class GradioInference(LLM):
  File "pydantic\main.py", line 186, in pydantic.main.ModelMetaclass.__new__
  File "pydantic\utils.py", line 167, in pydantic.utils.validate_field_name

NameError: Field name "stream" shadows a BaseModel attribute; use a different field name with "alias='stream'".

C:\Users\Jakub\Documents\h2o test\h2ogpt>pip install --upgrade langchain

**Comment by pseudotensor** [comment]
@wozniaczek123 looks like you are using python3.11, I don't know effect of that.  I don't see the same error in windows.  I just revamped instructions.  I suspect that you have wrong versions of packages compared to in the requirements files.

**Comment by bbrosint** [comment]
Can confirm that this error is appearing by installing the latest langchain version via `pip install langchain` 

Using the instructions and installing with `pip install -r reqs_optional/requirements_optional_langchain.txt` solved it for me. Maybe it helps OP too?

**Comment by wozniaczek123** [comment]
I will check if it works tomorrow.

**Comment by pseudotensor** [comment]
@bbrosint did you need to do that because you had unfresh env, or did you find that even despite having fresh env, eventually langchain version was wrong and you had to go back and repeat that line?  Thanks!

**Comment by wozniaczek123** [comment]
Thanks @bbrosint it helped.

**Comment by bbrosint** [comment]
@pseudotensor  I had new env and did not install langchain at first. Then wanted to implement files and simply installed with `pip install langchain` and got the same error as @wozniaczek123 (that's how I guessed they must have done the same). 

Then I read your hint that the most latest langchain version might not work and headed to the installation manual,  uninstalled the latest langchain package and reinstalled the dependencies with command given in the manual. And it works flawlessly :+1:

**Comment by pseudotensor** [comment]
Got it, thanks for explaining!
