### ISSUE TITLE
After pulling latest code the inference throwing error :Error LlamaCpp.stream() got an unexpected keyword argument 'input'

### ISSUE THREAD

**Issue by slavag** [h2oai/h2ogpt#623]
Startup log :
```
Using Model llama
Prep: persist_directory=db_dir_UserData exists, using
Prep: persist_directory=db_dir_TestData exists, using
Starting get_model: llama 
Could not determine --max_seq_len, setting to 2048.  Pass if not correct
llama.cpp: loading model from /Users/slava/Documents/Development/private/AI/Models/TheBloke/llama2-7b-GGML/llama-2-7b-chat.ggmlv3.q4_1.bin
llama_model_load_internal: format     = ggjt v3 (latest)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 2048
llama_model_load_internal: n_embd     = 4096
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 32
llama_model_load_internal: n_head_kv  = 32
llama_model_load_internal: n_layer    = 32
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: n_gqa      = 1
llama_model_load_internal: rnorm_eps  = 1.0e-06
llama_model_load_internal: n_ff       = 11008
llama_model_load_internal: freq_base  = 10000.0
llama_model_load_internal: freq_scale = 1
llama_model_load_internal: ftype      = 3 (mostly Q4_1)
llama_model_load_internal: model size = 7B
llama_model_load_internal: ggml ctx size =    0.08 MB
llama_model_load_internal: mem required  = 4415.35 MB (+ 1024.00 MB per state)
llama_new_context_with_model: kv self size  = 1024.00 MB
ggml_metal_init: allocating
ggml_metal_init: using MPS
ggml_metal_init: loading '/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/llama_cpp/ggml-metal.metal'
ggml_metal_init: loaded kernel_add                            0x2ab6eb590
ggml_metal_init: loaded kernel_add_row                        0x2ab6eb9f0
ggml_metal_init: loaded kernel_mul                            0x2ab6ebc50
ggml_metal_init: loaded kernel_mul_row                        0x2ab6ebeb0
ggml_metal_init: loaded kernel_scale                          0x2ab6ec110
ggml_metal_init: loaded kernel_silu                           0x2aff06130
ggml_metal_init: loaded kernel_relu                           0x2aff06550
ggml_metal_init: loaded kernel_gelu                           0x2aff06970
ggml_metal_init: loaded kernel_soft_max                       0x2aff06f20
ggml_metal_init: loaded kernel_diag_mask_inf                  0x2aff07340
ggml_metal_init: loaded kernel_get_rows_f16                   0x2aff07760
ggml_metal_init: loaded kernel_get_rows_q4_0                  0x2aff07e50
ggml_metal_init: loaded kernel_get_rows_q4_1                  0x2aff083d0
ggml_metal_init: loaded kernel_get_rows_q2_K                  0x2aff08950
ggml_metal_init: loaded kernel_get_rows_q3_K                  0x2aff08ed0
ggml_metal_init: loaded kernel_get_rows_q4_K                  0x2aff09450
ggml_metal_init: loaded kernel_get_rows_q5_K                  0x2aff099d0
ggml_metal_init: loaded kernel_get_rows_q6_K                  0x2aff09f50
ggml_metal_init: loaded kernel_rms_norm                       0x2aff0a510
ggml_metal_init: loaded kernel_norm                           0x2aff0ad50
ggml_metal_init: loaded kernel_mul_mat_f16_f32                0x2aff0b170
ggml_metal_init: loaded kernel_mul_mat_q4_0_f32               0x2aff0b730
ggml_metal_init: loaded kernel_mul_mat_q4_1_f32               0x17f640580
ggml_metal_init: loaded kernel_mul_mat_q2_K_f32               0x17f641f40
ggml_metal_init: loaded kernel_mul_mat_q3_K_f32               0x164a26d80
ggml_metal_init: loaded kernel_mul_mat_q4_K_f32               0x164a27580
ggml_metal_init: loaded kernel_mul_mat_q5_K_f32               0x164a27c40
ggml_metal_init: loaded kernel_mul_mat_q6_K_f32               0x164a28760
ggml_metal_init: loaded kernel_rope                           0x164a28ca0
ggml_metal_init: loaded kernel_alibi_f32                      0x164a29580
ggml_metal_init: loaded kernel_cpy_f32_f16                    0x164a29e30
ggml_metal_init: loaded kernel_cpy_f32_f32                    0x2a19f8870
ggml_metal_init: loaded kernel_cpy_f16_f16                    0x2a19f7cc0
ggml_metal_init: recommendedMaxWorkingSetSize = 21845.34 MB
ggml_metal_init: hasUnifiedMemory             = true
ggml_metal_init: maxTransferRate              = built-in GPU
llama_new_context_with_model: max tensor size =    78.12 MB
ggml_metal_add_buffer: allocated 'data            ' buffer, size =  4017.70 MB, ( 4018.16 / 21845.34)
ggml_metal_add_buffer: allocated 'eval            ' buffer, size =    10.00 MB, ( 4028.16 / 21845.34)
ggml_metal_add_buffer: allocated 'kv              ' buffer, size =  1026.00 MB, ( 5054.16 / 21845.34)
ggml_metal_add_buffer: allocated 'scr0            ' buffer, size =   228.00 MB, ( 5282.16 / 21845.34)
ggml_metal_add_buffer: allocated 'scr1            ' buffer, size =   160.00 MB, ( 5442.16 / 21845.34)
AVX = 0 | AVX2 = 0 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 0 | NEON = 1 | ARM_FMA = 1 | F16C = 0 | FP16_VA = 1 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 0 | VSX = 0 | 
Model {'base_model': 'llama', 'tokenizer_base_model': '', 'lora_weights': '', 'inference_server': '', 'prompt_type': 'llama2', 'prompt_dict': {'promptA': '', 'promptB': '', 'PreInstruct': '<s>[INST] ', 'PreInput': None, 'PreResponse': '[/INST]', 'terminate_response': ['[INST]', '</s>'], 'chat_sep': ' ', 'chat_turn_sep': ' </s>', 'humanstr': '[INST]', 'botstr': '[/INST]', 'generates_leading_space': False, 'system_prompt': None}}
Running on local URL:  http://0.0.0.0:7860
```
Error log :
```
thread exception: (<class 'TypeError'>, TypeError("LlamaCpp.stream() got an unexpected keyword argument 'input'"), <traceback object at 0x2ae44b500>)
make stop: (<class 'TypeError'>, TypeError("LlamaCpp.stream() got an unexpected keyword argument 'input'"), <traceback object at 0x2ae44b500>)
hit stop
Traceback (most recent call last):
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/gradio/routes.py", line 442, in run_predict
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/gradio/blocks.py", line 1389, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/gradio/blocks.py", line 1108, in call_function
    prediction = await utils.async_iteration(iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/gradio/utils.py", line 346, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/gradio/utils.py", line 339, in __anext__
    return await anyio.to_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/gradio/utils.py", line 322, in run_sync_iterator_async
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/gradio/utils.py", line 691, in gen_wrapper
    yield from f(*args, **kwargs)
  File "/Users/slava/Documents/Development/private/AI/h2ogpt/src/gradio_runner.py", line 1763, in bot
    for res in get_response(fun1, history):
  File "/Users/slava/Documents/Development/private/AI/h2ogpt/src/gradio_runner.py", line 1714, in get_response
    for output_fun in fun1():
  File "/Users/slava/Documents/Development/private/AI/h2ogpt/src/gen.py", line 1810, in evaluate
    for r in run_qa_db(
  File "/Users/slava/Documents/Development/private/AI/h2ogpt/src/gpt_langchain.py", line 2499, in _run_qa_db
    raise thread.exc
  File "/Users/slava/Documents/Development/private/AI/h2ogpt/src/utils.py", line 388, in run
    self._return = self._target(*self._args, **self._kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/langchain/chains/base.py", line 243, in __call__
    raise e
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/langchain/chains/base.py", line 237, in __call__
    self._call(inputs, run_manager=run_manager)
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/langchain/chains/combine_documents/base.py", line 106, in _call
    output, extra_return_dict = self.combine_docs(
                                ^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/langchain/chains/combine_documents/stuff.py", line 165, in combine_docs
    return self.llm_chain.predict(callbacks=callbacks, **inputs), {}
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/langchain/chains/llm.py", line 252, in predict
    return self(kwargs, callbacks=callbacks)[self.output_key]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/langchain/chains/base.py", line 243, in __call__
    raise e
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/langchain/chains/base.py", line 237, in __call__
    self._call(inputs, run_manager=run_manager)
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/langchain/chains/llm.py", line 92, in _call
    response = self.generate([inputs], run_manager=run_manager)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/langchain/chains/llm.py", line 102, in generate
    return self.llm.generate_prompt(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/langchain/llms/base.py", line 186, in generate_prompt
    return self.generate(prompt_strings, stop=stop, callbacks=callbacks, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/langchain/llms/base.py", line 279, in generate
    output = self._generate_helper(
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/langchain/llms/base.py", line 223, in _generate_helper
    raise e
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/langchain/llms/base.py", line 210, in _generate_helper
    self._generate(
  File "/Users/slava/.pyenv/versions/3.11.3/lib/python3.11/site-packages/langchain/llms/base.py", line 602, in _generate
    self._call(prompt, stop=stop, run_manager=run_manager, **kwargs)
  File "/Users/slava/Documents/Development/private/AI/h2ogpt/src/gpt4all_llm.py", line 333, in _call
    for token in self.stream(input=prompt, stop=stop):
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: LlamaCpp.stream() got an unexpected keyword argument 'input'
```

**Comment by pseudotensor** [comment]
You need to update your dependencies so newer langchain used
