### ISSUE TITLE
Can't add personal data for inference

### ISSUE THREAD

**Issue by ClaudiuFilip110** [h2oai/h2ogpt#628]
command used: 
```
python generate.py --base_model=h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3 --load_8bit=True --langchain_mode=MyData --prompt_type=human_bot --share=False --gradio_offline_level=1 --score_model=None
```
Tried personal files, then tried the same file used in [this tutorial](https://www.youtube.com/watch?v=Coj72EzmX20&t=4s&ab_channel=RobMulla) used in the README.

The traceback call is similar to #620, but I can do inference on the model. The error appears when I try to add [this site](https://learn.neumann.edu/neupress/top-10-rollercoasters-in-pa-and-the-surrounding-area#:~:text=Want%20to%20feel%20the%20need,a%20track%20with%20unique%20twists.) to *MyData*.

Traceback

Traceback (most recent call last):
  File "C:\Users\Claudiu\miniconda3\envs\h2o\lib\site-packages\transformers\modeling_utils.py", line 463, in load_state_dict
    return torch.load(checkpoint_file, map_location="cpu")
  File "C:\Users\Claudiu\miniconda3\envs\h2o\lib\site-packages\torch\serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "C:\Users\Claudiu\miniconda3\envs\h2o\lib\site-packages\torch\serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Claudiu\miniconda3\envs\h2o\lib\site-packages\transformers\modeling_utils.py", line 467, in load_state_dict
    if f.read(7) == "version":
  File "C:\Users\Claudiu\miniconda3\envs\h2o\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 1821: character maps to <undefined>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Dev\h2ogpt\src\gradio_runner.py", line 2764, in update_user_db
    return _update_user_db(file, db1s=db1s, chunk=chunk, chunk_size=chunk_size,
  File "C:\Dev\h2ogpt\src\gradio_runner.py", line 2920, in _update_user_db
    db = get_db(sources, use_openai_embedding=use_openai_embedding,
  File "C:\Dev\h2ogpt\src\gpt_langchain.py", line 76, in get_db
    embedding = get_embedding(use_openai_embedding, hf_embedding_model=hf_embedding_model)
  File "C:\Dev\h2ogpt\src\gpt_langchain.py", line 290, in get_embedding
    embedding = HuggingFaceInstructEmbeddings(model_name=hf_embedding_model,
  File "C:\Users\Claudiu\miniconda3\envs\h2o\lib\site-packages\langchain\embeddings\huggingface.py", line 136, in __init__
    self.client = INSTRUCTOR(
  File "C:\Users\Claudiu\miniconda3\envs\h2o\lib\site-packages\sentence_transformers\SentenceTransformer.py", line 95, in __init__
    modules = self._load_sbert_model(model_path)
  File "C:\Users\Claudiu\miniconda3\envs\h2o\lib\site-packages\InstructorEmbedding\instructor.py", line 474, in _load_sbert_model
    module = module_class.load(os.path.join(model_path, module_config['path']))
  File "C:\Users\Claudiu\miniconda3\envs\h2o\lib\site-packages\InstructorEmbedding\instructor.py", line 306, in load
    return INSTRUCTOR_Transformer(model_name_or_path=input_path, **config)
  File "C:\Users\Claudiu\miniconda3\envs\h2o\lib\site-packages\InstructorEmbedding\instructor.py", line 240, in __init__
    self._load_model(self.model_name_or_path, config, cache_dir, **model_args)
  File "C:\Users\Claudiu\miniconda3\envs\h2o\lib\site-packages\sentence_transformers\models\Transformer.py", line 47, in _load_model
    self._load_t5_model(model_name_or_path, config, cache_dir)
  File "C:\Users\Claudiu\miniconda3\envs\h2o\lib\site-packages\sentence_transformers\models\Transformer.py", line 55, in _load_t5_model
    self.auto_model = T5EncoderModel.from_pretrained(model_name_or_path, config=config, cache_dir=cache_dir)
  File "C:\Users\Claudiu\miniconda3\envs\h2o\lib\site-packages\transformers\modeling_utils.py", line 2604, in from_pretrained
    state_dict = load_state_dict(resolved_archive_file)
  File "C:\Users\Claudiu\miniconda3\envs\h2o\lib\site-packages\transformers\modeling_utils.py", line 479, in load_state_dict
    raise OSError(
OSError: Unable to load weights from pytorch checkpoint file for 'C:\Users\Claudiu/.cache\torch\sentence_transformers\hkunlp_instructor-large\pytorch_model.bin' at 'C:\Users\Claudiu/.cache\torch\sentence_transformers\hkunlp_instructor-large\pytorch_model.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.

**Comment by pseudotensor** [comment]
Please try the windows installer version, to help eliminate potential installation issues.

**Comment by pseudotensor** [comment]
Or try to use GGML, which is improved experience in main now.
