### ISSUE TITLE
LLama bin file not a valid json

### ISSUE THREAD

**Issue by fl0x2208** [h2oai/h2ogpt#658]
When i run following command i get this error (running on MAC)

python3 generate.py --base_model=llama-2-7b-chat.ggmlv3.q8_0.bin --prompt_type=llama2

/Library/Python/3.8/site-packages/urllib3/__init__.py:34: NotOpenSSLWarning: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Auto set langchain_mode=LLM.  Could use MyData instead.  To allow UserData to pull files from disk, set user_path or langchain_mode_paths, and ensure allow_upload_to_user_data=True
Using Model llama-2-7b-chat.ggmlv3.q8_0.bin
Prep: persist_directory=db_dir_UserData exists, using
Starting get_model: llama-2-7b-chat.ggmlv3.q8_0.bin 
Traceback (most recent call last):
  File "/Users/r.a.w/Library/Python/3.8/lib/python/site-packages/transformers/configuration_utils.py", line 702, in _get_config_dict
    config_dict = cls._dict_from_json_file(resolved_config_file)
  File "/Users/r.a.w/Library/Python/3.8/lib/python/site-packages/transformers/configuration_utils.py", line 793, in _dict_from_json_file
    text = reader.read()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 28: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "generate.py", line 16, in <module>
    entrypoint_main()
  File "generate.py", line 12, in entrypoint_main
    H2O_Fire(main)
  File "/Users/r.a.w/Desktop/tools/h2ogpt/src/utils.py", line 57, in H2O_Fire
    fire.Fire(component=component, command=args)
  File "/Users/r.a.w/Library/Python/3.8/lib/python/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/Users/r.a.w/Library/Python/3.8/lib/python/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/Users/r.a.w/Library/Python/3.8/lib/python/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/Users/r.a.w/Desktop/tools/h2ogpt/src/gen.py", line 885, in main
    model0, tokenizer0, device = get_model(reward_type=False,
  File "/Users/r.a.w/Desktop/tools/h2ogpt/src/gen.py", line 1229, in get_model
    config, _, max_seq_len = get_config(base_model, **config_kwargs, raise_exception=False)
  File "/Users/r.a.w/Desktop/tools/h2ogpt/src/gen.py", line 950, in get_config
    config = AutoConfig.from_pretrained(base_model, use_auth_token=use_auth_token,
  File "/Users/r.a.w/Library/Python/3.8/lib/python/site-packages/transformers/models/auto/configuration_auto.py", line 983, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/Users/r.a.w/Library/Python/3.8/lib/python/site-packages/transformers/configuration_utils.py", line 617, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/Users/r.a.w/Library/Python/3.8/lib/python/site-packages/transformers/configuration_utils.py", line 705, in _get_config_dict
    raise EnvironmentError(
OSError: It looks like the config file at 'llama-2-7b-chat.ggmlv3.q8_0.bin' is not a valid JSON file.

**Comment by pseudotensor** [comment]
That's not the correct format.  `base_model` is reserved for HF models or 'llama' for your case.  See docs, but like:

```
python generate.py --prompt_type=llama2
```

is enough in your case.  See: https://github.com/h2oai/h2ogpt/blob/main/docs/FAQ.md#adding-models
