### ISSUE TITLE
broken Authentication

### ISSUE THREAD

**Issue by ValkaTR** [h2oai/h2ogpt#676]
Something went wrong for me unfortunately.

Made a fresh first install. All according to instructions. CPU mode.

When I tried to login for the first time I get error message in web UI:

```
[Errno 2] No such file or directory: 'auth.json'
```

If I create an empty 'auth.json' file and try to login again, it will make a backup, remove original 'auth.json' file and report error again.

In the console I have following error messages:

```
Traceback (most recent call last):
  File "/home/valka/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/valka/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/gradio/blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "/home/valka/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/gradio/blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/valka/.local/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/valka/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/valka/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/valka/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/gradio/utils.py", line 706, in wrapper
    response = f(*args, **kwargs)
  File "/home/valka/h2ogpt/src/gradio_runner.py", line 1529, in login
    authorized1 = authf(username1, password1)
  File "/home/valka/h2ogpt/src/gradio_runner.py", line 338, in auth_func
    save_auth_dict(auth_dict, auth_filename)
  File "/home/valka/h2ogpt/src/gradio_runner.py", line 1628, in save_auth_dict
    shutil.copy(auth_filename, backup_file)
  File "/home/valka/miniconda3/envs/h2ogpt/lib/python3.10/shutil.py", line 417, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/valka/miniconda3/envs/h2ogpt/lib/python3.10/shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'auth.json'
```

I tried passing --auth argument like this:

```
python generate.py --base_model='llama' --prompt_type=wizard_lm --score_model=None --langchain_mode='UserData' --user_path=user_path --model_path_llama=wizardlm-30b-uncensored.ggmlv3.q6_K.bin --root_path=/h2ogpt --auth="[('jon', 'password')]"
```

but then it won't start giving following error:

```
Traceback (most recent call last):
  File "/home/valka/h2ogpt/generate.py", line 16, in <module>
    entrypoint_main()
  File "/home/valka/h2ogpt/generate.py", line 12, in entrypoint_main
    H2O_Fire(main)
  File "/home/valka/h2ogpt/src/utils.py", line 57, in H2O_Fire
    fire.Fire(component=component, command=args)
  File "/home/valka/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/valka/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/valka/miniconda3/envs/h2ogpt/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/valka/h2ogpt/src/gen.py", line 930, in main
    go_gradio(**locals())
  File "/home/valka/h2ogpt/src/gradio_runner.py", line 388, in go_gradio
    for k, v in zip(kwargs['auth'][0], kwargs['auth'][1]):
IndexError: list index out of range
```

Please help <3

**Comment by pseudotensor** [comment]
These were fixed about a day before your github posting.  Please try again with latest main.

**Comment by ValkaTR** [comment]
alright. it really did resolved the issue. thanks!
