### ISSUE TITLE
unable to use GPU compute power to generate results

### ISSUE THREAD

**Issue by bsudhanva** [h2oai/h2ogpt#687]
_when I run this command_

(h2ogpt) C:\Users\username\h2ogpt>python generate.py --base_model='llama' --prompt_type=llama2 --score_model=None --langchain_mode='UserData' --user_path=user_path

_I get the following output_

`Using Model llama
Prep: persist_directory=db_dir_UserData exists, user_path=user_path passed, adding any changed or new documents
0it [00:00, ?it/s]
0it [00:00, ?it/s]
Loaded 0 sources for potentially adding to UserData
Prep: persist_directory= does not exist, regenerating
Did not generate db since no sources
Prep: persist_directory= does not exist, regenerating
Did not generate db since no sources
Starting get_model: llama
Could not determine --max_seq_len, setting to 2048.  Pass if not correct
Already have llama-2-7b-chat.ggmlv3.q8_0.bin from url https://huggingface.co/TheBloke/Llama-2-7B-Chat-GGML/resolve/main/llama-2-7b-chat.ggmlv3.q8_0.bin, delete file if invalid
ggml_init_cublas: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 4060 Laptop GPU, compute capability 8.9
llama.cpp: loading model from llama-2-7b-chat.ggmlv3.q8_0.bin
llama_model_load_internal: format     = ggjt v3 (latest)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 2048
llama_model_load_internal: n_embd     = 4096
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 32
llama_model_load_internal: n_layer    = 32
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: freq_base  = 10000.0
llama_model_load_internal: freq_scale = 1
llama_model_load_internal: ftype      = 7 (mostly Q8_0)
llama_model_load_internal: n_ff       = 11008
llama_model_load_internal: model size = 7B
llama_model_load_internal: ggml ctx size =    0.08 MB
llama_model_load_internal: using CUDA for GPU acceleration
llama_model_load_internal: mem required  = 1804.89 MB (+ 1026.00 MB per state)
llama_model_load_internal: allocating batch_size x (512 kB + n_ctx x 128 B) = 384 MB VRAM for the scratch buffer
llama_model_load_internal: offloading 32 repeating layers to GPU
llama_model_load_internal: offloading non-repeating layers to GPU
llama_model_load_internal: offloading v cache to GPU
llama_model_load_internal: offloading k cache to GPU
llama_model_load_internal: offloaded 35/35 layers to GPU
llama_model_load_internal: total VRAM used: 8106 MB
llama_new_context_with_model: kv self size  = 1024.00 MB
AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | VSX = 0 |
Model {'base_model': 'llama', 'tokenizer_base_model': '', 'lora_weights': '', 'inference_server': '', 'prompt_type': 'llama2', 'prompt_dict': {'promptA': '', 'promptB': '', 'PreInstruct': '<s>[INST] ', 'PreInput': None, 'PreResponse': '[/INST]', 'terminate_response': ['[INST]', '</s>'], 'chat_sep': ' ', 'chat_turn_sep': ' </s>', 'humanstr': '[INST]', 'botstr': '[/INST]', 'generates_leading_space': False, 'system_prompt': None}}
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
0it [00:00, ?it/s]
0it [00:00, ?it/s]
Loaded 0 sources for potentially adding to UserData
0it [00:00, ?it/s]
0it [00:00, ?it/s]
Loaded 0 sources for potentially adding to UserData`

**Issue**

The app starts and generates results. However, this time it does not load onto VRAM but it maxes out my CPU and RAM usage while generating results (uses merely 9% of GPU and 90-95% of CPU). So, it appears that the app is using CPU compute power to generate results. 
I strongly suspect that it’s not using my GPU compute power to generate results.

**Moreover**, during my previous issue [unable to run the app](https://github.com/h2oai/h2ogpt/issues/620), I was able to get the program to work only on CPU mode, and it was able to generate results in 10-20 seconds. i.e.,

Question: Hi
Answer: Hey there! How’s it going?

But now, even though it loads onto VRAM, it takes 1:15 min- 1:30 min for generating similar results.

**Here’s some more diagnostic data:**

The `nvidia-smi` command gives the following results:

+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 536.99                 Driver Version: 536.99       CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 4060 ...  WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   49C    P8               2W /  45W |   7944MiB /  8188MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A     21752      C   D:\miniconda3\envs\h2ogpt\python.exe      N/A      |
+---------------------------------------------------------------------------------------+

**Comment by bsudhanva** [comment]
Sorry for the typo, yes it is offloading fully to vram, but its offloading onto ram as well, and it only uses cpu to compute, but slower, as compared to CPU only mode.

and about offloading less layers

I tried this command
(h2ogpt) C:\Users\sudha\h2ogpt>python generate.py --base_model='llama' --prompt_type=llama2 --score_model=None --langchain_mode='UserData' --user_path=user_path --llamacpp_dict="{n_gpu_layers=20}

and gives the following error

` Traceback (most recent call last):
  File "C:\Users\username\h2ogpt\generate.py", line 16, in <module>
    entrypoint_main()
  File "C:\Users\username\h2ogpt\generate.py", line 12, in entrypoint_main
    H2O_Fire(main)
  File "C:\Users\username\h2ogpt\src\utils.py", line 57, in H2O_Fire
    fire.Fire(component=component, command=args)
  File "C:\Users\username\miniconda3\envs\h2ogpt\lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\Users\username\miniconda3\envs\h2ogpt\lib\site-packages\fire\core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "C:\Users\username\miniconda3\envs\h2ogpt\lib\site-packages\fire\core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "C:\Users\username\h2ogpt\src\gen.py", line 546, in main
    llamacpp_dict = ast.literal_eval(llamacpp_dict)
  File "C:\Users\username\miniconda3\envs\h2ogpt\lib\ast.py", line 64, in literal_eval
    node_or_string = parse(node_or_string.lstrip(" \t"), mode='eval')
  File "C:\Users\username\miniconda3\envs\h2ogpt\lib\ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 1
    {n_gpu_layers=20}
     ^^^^^^^^^^^^^^^
SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='? `

**Comment by pseudotensor** [comment]
The dict is a python dict, I give example in gen.py or `python generate.py --help` like this:
```
e.g. python generate.py --base_model='llama' --prompt_type=llama2 --score_model=None --langchain_mode='UserData' --user_path=user_path --llamacpp_dict="{'n_gpu_layers':25,'n_batch':128}"
```

but you can choose fewer layers or smaller batch

**Comment by bsudhanva** [comment]
@pseudotensor I tried it , still facing same issue. 90% cpu and max ram usage and 9% gpu usage, plus very slow/laggy response.

this is from the command prompt for your refrence

Using Model llama
Prep: persist_directory=db_dir_UserData exists, user_path=user_path passed, adding any changed or new documents
0it [00:00, ?it/s]
0it [00:00, ?it/s]
Loaded 0 sources for potentially adding to UserData
Prep: persist_directory= does not exist, regenerating
Did not generate db since no sources
Prep: persist_directory= does not exist, regenerating
Did not generate db since no sources
Starting get_model: llama
Could not determine --max_seq_len, setting to 2048.  Pass if not correct
Already have llama-2-7b-chat.ggmlv3.q8_0.bin from url https://huggingface.co/TheBloke/Llama-2-7B-Chat-GGML/resolve/main/llama-2-7b-chat.ggmlv3.q8_0.bin, delete file if invalid
ggml_init_cublas: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 4060 Laptop GPU, compute capability 8.9
llama.cpp: loading model from llama-2-7b-chat.ggmlv3.q8_0.bin
llama_model_load_internal: format     = ggjt v3 (latest)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 2048
llama_model_load_internal: n_embd     = 4096
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 32
llama_model_load_internal: n_layer    = 32
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: freq_base  = 10000.0
llama_model_load_internal: freq_scale = 1
llama_model_load_internal: ftype      = 7 (mostly Q8_0)
llama_model_load_internal: n_ff       = 11008
llama_model_load_internal: model size = 7B
llama_model_load_internal: ggml ctx size =    0.08 MB
warning: failed to VirtualLock 81920-byte buffer (after previously locking 0 bytes): Invalid access to memory location.

llama_model_load_internal: using CUDA for GPU acceleration
llama_model_load_internal: mem required  = 3373.38 MB (+ 1026.00 MB per state)
llama_model_load_internal: allocating batch_size x (512 kB + n_ctx x 128 B) = 384 MB VRAM for the scratch buffer
llama_model_load_internal: offloading 25 repeating layers to GPU
llama_model_load_internal: offloaded 25/35 layers to GPU
llama_model_load_internal: total VRAM used: 5512 MB
llama_new_context_with_model: kv self size  = 1024.00 MB
AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | VSX = 0 |
Model {'base_model': 'llama', 'tokenizer_base_model': '', 'lora_weights': '', 'inference_server': '', 'prompt_type': 'llama2', 'prompt_dict': {'promptA': '', 'promptB': '', 'PreInstruct': '<s>[INST] ', 'PreInput': None, 'PreResponse': '[/INST]', 'terminate_response': ['[INST]', '</s>'], 'chat_sep': ' ', 'chat_turn_sep': ' </s>', 'humanstr': '[INST]', 'botstr': '[/INST]', 'generates_leading_space': False, 'system_prompt': None}}
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
0it [00:00, ?it/s]
0it [00:00, ?it/s]
Loaded 0 sources for potentially adding to UserData


and `Nvidia-smi` gives
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 536.99                 Driver Version: 536.99       CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 4060 ...  WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   50C    P8               2W /  45W |   6832MiB /  8188MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A     17136      C   D:\miniconda3\envs\h2ogpt\python.exe      N/A      |
+---------------------------------------------------------------------------------------+

**Comment by pseudotensor** [comment]
Did it ever work for you properly?

**Comment by bsudhanva** [comment]
I mean it was kinda working previously when it was only running from cpu+ram. But couldn't for once get it to run only through GPU

**Comment by bsudhanva** [comment]
@pseudotensor related issue

https://www.reddit.com/r/LocalLLaMA/comments/162wf4f/comment/jxzm7h3/.

Also this issue is specific to  models, some models are working as expected

**Comment by stratus-ss** [comment]
I am having what looks to be a similar problem to this.  I can see the process gets loaded into vram:

![image](https://github.com/h2oai/h2ogpt/assets/8162705/28d48647-08ae-4407-bfd3-ffbc9a45b17f)

However while running against a text file I uploaded its using only the CPU

![image](https://github.com/h2oai/h2ogpt/assets/8162705/66b05db2-d952-4f65-90e2-ecba1f27f05a)


I am using the following command to launch h2ogpt

```
export CUDA_VISIBLE_DEVICES="0,1"
LD_LIBRARY_PATH=/root/h2o/conda/envs/h2ogpt/lib/ python /root/h2ogpt/generate.py --base_model=h2oai/h2ogpt-oasst1-512-12b --load_8bit=True --score_model=None --langchain_mode='UserData' --user_path=user_path --use_gpu_id=False
```

The logs show

```
soundfile, librosa, and wavio not installed, disabling STT
soundfile, librosa, and wavio not installed, disabling TTS
Using Model h2oai/h2ogpt-oasst1-512-12b
load INSTRUCTOR_Transformer
max_seq_length  512
Must install DocTR and LangChain installed if enabled DocTR, disabling
Starting get_model: h2oai/h2ogpt-oasst1-512-12b
config.json: 100%|███████████████████████████████████████████████████████| 776/776 [00:00<00:00, 6.27MB/s]
tokenizer_config.json: 100%|█████████████████████████████████████████████| 264/264 [00:00<00:00, 2.82MB/s]
tokenizer.json: 100%|████████████████████████████████████████████████| 2.11M/2.11M [00:00<00:00, 15.3MB/s]
special_tokens_map.json: 100%|██████████████████████████████████████████| 99.0/99.0 [00:00<00:00, 317kB/s]
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned 
or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned 
or trained.
pytorch_model.bin.index.json: 100%|██████████████████████████████████| 47.3k/47.3k [00:00<00:00, 1.49MB/s]
pytorch_model-00001-of-00005.bin: 100%|██████████████████████████████| 4.96G/4.96G [01:23<00:00, 59.1MB/s]
pytorch_model-00002-of-00005.bin: 100%|██████████████████████████████| 4.85G/4.85G [01:20<00:00, 59.9MB/s]
pytorch_model-00003-of-00005.bin: 100%|██████████████████████████████| 4.86G/4.86G [01:19<00:00, 61.2MB/s]
pytorch_model-00004-of-00005.bin: 100%|██████████████████████████████| 5.02G/5.02G [01:20<00:00, 62.6MB/s]
pytorch_model-00005-of-00005.bin: 100%|██████████████████████████████| 4.16G/4.16G [01:07<00:00, 61.9MB/s]
Downloading shards: 100%|███████████████████████████████████████████████████| 5/5 [06:33<00:00, 78.77s/it]
Loading checkpoint shards: 100%|████████████████████████████████████████████| 5/5 [00:14<00:00,  2.93s/it]
generation_config.json: 100%|████████████████████████████████████████████| 111/111 [00:00<00:00, 1.15MB/s]
Model {'base_model': 'h2oai/h2ogpt-oasst1-512-12b', 'base_model0': 'h2oai/h2ogpt-oasst1-512-12b', 'tokeniz
er_base_model': '', 'lora_weights': '', 'inference_server': '', 'prompt_type': 'human_bot', 'prompt_dict':
 {'promptA': '', 'promptB': '', 'PreInstruct': '<human>: ', 'PreInput': None, 'PreResponse': '<bot>:', 'te
rminate_response': ['\n<human>:', '\n<bot>:', '<human>:', '<bot>:', '<bot>:'], 'chat_sep': '\n', 'chat_tur
n_sep': '\n', 'humanstr': '<human>:', 'botstr': '<bot>:', 'generates_leading_space': True, 'system_prompt'
: 'auto', 'can_handle_system_prompt': False}, 'visible_models': None, 'h2ogpt_key': None, 'load_8bit': Tru
e, 'load_4bit': False, 'low_bit_mode': 1, 'load_half': True, 'use_flash_attention_2': False, 'load_gptq': 
'', 'load_awq': '', 'load_exllama': False, 'use_safetensors': False, 'revision': None, 'use_gpu_id': False
, 'gpu_id': 0, 'compile_model': None, 'use_cache': None, 'llamacpp_dict': {'n_gpu_layers': 100, 'use_mlock
': True, 'n_batch': 1024, 'n_gqa': 0, 'model_path_llama': '', 'model_name_gptj': '', 'model_name_gpt4all_l
lama': '', 'model_name_exllama_if_no_config': ''}, 'rope_scaling': {}, 'max_seq_len': 2048, 'exllama_dict'
: {}, 'gptq_dict': {}, 'attention_sinks': False, 'sink_dict': {}, 'truncation_generation': False, 'hf_mode
l_dict': {}}   
Begin auto-detect HF cache text generation models
End auto-detect HF cache text generation models
Begin auto-detect llama.cpp models
End auto-detect llama.cpp models
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
Started Gradio Server and/or GUI: server_name: localhost port: None
Use local URL: http://localhost:7860/
/root/h2o/h2o_venv/lib/python3.10/site-packages/pydantic/_internal/_fields.py:149: UserWarning: Field "model_name" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
/root/h2o/h2o_venv/lib/python3.10/site-packages/pydantic/_internal/_fields.py:149: UserWarning: Field "model_names" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
OpenAI API URL: http://0.0.0.0:5000
OpenAI API key: EMPTY
INFO:     192.168.99.198:58188 - "POST /upload HTTP/1.1" 200 OK
Found 0 new sources (0 have no hash in original source, so have to reprocess for migration to sources with hash)
Removing 0 duplicate files from db because ingesting those as new documents
```

**Comment by pseudotensor** [comment]
1) Can you please run with `--verbose=True --debug=True` and share logs?
2) Please check that torch can see your GPUs as in the readme_linux.md
   ```python
   import torch
   print(torch.cuda.is_available())
   ```
    should print True.

**Comment by stratus-ss** [comment]
I'll add those flags in and get you logs shortly.

For now, yes Torch can see the cards

```
(h2o_venv) (base) [root@gpt-gpu ~]# python3
Python 3.10.9 (main, Jan 11 2023, 15:21:40) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> print(torch.cuda.is_available())

True
```
