### ISSUE TITLE
CUDA Out of Memory with Multiple Documents

### ISSUE THREAD

**Issue by ffalkenberg** [h2oai/h2ogpt#694]
Hello maintainers,

I have encountered an issue when trying to prompt the Llama2 model. While I can successfully prompt the model after uploading a single document, I run into a CUDA out of memory error when I attempt to do the same after uploading two documents. This is my startup:
```python
python3.10 /workspace/generate.py \
          --base_model=meta-llama/Llama-2-13b-chat-hf \
          --prompt_type=llama2 \
          --save_dir='/workspace/save/' \
          --score_model=None \
          --max_max_new_tokens=2048 \
          --max_new_tokens=1024 \
          --num_async=3 \
          --top_k_docs=-1 \
          --use_auth_token=$HUGGING_FACE_HUB_TOKEN \
          --load_8bit=True
```
**One Document**

![18-08-2023_16-06-17](https://github.com/h2oai/h2ogpt/assets/48180924/61c281b1-38a9-4647-a0cd-6aa33859592d)

**Two Documents**

![18-08-2023_16-04-32](https://github.com/h2oai/h2ogpt/assets/48180924/51f0cea6-0a0d-49b1-8940-8c2f7752d5f3)

**Error Message:**

```
CUDA out of memory. Tried to allocate 1.27 GiB (GPU 0; 19.50 GiB total capacity; 16.04 GiB already allocated; 277.88 MiB free; 18.15 GiB reserved in total by PyTorch) 
If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```
Notably, the memory usage seems excessively high considering I'm only processing two documents. Additionally, it's worth mentioning that:

- Both documents are identical
- The documents are in PDF format
- They are scans of rare documents and have not been subjected to OCR beforehand

<details>
  <summary>View Stack Trace</summary>

```plaintext
load INSTRUCTOR_Transformer
max_seq_length  512
Xformers is not installed correctly. If you want to use memory_efficient_attention to accelerate training use the following command to install Xformers
pip install xformers.
The model 'OptimizedModule' is not supported for . Supported models are ['BartForCausalLM', 'BertLMHeadModel', 'BertGenerationDecoder', 'BigBirdForCausalLM', 'BigBirdPegasusForCausalLM', 'BioGptForCausalLM', 'BlenderbotForCausalLM', 'BlenderbotSmallForCausalLM', 'BloomForCausalLM', 'CamembertForCausalLM', 'CodeGenForCausalLM', 'CpmAntForCausalLM', 'CTRLLMHeadModel', 'Data2VecTextForCausalLM', 'ElectraForCausalLM', 'ErnieForCausalLM', 'GitForCausalLM', 'GPT2LMHeadModel', 'GPT2LMHeadModel', 'GPTBigCodeForCausalLM', 'GPTNeoForCausalLM', 'GPTNeoXForCausalLM', 'GPTNeoXJapaneseForCausalLM', 'GPTJForCausalLM', 'LlamaForCausalLM', 'MarianForCausalLM', 'MBartForCausalLM', 'MegaForCausalLM', 'MegatronBertForCausalLM', 'MvpForCausalLM', 'OpenLlamaForCausalLM', 'OpenAIGPTLMHeadModel', 'OPTForCausalLM', 'PegasusForCausalLM', 'PLBartForCausalLM', 'ProphetNetForCausalLM', 'QDQBertLMHeadModel', 'ReformerModelWithLMHead', 'RemBertForCausalLM', 'RobertaForCausalLM', 'RobertaPreLayerNormForCausalLM', 'RoCBertForCausalLM', 'RoFormerForCausalLM', 'RwkvForCausalLM', 'Speech2Text2ForCausalLM', 'TransfoXLLMHeadModel', 'TrOCRForCausalLM', 'XGLMForCausalLM', 'XLMWithLMHeadModel', 'XLMProphetNetForCausalLM', 'XLMRobertaForCausalLM', 'XLMRobertaXLForCausalLM', 'XLNetLMHeadModel', 'XmodForCausalLM'].
Number of requested results 1000 is greater than number of elements in index 16, updating n_results = 16
thread exception: (<class 'torch.cuda.OutOfMemoryError'>, OutOfMemoryError('CUDA out of memory. Tried to allocate 1.06 GiB (GPU 0; 19.50 GiB total capacity; 15.28 GiB already allocated; 1.01 GiB free; 17.41 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF'), <traceback object at 0x7fa4ee722b00>)
make stop: (<class 'torch.cuda.OutOfMemoryError'>, OutOfMemoryError('CUDA out of memory. Tried to allocate 1.06 GiB (GPU 0; 19.50 GiB total capacity; 15.28 GiB already allocated; 1.01 GiB free; 17.41 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF'), <traceback object at 0x7fa4ee722b00>)
hit stop
Traceback (most recent call last):
  File "/h2ogpt_conda/lib/python3.10/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/h2ogpt_conda/lib/python3.10/site-packages/gradio/blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "/h2ogpt_conda/lib/python3.10/site-packages/gradio/blocks.py", line 1123, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/h2ogpt_conda/lib/python3.10/site-packages/gradio/utils.py", line 349, in async_iteration
    return await iterator.__anext__()
  File "/h2ogpt_conda/lib/python3.10/site-packages/gradio/utils.py", line 342, in __anext__
    return await anyio.to_thread.run_sync(
  File "/h2ogpt_conda/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/h2ogpt_conda/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/h2ogpt_conda/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/h2ogpt_conda/lib/python3.10/site-packages/gradio/utils.py", line 325, in run_sync_iterator_async
    return next(iterator)
  File "/h2ogpt_conda/lib/python3.10/site-packages/gradio/utils.py", line 694, in gen_wrapper
    yield from f(*args, **kwargs)
  File "/workspace/src/gradio_runner.py", line 2323, in bot
    for res in get_response(fun1, history):
  File "/workspace/src/gradio_runner.py", line 2272, in get_response
    for output_fun in fun1():
  File "/workspace/src/gen.py", line 1903, in evaluate
    for r in run_qa_db(
  File "/workspace/src/gpt_langchain.py", line 2625, in _run_qa_db
    raise thread.exc
  File "/workspace/src/utils.py", line 398, in run
    self._return = self._target(*self._args, **self._kwargs)
  File "/h2ogpt_conda/lib/python3.10/site-packages/langchain/chains/base.py", line 258, in __call__
    raise e
  File "/h2ogpt_conda/lib/python3.10/site-packages/langchain/chains/base.py", line 252, in __call__
    self._call(inputs, run_manager=run_manager)
  File "/h2ogpt_conda/lib/python3.10/site-packages/langchain/chains/combine_documents/base.py", line 106, in _call
    output, extra_return_dict = self.combine_docs(
  File "/h2ogpt_conda/lib/python3.10/site-packages/langchain/chains/combine_documents/stuff.py", line 165, in combine_docs
    return self.llm_chain.predict(callbacks=callbacks, **inputs), {}
  File "/h2ogpt_conda/lib/python3.10/site-packages/langchain/chains/llm.py", line 252, in predict
    return self(kwargs, callbacks=callbacks)[self.output_key]
  File "/h2ogpt_conda/lib/python3.10/site-packages/langchain/chains/base.py", line 258, in __call__
    raise e
  File "/h2ogpt_conda/lib/python3.10/site-packages/langchain/chains/base.py", line 252, in __call__
    self._call(inputs, run_manager=run_manager)
  File "/h2ogpt_conda/lib/python3.10/site-packages/langchain/chains/llm.py", line 92, in _call
    response = self.generate([inputs], run_manager=run_manager)
  File "/h2ogpt_conda/lib/python3.10/site-packages/langchain/chains/llm.py", line 102, in generate
    return self.llm.generate_prompt(
  File "/h2ogpt_conda/lib/python3.10/site-packages/langchain/llms/base.py", line 451, in generate_prompt
    return self.generate(prompt_strings, stop=stop, callbacks=callbacks, **kwargs)
  File "/h2ogpt_conda/lib/python3.10/site-packages/langchain/llms/base.py", line 582, in generate
    output = self._generate_helper(
  File "/h2ogpt_conda/lib/python3.10/site-packages/langchain/llms/base.py", line 488, in _generate_helper
    raise e
  File "/h2ogpt_conda/lib/python3.10/site-packages/langchain/llms/base.py", line 475, in _generate_helper
    self._generate(
  File "/h2ogpt_conda/lib/python3.10/site-packages/langchain/llms/base.py", line 961, in _generate
    self._call(prompt, stop=stop, run_manager=run_manager, **kwargs)
  File "/h2ogpt_conda/lib/python3.10/site-packages/langchain/llms/huggingface_pipeline.py", line 168, in _call
    response = self.pipeline(prompt)
  File "/h2ogpt_conda/lib/python3.10/site-packages/transformers/pipelines/text_generation.py", line 201, in __call__
    return super().__call__(text_inputs, **kwargs)
  File "/h2ogpt_conda/lib/python3.10/site-packages/transformers/pipelines/base.py", line 1120, in __call__
    return self.run_single(inputs, preprocess_params, forward_params, postprocess_params)
  File "/h2ogpt_conda/lib/python3.10/site-packages/transformers/pipelines/base.py", line 1127, in run_single
    model_outputs = self.forward(model_inputs, **forward_params)
  File "/h2ogpt_conda/lib/python3.10/site-packages/transformers/pipelines/base.py", line 1026, in forward
    model_outputs = self._forward(model_inputs, **forward_params)
  File "/workspace/src/h2oai_pipeline.py", line 159, in _forward
    return self.__forward(model_inputs, **generate_kwargs)
  File "/workspace/src/h2oai_pipeline.py", line 195, in __forward
    generated_sequence = self.model.generate(input_ids=input_ids, attention_mask=attention_mask, **generate_kwargs)
  File "/h2ogpt_conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/h2ogpt_conda/lib/python3.10/site-packages/transformers/generation/utils.py", line 1522, in generate
    return self.greedy_search(
  File "/h2ogpt_conda/lib/python3.10/site-packages/transformers/generation/utils.py", line 2339, in greedy_search
    outputs = self(
  File "/h2ogpt_conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/h2ogpt_conda/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/h2ogpt_conda/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 688, in forward
    outputs = self.model(
  File "/h2ogpt_conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/h2ogpt_conda/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/h2ogpt_conda/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 578, in forward
    layer_outputs = decoder_layer(
  File "/h2ogpt_conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/h2ogpt_conda/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/h2ogpt_conda/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 292, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/h2ogpt_conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/h2ogpt_conda/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/h2ogpt_conda/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 231, in forward
    attn_weights = nn.functional.softmax(attn_weights, dim=-1, dtype=torch.float32).to(query_states.dtype)
  File "/h2ogpt_conda/lib/python3.10/site-packages/torch/nn/functional.py", line 1845, in softmax
    ret = input.softmax(dim, dtype=dtype)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.06 GiB (GPU 0; 19.50 GiB total capacity; 15.28 GiB already allocated; 1.01 GiB free; 17.41 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

```
</details>

**Comment by pseudotensor** [comment]
Using `--top_k_docs=-1` is filling up the context of the model, so uses maximum amount of memory.  You have a few options:
* Leave top_k_docs as default of 3 to 4, or set it
* Use smaller model
* Use same model but quantized like AutoGPTQ from TheBloke using exllama or GGML from TheBloke
* Use 4-bit or 8-bit, esp. 4-bit is quite efficient and after recent fixes is quite fast.

**Comment by ffalkenberg** [comment]
Thank you for the clarification on the --top_k_docs=-1 issue. I appreciate the suggested solutions.

However, I'd like to point out some ambiguities in the naming and definitions provided:

> `:param top_k_docs: number of chunks to give LLM`
> `:param chunk: Whether to chunk data (True unless know data is already optimally chunked)`
> `:param chunk_size: Size of chunks, with typically top-4 passed to LLM, so needs to be in context length`

From the above definition, it appears that `top_k_docs` might be more appropriately named `top_k_chunks`. 

Considering a large document could be divided into hundreds of chunks based on the `chunk` and `chunk_size` parameters, it's essential to have a clear distinction.

Furthermore, it seems intuitive that there should be a way to process the chunks serially, especially if the model's context is being filled up. This would allow for processing without overloading the memory.

**Comment by pseudotensor** [comment]
top_k_docs started as number of chunks, but it applies to summarization too now, when it is not chunks but pages or other document parts however the parser did its job.  So it's not always chunk number.  I can update doc string.

Managing parameters to fit into memory is generally extraordinarily challenging.  However,  you can vary max_seq_len to limit your use of the model's sequence length while still using top_k_docs=-1 to auto-fill that context.
