### ISSUE TITLE
docker run hit permission denied issue on '/workspace/.cache/huggingface'

### ISSUE THREAD

**Issue by robinliubin** [h2oai/h2ogpt#729]
```
[ec2-user@ip-10-0-102-5 ~]$ sudo docker run \
       --gpus all \
       --runtime=nvidia \
       --shm-size=2g \
       -p 7860:7860 \
       --rm --init \
       -v "${HOME}"/.cache:/workspace/.cache \
       -v "${HOME}"/save:/workspace/save \
       gcr.io/vorvan/h2oai/h2ogpt-runtime:0.1.0 /workspace/generate.py \
          --base_model=h2oai/h2ogpt-4096-llama2-7b-chat \
          --use_safetensors=True \
          --prompt_type=llama2 \
          --save_dir='/workspace/save/' \
          --score_model=None \
          --max_max_new_tokens=2048 \
          --max_new_tokens=1024
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-9k89vsu8 because the default path (/workspace/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
There was a problem when trying to write in your cache folder (/workspace/.cache/huggingface/transformers/). You should set the environment variable TRANSFORMERS_CACHE to a writable directory.
Auto set langchain_mode=LLM.  Could use MyData instead.  To allow UserData to pull files from disk, set user_path or langchain_mode_paths, and ensure allow_upload_to_user_data=True
Using Model h2oai/h2ogpt-4096-llama2-7b-chat
Prep: persist_directory=db_dir_UserData exists, using
Starting get_model: h2oai/h2ogpt-4096-llama2-7b-chat
Traceback (most recent call last):
  File "/workspace/generate.py", line 16, in <module>
    entrypoint_main()
  File "/workspace/generate.py", line 12, in entrypoint_main
    H2O_Fire(main)
  File "/workspace/src/utils.py", line 60, in H2O_Fire
    fire.Fire(component=component, command=args)
  File "/h2ogpt_conda/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/h2ogpt_conda/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/h2ogpt_conda/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/workspace/src/gen.py", line 1008, in main
    model0, tokenizer0, device = get_model(reward_type=False,
  File "/workspace/src/gen.py", line 1356, in get_model
    config, _, max_seq_len = get_config(base_model, **config_kwargs, raise_exception=False)
  File "/workspace/src/gen.py", line 1075, in get_config
    config = AutoConfig.from_pretrained(base_model, use_auth_token=use_auth_token,
  File "/h2ogpt_conda/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 944, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/h2ogpt_conda/lib/python3.10/site-packages/transformers/configuration_utils.py", line 574, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/h2ogpt_conda/lib/python3.10/site-packages/transformers/configuration_utils.py", line 629, in _get_config_dict
    resolved_config_file = cached_file(
  File "/h2ogpt_conda/lib/python3.10/site-packages/transformers/utils/hub.py", line 417, in cached_file
    resolved_file = hf_hub_download(
  File "/h2ogpt_conda/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/h2ogpt_conda/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1159, in hf_hub_download
    os.makedirs(storage_folder, exist_ok=True)
  File "/h2ogpt_conda/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/h2ogpt_conda/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/h2ogpt_conda/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/workspace/.cache/huggingface'
```

**Comment by robinliubin** [comment]
this worked for me
```
docker run \
       --gpus all \
       --runtime=nvidia \
       --shm-size=2g \
       -p 7860:7860 \
       --rm --init \
       -v "${HOME}"/.cache:${HOME}/workspace/.cache \
       -v "${HOME}"/save:${HOME}/workspace/save \
       gcr.io/vorvan/h2oai/h2ogpt-runtime:0.1.0 /workspace/generate.py \
          --base_model=h2oai/h2ogpt-4096-llama2-7b-chat \
          --use_safetensors=True \
          --prompt_type=llama2 \
          --save_dir='${HOME}/workspace/save/' \
          --score_model=None \
          --max_max_new_tokens=2048 \
          --max_new_tokens=1024

```

**Comment by achraf-mer** [comment]
@robinliubin we will change the doc to include this change at the docker run:
```
-u `id -u`:`id -g`
```
the issue above means that your local ~/.cache is not writable by the docker's default user which is `h2ogpt`.

**Comment by robinliubin** [comment]
thanks @achraf-mer, let me try chmod 777 on ~/.cache for temp workaround

**Comment by achraf-mer** [comment]
fyi @robinliubin https://github.com/h2oai/h2ogpt/pull/730

**Comment by achraf-mer** [comment]
addressed in https://github.com/h2oai/h2ogpt/pull/730
