### ISSUE TITLE
ValueError: An event handler (bot) didn't receive enough input values (needed: 43, got: 39).

### ISSUE THREAD

**Issue by the-consultant-git** [h2oai/h2ogpt#769]
Hello there, 

Greetings!!!

I was trying to leverage the `Client` to access `Chat as API` using the latest available code from `main`. 

Here is the code below that I was trying : 

```python
from h2ogpt_client import Client

client = Client("http://0.0.0.0:7860")

chat_completion = client.chat_completion.create()
reply = chat_completion.chat_sync("Hey!!!!")

print(reply["user"])  # prints user prompt, i.e. "Hey!"
print(reply["gpt"])   # prints reply from h2oGPT
``` 

But this always resulted in the following error : 
```
Traceback (most recent call last):
  File "/Users/user/Work/Extras/LocalGPT/h2ogpt/test.py", line 14, in <module>
    reply = chat_completion.chat_sync("Hey!!!!")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/h2ogpt_client/_core.py", line 288, in chat_sync
    response = self._client._predict(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/h2ogpt_client/_core.py", line 44, in _predict
    return self._client.submit(*args, api_name=api_name).result()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/gradio_client/client.py", line 1126, in result
    raise self.future._exception  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/gradio_client/client.py", line 787, in _inner
    predictions = _predict(*data)
                  ^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/gradio_client/client.py", line 818, in _predict
    raise ValueError(result["error"])
ValueError: An event handler (bot) didn't receive enough input values (needed: 43, got: 39).
Check if the event handler calls a Javascript function, and make sure its return value is correct.
Wanted inputs:
    [textbox, textbox, textbox, checkbox, dropdown, textbox, slider, slider, slider, slider, slider, slider, checkbox, slider, slider, slider, checkbox, checkbox, textbox, textbox, radio, checkbox, radio, dropdown, slider, checkbox, number, radio, dropdown, textbox, textbox, textbox, textbox, textbox, checkboxgroup, checkboxgroup, checkboxgroup, textbox, state, state, state, state, chatbot]
Received inputs:
    ["Hey!!!!", "", "", False, 0, "", 1.0, 1.0, 40, 1.0, 128, 0, False, 180, 1.07, 1, False, True, "", "", "Disabled", False, "Query", [], 4, True, 512, "Relevant", [], "", "", "", "", "", [['Hey!!!!', None]], None, None, None, None]
``` 

I used the following command to start the server : 
```
python generate.py --base_model='llama' --prompt_type=llama2
``` 
Can anyone please help me with it?

Thanx :)

**Comment by pseudotensor** [comment]
I think your client and server must be out of sync.  You seem to have old client and new server.  Please rebuilt the client.

I did that and all seems fine:

```
(h2ogpt) jon@pseudotensor:~/h2ogpt$ python
Python 3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:40:32) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> client = Client("http://0.0.0.0:7860")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'Client' is not defined
>>> from h2ogpt_client import Client
>>> client = Client("http://0.0.0.0:7860")
>>> text_completion = client.text_completion.create()
>>> response = text_completion.complete_sync("Hello world")
>>> response
" Hello! It's nice to meet you.\n\nIs there something I can help you with or would you like to chat?"
>>> 

```

**Comment by the-consultant-git** [comment]
HI @pseudotensor , `text_completion` is working fine.. The problem is with the `chat_completion` . Can you please give it a try too ?

**Comment by the-consultant-git** [comment]
I tried to re-build the h2o client, and it is giving me the same error @pseudotensor

**Comment by pseudotensor** [comment]
Sorry about that.  I need to make sure I test client stuff when testing rest.

**Comment by the-consultant-git** [comment]
I have seen the commit : [https://github.com/h2oai/h2ogpt/commit/87be7a3fe79e5bfa8bbf30a308949a013ac0e55f](https://github.com/h2oai/h2ogpt/commit/87be7a3fe79e5bfa8bbf30a308949a013ac0e55f) . This code is there.. but still I get the error. I am using the nearly latest code from main

**Comment by pseudotensor** [comment]
Did you rebuild the client and install it?  All the commands work for me now.

**Comment by the-consultant-git** [comment]
I fetched the lates code from main... and ran it again. Now it works.. Thanx a lot :)
