### ISSUE TITLE
Error in make_db.py or generate.py

### ISSUE THREAD

**Issue by hz01** [h2oai/h2ogpt#801]
whenever i try to run make_db pr generate i get this error

Using Model h2oai/h2ogpt-4096-llama2-7b-chat
Prep: persist_directory=db_dir_UserData exists, using
load INSTRUCTOR_Transformer
max_seq_length  512
Traceback (most recent call last):
  File "/home/arcinaai/Desktop/h2ogpt/generate.py", line 16, in <module>
    entrypoint_main()
  File "/home/arcinaai/Desktop/h2ogpt/generate.py", line 12, in entrypoint_main
    H2O_Fire(main)
  File "/home/arcinaai/Desktop/h2ogpt/src/utils.py", line 60, in H2O_Fire
    fire.Fire(component=component, command=args)
  File "/home/arcinaai/anaconda3/envs/h2ogpt/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/arcinaai/anaconda3/envs/h2ogpt/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/arcinaai/anaconda3/envs/h2ogpt/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/arcinaai/Desktop/h2ogpt/src/gen.py", line 961, in main
    db = prep_langchain(persist_directory1,
  File "/home/arcinaai/Desktop/h2ogpt/src/gpt_langchain.py", line 2342, in prep_langchain
    get_existing_db(None, persist_directory, load_db_if_exists,
  File "/home/arcinaai/Desktop/h2ogpt/src/gpt_langchain.py", line 2447, in get_existing_db
    db = Chroma(persist_directory=persist_directory, embedding_function=embedding,
  File "/home/arcinaai/anaconda3/envs/h2ogpt/lib/python3.10/site-packages/langchain/vectorstores/chroma.py", line 119, in __init__
    self._client = chromadb.Client(_client_settings)
  File "/home/arcinaai/anaconda3/envs/h2ogpt/lib/python3.10/site-packages/chromadb/__init__.py", line 31, in Client
    api = system.instance(API)
  File "/home/arcinaai/anaconda3/envs/h2ogpt/lib/python3.10/site-packages/chromadb/config.py", line 162, in instance
    impl = type(self)
  File "/home/arcinaai/anaconda3/envs/h2ogpt/lib/python3.10/site-packages/chromadb/api/local.py", line 64, in __init__
    self._db = self.require(DB)
  File "/home/arcinaai/anaconda3/envs/h2ogpt/lib/python3.10/site-packages/chromadb/config.py", line 114, in require
    inst = self._system.instance(type)
  File "/home/arcinaai/anaconda3/envs/h2ogpt/lib/python3.10/site-packages/chromadb/config.py", line 162, in instance
    impl = type(self)
  File "/home/arcinaai/anaconda3/envs/h2ogpt/lib/python3.10/site-packages/chromadb/db/duckdb.py", line 445, in __init__
    self.load()
  File "/home/arcinaai/anaconda3/envs/h2ogpt/lib/python3.10/site-packages/chromadb/db/duckdb.py", line 503, in load
    self._conn.execute(
duckdb.Error: Invalid Error: Payload value bigger than allowed. Corrupted file?

**Comment by pseudotensor** [comment]
I haven't seen that before.  Are you able to reproduce this?  Is there something unique about what you are doing?

**Comment by hz01** [comment]
i put around 27000 txt files in user_path sizes ranging from a few kbs to 200-300kbs

**Comment by pseudotensor** [comment]
The only hit I found in google was this: https://stackoverflow.com/questions/71464152/query-parquet-file-with-d

Saying it's a bug that was fixed, but we are using duckdb that is after that fix.

I've used h2oGPT with 20GB database of half of wikipedia and didn't hit any issue.  So probably still something unique about your case, or you ran out of disk space, ran out of memory, etc.

**Comment by hz01** [comment]
i have 64gb ram, 2 x 3090 and an i7 13700k
