### ISSUE TITLE
Docker build seems broken

### ISSUE THREAD

**Issue by xVinci6** [h2oai/h2ogpt#826]
Hi,

The docker build (I tried a few recent commits, Dockerfile and docker_build_script_ubuntu as provided on your branches with no modifications) will only work with weaviate. If launching without weaviate and using duckdb, the following happens:

```
Adding to db
Traceback (most recent call last):
  File "/workspace/generate.py", line 16, in <module>
    entrypoint_main()
  File "/workspace/generate.py", line 12, in entrypoint_main
    H2O_Fire(main)
  File "/workspace/src/utils.py", line 59, in H2O_Fire
    fire.Fire(component=component, command=args)
  File "/h2ogpt_conda/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/h2ogpt_conda/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/h2ogpt_conda/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/workspace/src/gen.py", line 990, in main
    db = prep_langchain(persist_directory1,
  File "/workspace/src/gpt_langchain.py", line 2419, in prep_langchain
    db, num_new_sources, new_sources_metadata = make_db(**langchain_kwargs)
  File "/workspace/src/gpt_langchain.py", line 2567, in make_db
    return _make_db(**langchain_kwargs)
  File "/workspace/src/gpt_langchain.py", line 2813, in _make_db
    db = get_db(sources, use_openai_embedding=use_openai_embedding, db_type=db_type,
  File "/workspace/src/gpt_langchain.py", line 135, in get_db
    db = Chroma.from_documents(documents=sources,
  File "/h2ogpt_conda/lib/python3.10/site-packages/langchain/vectorstores/chroma.py", line 603, in from_documents
    return cls.from_texts(
  File "/h2ogpt_conda/lib/python3.10/site-packages/langchain/vectorstores/chroma.py", line 558, in from_texts
    chroma_collection = cls(
  File "/h2ogpt_conda/lib/python3.10/site-packages/langchain/vectorstores/chroma.py", line 120, in __init__
    self._client = chromadb.Client(_client_settings)
  File "/h2ogpt_conda/lib/python3.10/site-packages/chromadb/__init__.py", line 35, in Client
    return system.get_api()
  File "/h2ogpt_conda/lib/python3.10/site-packages/chromadb/config.py", line 97, in get_api
    self.api = self._instantiate("chroma_api_impl")
  File "/h2ogpt_conda/lib/python3.10/site-packages/chromadb/config.py", line 87, in _instantiate
    impl = cls(self)
  File "/h2ogpt_conda/lib/python3.10/site-packages/chromadb/api/local.py", line 57, in __init__
    self._db = system.get_db()
  File "/h2ogpt_conda/lib/python3.10/site-packages/chromadb/config.py", line 92, in get_db
    self.db = self._instantiate("chroma_db_impl")
  File "/h2ogpt_conda/lib/python3.10/site-packages/chromadb/config.py", line 85, in _instantiate
    module = importlib.import_module(module_name)
  File "/h2ogpt_conda/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/h2ogpt_conda/lib/python3.10/site-packages/chromadb/db/duckdb.py", line 14, in <module>
    import duckdb
  File "/h2ogpt_conda/lib/python3.10/site-packages/duckdb/__init__.py", line 4, in <module>
    import duckdb.functional as functional
  File "/h2ogpt_conda/lib/python3.10/site-packages/duckdb/functional/__init__.py", line 1, in <module>
    from duckdb.duckdb.functional import (
ImportError: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /h2ogpt_conda/lib/python3.10/site-packages/duckdb/duckdb.cpython-310-x86_64-linux-gnu.so)
```

I have tried to find a way to either add the dependency or configure it correctly, but to no avail. Sorry I could not help.

**Comment by pselvana** [comment]
Looks like the problem is because the conda version of libstdc++.so.6 isn't in the LD_LIBRARY_PATH early enough.  It has the right GLIBC version whereas the /lib/x86_64-linu-gnu version stops at 3.4.28.

Quick workaround was the following in the container:
%  export LD_LIBRARY_PATH=/h2ogpt_conda/lib:$LD_LIBRARY_PATH

Or adding the following to your docker run command before the image name:
       -e LD_LIBRARY_PATH=/h2ogpt_conda/lib \

**Comment by achraf-mer** [comment]
This fixes: https://github.com/h2oai/h2ogpt/pull/834, don't need to pin to conda's libc as we might get into issues depending on which dependency is loaded first, see PR.
