### ISSUE TITLE
TheBloke/Llama-2-13B-chat-GPTQ not found

### ISSUE THREAD

**Issue by slavag** [h2oai/h2ogpt#886]
Hi,
I'm trying to run `python generate.py --base_model=TheBloke/Llama-2-13B-chat-GPTQ --load_gptq="gptq_model-4bit-128g" --use_safetensors=True --prompt_type=llama2`
And getting next error :
```
Using Model thebloke/llama-2-13b-chat-gptq
Starting get_model: TheBloke/Llama-2-13B-chat-GPTQ 
/mnt/miniconda3/envs/python311/lib/python3.11/site-packages/transformers/models/auto/configuration_auto.py:1006: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers.
  warnings.warn(
/mnt/miniconda3/envs/python311/lib/python3.11/site-packages/transformers/models/auto/tokenization_auto.py:640: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers.
  warnings.warn(
/mnt/miniconda3/envs/python311/lib/python3.11/site-packages/transformers/models/auto/configuration_auto.py:1006: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers.
  warnings.warn(
device_map: {'': 0}
/mnt/miniconda3/envs/python311/lib/python3.11/site-packages/transformers/utils/hub.py:374: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers.
  warnings.warn(
Traceback (most recent call last):
  File "/mnt/AI/h2ogpt/generate.py", line 16, in <module>
    entrypoint_main()
  File "/mnt/AI/h2ogpt/generate.py", line 12, in entrypoint_main
    H2O_Fire(main)
  File "/mnt/AI/h2ogpt/src/utils.py", line 59, in H2O_Fire
    fire.Fire(component=component, command=args)
  File "/mnt/miniconda3/envs/python311/lib/python3.11/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/miniconda3/envs/python311/lib/python3.11/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/mnt/miniconda3/envs/python311/lib/python3.11/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/AI/h2ogpt/src/gen.py", line 1162, in main
    model0, tokenizer0, device = get_model(reward_type=False,
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/AI/h2ogpt/src/gen.py", line 1639, in get_model
    return get_hf_model(load_8bit=load_8bit,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/AI/h2ogpt/src/gen.py", line 1802, in get_hf_model
    model = get_non_lora_model(base_model, model_loader, load_half, load_gptq,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/AI/h2ogpt/src/gen.py", line 1386, in get_non_lora_model
    model = model_loader(
            ^^^^^^^^^^^^^
  File "/mnt/miniconda3/envs/python311/lib/python3.11/site-packages/auto_gptq/modeling/auto.py", line 108, in from_quantized
    return quant_func(
           ^^^^^^^^^^^
  File "/mnt/miniconda3/envs/python311/lib/python3.11/site-packages/auto_gptq/modeling/_base.py", line 791, in from_quantized
    raise FileNotFoundError(f"Could not find model in {model_name_or_path}")
FileNotFoundError: Could not find model in TheBloke/Llama-2-13B-chat-GPTQ
```

What can be an issue here ?
Thanks

**Comment by pseudotensor** [comment]
TheBloke changed all his models to prepare for native transformers autogptq, breaking all prior usage.  It's easy to fix however, just use "model" instead of the specific "load_gptq" instance, like:

```
python generate.py --base_model=TheBloke/Llama-2-13B-chat-GPTQ --load_gptq=model --use_safetensors=True --prompt_type=llama2
```

**Comment by slavag** [comment]
@pseudotensor thanks a lot
