### ISSUE TITLE
cannot import name 'flash_attn_func' from 'flash_attn'

### ISSUE THREAD

**Issue by MSZ-MGS** [h2oai/h2ogpt#936]
Please take a quick look to this error and advise.
H2ogpt is the latest.

(h2ogpt) G:\Users\mazen\OneDrive\Desktop\AI\H2OGPT\H2oGPT>python generate.py --base_model='llama' --model_path_llama=AddedModels\mistral-7b-instruct-v0.1\mistral-7b-instruct-v0.1.Q5_K_S.gguf --prompt_type=mistral --score_model=None --langchain_mode='UserData' --user_path=user_path --llamacpp_dict="{'n_gpu_layers':35,'n_batch':128}" --do_sample=True --top_k_docs=-1 --temperature=0.7 --repetition_penalty=1.1 --top_p=0.9 --max_seq_len=4096 --share=False
Using Model llama
load INSTRUCTOR_Transformer
max_seq_length  512
0it [00:00, ?it/s]
0it [00:00, ?it/s]
Loaded 0 sources for potentially adding to UserData
Starting get_model: llama
G:\Users\mazen\miniconda3\envs\h2ogpt\lib\site-packages\transformers\models\auto\configuration_auto.py:1020: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers.
  warnings.warn(
Traceback (most recent call last):
  File "G:\Users\mazen\miniconda3\envs\h2ogpt\lib\site-packages\transformers\utils\import_utils.py", line 1282, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "G:\Users\mazen\miniconda3\envs\h2ogpt\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "G:\Users\mazen\miniconda3\envs\h2ogpt\lib\site-packages\transformers\models\llama\modeling_llama.py", line 45, in <module>
    from flash_attn import flash_attn_func, flash_attn_varlen_func
ImportError: cannot import name 'flash_attn_func' from 'flash_attn' (G:\Users\mazen\miniconda3\envs\h2ogpt\lib\site-packages\flash_attn\__init__.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "G:\Users\mazen\OneDrive\Desktop\AI\H2OGPT\H2oGPT\generate.py", line 16, in <module>
    entrypoint_main()
  File "G:\Users\mazen\OneDrive\Desktop\AI\H2OGPT\H2oGPT\generate.py", line 12, in entrypoint_main
    H2O_Fire(main)
  File "G:\Users\mazen\OneDrive\Desktop\AI\H2OGPT\H2oGPT\src\utils.py", line 64, in H2O_Fire
    fire.Fire(component=component, command=args)
  File "G:\Users\mazen\miniconda3\envs\h2ogpt\lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "G:\Users\mazen\miniconda3\envs\h2ogpt\lib\site-packages\fire\core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "G:\Users\mazen\miniconda3\envs\h2ogpt\lib\site-packages\fire\core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "G:\Users\mazen\OneDrive\Desktop\AI\H2OGPT\H2oGPT\src\gen.py", line 1203, in main
    model0, tokenizer0, device = get_model(reward_type=False,
  File "G:\Users\mazen\OneDrive\Desktop\AI\H2OGPT\H2oGPT\src\gen.py", line 1610, in get_model
    get_loaders(model_name=base_model, reward_type=reward_type, llama_type=llama_type,
  File "G:\Users\mazen\OneDrive\Desktop\AI\H2OGPT\H2oGPT\src\loaders.py", line 77, in get_loaders
    from transformers import LlamaForCausalLM, LlamaTokenizer
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "G:\Users\mazen\miniconda3\envs\h2ogpt\lib\site-packages\transformers\utils\import_utils.py", line 1273, in __getattr__
    value = getattr(module, name)
  File "G:\Users\mazen\miniconda3\envs\h2ogpt\lib\site-packages\transformers\utils\import_utils.py", line 1272, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "G:\Users\mazen\miniconda3\envs\h2ogpt\lib\site-packages\transformers\utils\import_utils.py", line 1284, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.llama.modeling_llama because of the following error (look up to see its traceback):
cannot import name 'flash_attn_func' from 'flash_attn' (G:\Users\mazen\miniconda3\envs\h2ogpt\lib\site-packages\flash_attn\__init__.py)

(h2ogpt) G:\Users\mazen\OneDrive\Desktop\AI\H2OGPT\H2oGPT>

**Comment by pseudotensor** [comment]
Thanks for reporting.
1) Can you check if you revert via `pip install transformers==4.33.1 --upgrade` if you still see that?  transformers may be accidentally forcing need for flash attention package.
2) Can you try `pip install flash_attn` ?

**Comment by pseudotensor** [comment]
```
(h2ogpt) jon@pseudotensor:~/h2ogpt2$ CUDA_VISIBLE_DEVICES=0 python generate.py --base_model='llama' --model_path_llama=https://huggingface.co/TheBloke/Mistral-7B-Instruct-v0.1-GGUF/resolve/main/mistral-7b-instruct-v0.1.Q5_K_S.gguf --prompt_type=mistral --score_model=None --langchain_mode='UserData' --user_path=user_path --llamacpp_dict="{'n_gpu_layers':35,'n_batch':128}" --do_sample=True --top_k_docs=-1 --temperature=0.7 --repetition_penalty=1.1 --top_p=0.9 --max_seq_len=4096 --share=False
```

gives:

![image](https://github.com/h2oai/h2ogpt/assets/2249614/13c7b077-8744-42d1-b809-a5864333d45c)


and I don't have flash attention installed.

```
(h2ogpt) jon@pseudotensor:~/h2ogpt2$ pip freeze | grep flash
(h2ogpt) jon@pseudotensor:~/h2ogpt2$ 
```

**Comment by pseudotensor** [comment]
Also, unrelated a bit, you have max_seq_len for mistral at 4096, but it can easily handle 8192 if you have enough memory.  I think it can even handle 16k-32k, but I'm unclear on that.

**Comment by MSZ-MGS** [comment]
Thanks @pseudotensor for swift feedback, really appreciate your dedication to H2oGPT.

Just to clarify, this issue is happening also with LLama-2.
Yes both  transformers==4.34.0 and tokenizers==0.14.1 are installed on the same version.

I applied this command "pip install transformers==4.33.1 --upgrade" and the problem got resolved.

I'll test the context size later. I am still having issues in asking for "500 random sentences", I think I need to understand the parameters.
Thanks.

**Comment by MSZ-MGS** [comment]
FYI, it is installed when the issue was there.
![image](https://github.com/h2oai/h2ogpt/assets/65172063/10a45038-6e31-4dbb-850b-2203711ea728)

**Comment by pseudotensor** [comment]
For me FYI:
```
(h2ogpt) jon@pseudotensor:~/h2ogpt2$ pip show flash-attn
WARNING: Package(s) not found: flash-attn
(h2ogpt) jon@pseudotensor:~/h2ogpt2$ 
```

```
(h2ogpt) jon@pseudotensor:~/h2ogpt2$ pip freeze | grep 'trans\|token\|accel'
accelerate==0.22.0
asttokens==2.4.0
s3transfer==0.6.2
sentence-transformers==2.2.2
tiktoken==0.4.0
tokenizers==0.14.1
transformers==4.34.0
```

Perhaps you need to remove your flash attention package?

**Comment by MSZ-MGS** [comment]
So I uninstalled the flash_attn  and upgraded pip install transformers to 4.34.0 I received below errors for the first time:
![image](https://github.com/h2oai/h2ogpt/assets/65172063/98a53bf4-efb4-43f2-b892-817f815b74bc)
Further, the H2oGPT is opening, prompting but not responding anymore.
Then I checked the versions of the below dependencies and found the following:
accelerate==0.22.0 OK
asttokens==2.4.0 Not Installed! .... Why?!
s3transfer==0.6.2 OK
sentence-transformers==2.2.2 OK
tiktoken==0.4.0 OK
tokenizers==0.14.1 OK
transformers==4.34.0 OK

After installing the asttokens it worked, and started responding. However, another warning appeared:
![image](https://github.com/h2oai/h2ogpt/assets/65172063/5785c8b1-5a80-4af6-ae78-df84491704af)

**Comment by pseudotensor** [comment]
Hi, I have that package already, and did not manually install:
```
(h2ogpt) jon@pseudotensor:~/h2ogpt$ pip freeze | grep asttokens
asttokens==2.4.0
```

The warnings are just deprecation warnings after upgrading gradio.  They are not fatal, and I'll be changing the code to avoid them soon.
