### ISSUE TITLE
Does not work on MacOS M1

### ISSUE THREAD

**Issue by z4ce** [h2oai/h2ogpt#94]
I'm not sure if the desire is to fallback to Apple SDKs or to only support nVidia CUDA, but the requirement should be documented as a prereq.

```
╰─ python3 generate.py --base_model=h2oai/h2ogpt-oasst1-512-12b

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /opt/homebrew/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cpu.so
/opt/homebrew/lib/python3.11/site-packages/bitsandbytes/cextension.py:33: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
CUDA SETUP: Loading binary /opt/homebrew/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cpu.so...
dlopen(/opt/homebrew/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cpu.so, 0x0006): tried: '/opt/homebrew/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cpu.so' (not a mach-o file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cpu.so' (no such file), '/opt/homebrew/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cpu.so' (not a mach-o file)
No neptune configured, set NEPTUNE_API_TOKEN env var.

    WORLD_SIZE=4 CUDA_VISIBLE_DEVICES="0,1,2,3" torchrun --nproc_per_node=4 --master_port=1234 generate.py --base_model='EleutherAI/gpt-j-6B' --lora_weights=lora-alpaca_6B
    python generate.py --base_model='EleutherAI/gpt-j-6B' --lora_weights='lora-alpaca_6B'
    python generate.py --base_model='EleutherAI/gpt-neox-20b' --lora_weights='lora-alpaca_20B'

    # generate without lora weights, no prompt
    python generate.py --base_model='EleutherAI/gpt-neox-20b' --prompt_type='plain'
    python generate.py --base_model='togethercomputer/GPT-NeoXT-Chat-Base-20B' --prompt_type='dai_faq'

    python generate.py --base_model='togethercomputer/GPT-NeoXT-Chat-Base-20B' --prompt_type='dai_faq' --lora_weights='lora_20B_daifaq'
    # OpenChatKit settings:
    python generate.py --base_model='togethercomputer/GPT-NeoXT-Chat-Base-20B' --prompt_type='human_bot --debug=True --num_beams=1 --temperature=0.6 --top_k=40 --top_p=1.0

    python generate.py --base_model='distilgpt2' --prompt_type='plain' --debug=True --num_beams=1 --temperature=0.6 --top_k=40 --top_p=1.0 --share=False
    python generate.py --base_model='t5-large' --prompt_type='simple_instruct'
    python generate.py --base_model='philschmid/bart-large-cnn-samsum'
    python generate.py --base_model='philschmid/flan-t5-base-samsum'
    python generate.py --base_model='facebook/mbart-large-50-many-to-many-mmt'

    python generate.py --base_model='togethercomputer/GPT-NeoXT-Chat-Base-20B' --prompt_type='human_bot' --lora_weights='GPT-NeoXT-Chat-Base-20B.merged.json.8_epochs.57b2892c53df5b8cefac45f84d019cace803ef26.28'

    must have 4*48GB GPU and run without 8bit in order for sharding to work with infer_devices=False
    can also pass --prompt_type='human_bot' and model can somewhat handle instructions without being instruct tuned
    python generate.py --base_model=decapoda-research/llama-65b-hf --load_8bit=False --infer_devices=False --prompt_type='human_bot'

    python generate.py --base_model=h2oai/h2ogpt-oig-oasst1-512-6.9b


Using Model h2oai/h2ogpt-oasst1-512-12b
Get h2oai/h2ogpt-oasst1-512-12b model
Traceback (most recent call last):
  File "/Users/ianzink/git/h2ogpt/generate.py", line 1118, in <module>
    fire.Fire(main)
  File "/opt/homebrew/lib/python3.11/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ianzink/git/h2ogpt/generate.py", line 311, in main
    model0, tokenizer0, device = get_model(**all_kwargs)
                                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ianzink/git/h2ogpt/generate.py", line 434, in get_model
    device = get_device()
             ^^^^^^^^^^^^
  File "/Users/ianzink/git/h2ogpt/generate.py", line 328, in get_device
    raise RuntimeError("only cuda supported")
RuntimeError: only cuda supported
```

**Comment by pseudotensor** [comment]
Understood.  We removed 'mps' since usually will be too slow without quantization etc.  It's not hard to add back, but I don't have a mac to test it on.

**Comment by pseudotensor** [comment]
Now support MAC/Windows CPU mode, and plan to support mac MPS M1/M2.

**Comment by phdykd** [comment]
is there any update of availability of bitsandbytes for M2 MacOS? It is needed in QLORA...
Thanks

**Comment by pseudotensor** [comment]
Hi @phdykd , I'm not sure if it exists.  It would have be be compiled like the windows version was done: https://github.com/jllllll/bitsandbytes-windows-webui

Also, a challenge for me is I have linux with GPU, windows with GPU, and mac with CPU, but I don't have M1/M2.  So I'd need someone in wild to share how they did it if it can be done.

**Comment by InfuriatingYetti** [comment]
Hello everyone! 

I am new to the world of h2oGPT and I find it interesting! In offline mode I am seeing conversations about the CPU and GPU usage, and using one over the other in certain hardware circumstances. I was curious if it is possible to utilize the Apple Neural Engine (ANE) in conjunction with either the CPU or GPU, or if there is any added benefit? From what I have read the ANE is made specifically for AI and machine learning and am wondering what h2o would be like if it was able to harness this hardware (if it isn't already)...does using either the GPU or CPU in offline mode automatically utilize the ANE? I asked h2oGPT and it suggested to enable the GPU to utilize ANE...does anyone know if this is accurate?

Thank you!

**Comment by pseudotensor** [comment]
This issue was solved by @Mathanraj-Sharma 

I'm not familiar with ANE itself.
