### ISSUE TITLE
Add option to disable ssl verify check 

### ISSUE THREAD

**Issue by kalaiselvan263** [h2oai/h2ogpt#950]
https://support.h2o.ai/a/tickets/106627

Need option to disable ssl verify in code 

```
from gradio_client import Client
import ast
HOST_URL ="[https://eas-aimlservices-gtdcu.nam.nsroot.net:21425/"](https://eas-aimlservices-gtdcu.nam.nsroot.net:21425/%22)
client = Client(HOST_URL)
 # string of dict for input
kwargs = dict(instruction_nochat='Who are you?')
res = client.predict(str(dict(kwargs)), api_name='/submit_nochat_api')
 # string of dict for output
response = ast.literal_eval(res)['response']
print(response)
```

**Comment by pseudotensor** [comment]
This was done earlier.

These options from gradio are exposed:

```
        ssl_verify: bool = True,
        ssl_keyfile: str | None = None,
        ssl_certfile: str | None = None,
        ssl_keyfile_password: str | None = None,

```

**Comment by kalaiselvan263** [comment]
Customer have added the ssl_verify=False , However still they are getting the same error.


`(gradioclient) -bash-4.2$ python generate.py --ssl_verify=False
Loaded as API: https://eas-aimlservices-gtdcu.nam.nsroot.net:21425/ ✔
Traceback (most recent call last):
  File "/home/sr70157/.conda/envs/gradioclient/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/sr70157/.conda/envs/gradioclient/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/sr70157/.conda/envs/gradioclient/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/home/sr70157/.conda/envs/gradioclient/lib/python3.10/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/home/sr70157/.conda/envs/gradioclient/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/home/sr70157/.conda/envs/gradioclient/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/home/sr70157/.conda/envs/gradioclient/lib/python3.10/ssl.py", line 512, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/sr70157/.conda/envs/gradioclient/lib/python3.10/ssl.py", line 1070, in _create
    self.do_handshake()
  File "/home/sr70157/.conda/envs/gradioclient/lib/python3.10/ssl.py", line 1341, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "/home/sr70157/.conda/envs/gradioclient/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/home/sr70157/.conda/envs/gradioclient/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/home/sr70157/.conda/envs/gradioclient/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='eas-aimlservices-gtdcu.nam.nsroot.net', port=21425): Max retries exceeded with url: /config (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')))

(base) [root@aingtu4689 h2ogpt]# curl -LIk https://eas-aimlservices-gtdcu.nam.nsroot.net:21234/
HTTP/1.1 200 OK
date: Tue, 17 Oct 2023 07:48:53 GMT
server: uvicorn
content-length: 320578
content-type: text/html; charset=utf-8`

**Comment by pseudotensor** [comment]
@kalaiselvan263 Did they do something like this?  I don't know SSL much, but maybe even if don't verify, still need to set the other things:

https://stackoverflow.com/a/76405442

**Comment by pseudotensor** [comment]
solved and FAQ item added

**Comment by shodanx2** [comment]
Thank you that fixed my problem with SSL self-signed for 
https://github.com/Vincentqyw/youtube-dl-webui.git
unrelated to your project but this tread is top google link for 
gradio httpcore.ConnectError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate

**Comment by kschmid23** [comment]
what is the solution?
